<div id="article_type_delete_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Удалить тип статьи') . ' ➛ ' . $this->escape($this->article_type->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Предупреждение!'); ?></h4>
                <?php echo $this->translate('Вы действительно хотите удалить тип статьи ') . '"' . $this->escape($this->article_type->name) . '"?'; ?>
            </div>
            <?php echo $this->form; ?>
            <div class="article_type_item">
                <span><?php echo $this->translate('Название'); ?>:</span>
                <div class="article_type_name"><?php echo $this->escape($this->article_type->name); ?></div>
                <br>
                <span><?php echo $this->translate('Описание'); ?>:</span>
                <div class="article_type_descr"><?php echo $this->escape($this->article_type->description); ?></div>
                <div class="article_type_info">
                    <div class="article_type_name article_type_info_item"><?php echo $this->translate('Тип статьи'); ?></div>
                    <div class="article_type_date_create article_type_info_item"><span><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->article_type->date_create); ?></div>
                    <?php if ($this->escape($this->article_type->date_create) != $this->escape($this->article_type->date_edit)) { ?>
                        <div class="article_type_date_edit article_type_info_item"><span><?php echo $this->translate('Редактировалось') ?>: </span><?php echo $this->escape($this->article_type->date_edit); ?></div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>