<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Default_Model_UserRole', 'default');

/**
 * Default_Model_Base_UserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $UserID
 * @property integer $RoleID
 * @property Default_Model_Role $Role
 * @property Default_Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_UserRole extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_role');
        $this->hasColumn('ID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('UserID', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('RoleID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Role as Role', array(
             'local' => 'RoleID',
             'foreign' => 'ID'));

        $this->hasOne('Default_Model_User as User', array(
             'local' => 'UserID',
             'foreign' => 'ID'));
    }
}