<?php

if (!$this->breadcrumb) {
    $this->breadcrumb()->build();
}

$activeNav = $this->navigation($this->breadcrumb)->findByUri($this->url());
if ($activeNav != NULL) {
    $activeNav->active = true;
}
$partial = array('menu_layout/breadcrumb.phtml', 'default');
//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setMinDepth(0)->setSeparator("<span class='divider'> / </span>")->setLinkLast(false);
//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setMinDepth(0)->setLinkLast(false)->setPartial($partial)->render();
$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setPartial($partial)->setMinDepth(0)->setLinkLast(false);
//$this->navigation()->menu($this->main_menu)->setPartial($partial);


if ($breadcrumb != '') {
    ?>

    <?php echo($breadcrumb); ?>
<?php } ?>