<!-- Main Menu -->
<?php echo $this->render('default_layout/header/hd_main_menu.phtml'); ?>
<?php
$main_slider = Zend_Registry::get('slider');
if ($main_slider['show']) {
    echo $this->render("default_layout/slider.phtml");
}
?>
<div class="clearfix"></div>
<!-- Moving text-->
<?php
if ($this->hd_moving_text_block) {
    echo $this->render('default_layout/header/hd_mooving_text_block.phtml');
}
?>
<!-- Hot Lap -->
<?php
if ($this->hd_hot_lap_block) {
    echo $this->render('default_layout/header/hd_hot_lap_block.phtml');
}
?>