<div class="navbar navbar-static-top" role="navigation">
    <div class="container">
	<div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav">
		<a class="navbar-brand" href="#">ONLINE-RACING.NET</a>
	    </ul>
	    <p class="navbar-text pull-right">Signed in as <a href="#" class="navbar-link">Mark Otto</a></p>
	    <form class="navbar-form navbar-right" action="" role="search">
		<div class="form-group">
		    <input type="text" class="form-control" placeholder="<?php echo $this->translate('Поиск'); ?>">
		</div>
		<button type="submit" class="btn btn-default"><?php echo $this->translate('Поиск'); ?></button>
	    </form>
	</div>
    </div>
</div>