<div id="slider_block">
    <div id="main-slider" class="carousel slide">
	<ol class="carousel-indicators">
	    <li data-target="#main-slider" data-slide-to="0" class="active"></li>
	    <li data-target="#main-slider" data-slide-to="1"></li>
	    <li data-target="#main-slider" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
	    <div class="item active">
		<img src="/img/data/slider_posts/post_1.jpg" alt="">
		<div class="carousel-caption">
		    <h4>Online-Racing.Net - Sim-Racing Portal</h4>
		    <p>Да прибудет с вами скорость. ©</p>
		</div>
	    </div>
	    <div class="item">
		<img src="/img/data/slider_posts/post_3.jpg" alt="">
		<div class="carousel-caption">
		    <h4>Вы выбрали нужное место!</h4>
		    <p>На нашем портале вы гарантировано получите самые острые ощущение, море адреналина и захватывающей борьбы.</p>
		</div>
	    </div>
	    <div class="item">
		<img src="/img/data/slider_posts/F1RFT_2012_V2_logo.jpg" alt="">
		<div class="carousel-caption">
		    <h4>F1ORL 2013 2.1</h4>
		    <p>Наш мод основанный на F1RFT 2013 не даст вам скучать и подарит ощущения реального гонщкиа формулы-1.</p>
		</div>
	    </div>
	</div>
	<a class="left carousel-control" href="#main-slider" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#main-slider" data-slide="next">&rsaquo;</a>
    </div>
</div>