<div id="slider_block" class="block_item">
    <div id="carousel-main" class="carousel slide">
	<!-- Indicators -->
	<ol class="carousel-indicators">
	    <li data-target="#carousel-main" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-main" data-slide-to="1"></li>
	    <li data-target="#carousel-main" data-slide-to="2"></li>
	</ol>
	<!-- Wrapper for slides -->
	<div class="carousel-inner">
	    <div class="item active">
		<img src="/img/data/slider_posts/post_1.jpg" class="img-responsive" alt="">
		<div class="carousel-caption">
		    <h4>Online-Racing.Net - Sim-Racing Portal</h4>
		    <p>Да прибудет с вами скорость. ©</p>
		</div>
	    </div>
	    <div class="item">
		<img src="/img/data/slider_posts/post_3.jpg" class="img-responsive" alt="">
		<div class="carousel-caption">
		    <h4>Вы выбрали нужное место!</h4>
		    <p>На нашем портале вы гарантировано получите самые острые ощущение, море адреналина и захватывающей борьбы.</p>
		</div>
	    </div>
	    <div class="item">
		<img src="/img/data/slider_posts/F1RFT_2012_V2_logo.jpg" class="img-responsive" alt="">
		<div class="carousel-caption">
		    <h4>F1ORL 2013 2.3.2</h4>
		    <p>Встречайте наш обновленный мод. Еще более быстрый и стабильный. <a href="/post/92.html">Скачать</a></p>
		</div>
	    </div>
	</div>
	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-main" data-slide="prev">
	    <span class="icon-prev"></span>
	</a>
	<a class="right carousel-control" href="#carousel-main" data-slide="next">
	    <span class="icon-next"></span>
	</a>
    </div>
</div>