<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner ">
        <ul class="nav">
            <li class="active"><a href="<?php echo $this->baseUrl(''); ?>"><?php echo $this->translate('Главная') ?></a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <?php echo $this->translate('Контент') ?>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->baseUrl('article/add'); ?>"><?php echo $this->translate('Добавить') ?></a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-header"><?php echo $this->translate('Панель администратора') ?></li>
                    <li>
                        <a href="<?php echo $this->baseUrl('admin/articles'); ?>"><?php echo $this->translate('Просмотреть') ?></a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-header"><?php echo $this->translate('Сайт') ?></li>
                    <li>
                        <a href="<?php echo $this->baseUrl('article/all'); ?>"><?php echo $this->translate('Просмотреть') ?></a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <?php echo $this->translate('Пользователи') ?>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li class="nav-header"><?php echo $this->translate('Панель администратора') ?></li>
                    <li>
                        <a href="<?php echo $this->baseUrl('admin/users'); ?>"><?php echo $this->translate('Просмотреть') ?></a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-header"><?php echo $this->translate('Сайт') ?></li>
                    <li>
                        <a href="<?php echo $this->baseUrl('user/all'); ?>"><?php echo $this->translate('Просмотреть') ?></a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li>
                <a class="brand" href="<?php echo $this->baseUrl('admin'); ?>"><?php echo $this->translate('Администратор Online-Racing.Net') ?></a>
            </li>
        </ul>
    </div>
</div>