<?php

if (!isset($this->breadcrumb)) {
    $this->breadcrumb()->init();
}

// Store the container in the proxy helper:
//$this->getHelper('navigation')->setContainer($this->breadcrumb);

$activeNav = $this->navigation($this->breadcrumb)->findByUri($this->url());

if ($activeNav != null) {
    $activeNav->active = true;
}

$partial = array('parcials/breadcrumb-btn-group-iterate.phtml', 'default');

//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setPartial($partial)->setMinDepth(0)->setSeparator("<span class='divider'> / </span>")->setLinkLast(false);
//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setMinDepth(0)->setLinkLast(false)->setPartial($partial)->render();
$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setPartial($partial)->setMinDepth(0)->setLinkLast(
    false
)->render();?>

<?php if ($breadcrumb) : ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?=($breadcrumb); ?>
        </div>
    </div>
<?php endif; ?>