<?php

if (!isset($this->breadcrumb)) {
    $this->breadcrumb()->init();
}

// Store the container in the proxy helper:
//$this->getHelper('navigation')->setContainer($this->breadcrumb);

$activeNav = $this->navigation($this->breadcrumb)->findByUri($this->url());

if ($activeNav != null) {
    $activeNav->active = true;
}

$partial = array('parcials/breadcrumb-btn-group-iterate.phtml', 'default');

//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setPartial($partial)->setMinDepth(0)->setSeparator("<span class='divider'> / </span>")->setLinkLast(false);
//$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setMinDepth(0)->setLinkLast(false)->setPartial($partial)->render();
$breadcrumb = $this->navigation($this->breadcrumb)->breadcrumbs()->setPartial($partial)->setMinDepth(0)->setLinkLast(
    false
)->render();

if ($breadcrumb) :
    echo($breadcrumb);
endif;
?>