<div id="main-wrapper" class="container m-t-10">
    <div id="main" class="row clearfix">
        <!-- Content -->
        <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 m-b-10">
            <div class="row">
                <div class="col-lg-12">
                    <?php
                    $main_slider = Zend_Registry::get('slider');
                    if ($main_slider['show']) {
                        echo $this->render("layout-default/slider.phtml");
                    }
                    ?>
                </div>
            </div>
            <div id="content" class="m-t-10">
                <?php
                $breadcrumb = Zend_Registry::get('breadcrumb');
                $page_title = $this->pageTitle();

                if ($breadcrumb['show']) {
                    $breadcrumb_data = $this->render("layout-default/breadcrumb.phtml");
                }

                if ($page_title != "" || (isset($breadcrumb_data))) :
                    ?>
                    <div id="page_title_wrapper" class="block-item m-b-10 shadow-bottom-2-corners">
                        <?php if ($this->pageTitle() != ""): ?>
                            <div class="page_title"><h4><?php echo $this->pageTitle() ?></h4></div>
                        <?php endif; ?>
                        <?php
                        if ($breadcrumb['show']) {
                            echo $breadcrumb_data;
                        }
                        ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->showMessages(); ?>
                <div id="<?php echo $this->module . '-' . $this->controller . '-' . $this->action; ?>"
                     class="page">
                    <div class="page_content">
                        <?php echo $this->layout()->content ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- Left sidebar -->
        <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 m-t-10 m-b-10">
            <div id="sidebar-left" class="sidebar-left">
                <?php echo $this->render("layout-default/sidebar-left.phtml") ?>
            </div>
        </div>
    </div>
</div>