<div id="main-wrapper" class="container m-t-10">
    <div id="main" class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 m-b-10">
            <?php
            $main_slider = Zend_Registry::get('slider');
            if ($main_slider['show']) : ?>
                <!-- main-slider -->
                <div id="main-slider" class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <?= $this->render("layout-default/slider.phtml"); ?>
                    </div>
                </div>
                <!-- ./ main-slider -->
            <?php endif; ?>

            <!-- content -->
            <div id="content" class="row m-t-10">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <?php
                    $breadcrumb = Zend_Registry::get('breadcrumb');
                    $page_title = $this->pageTitle();

                    if ($breadcrumb['show']) {
                        $breadcrumb_data = $this->render("layout-default/breadcrumb.phtml");
                    }

                    if ($page_title != "" || (isset($breadcrumb_data))) : ?>
                        <div id="page_title_wrapper" class="block block-default m-b-10 shadow-bottom-2-corners">
                            <?php if ($this->pageTitle() != ""): ?>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="page_title">
                                            <h4><?= $this->pageTitle() ?></h4>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <?php if ($breadcrumb['show']) : ?>
                                <?= $breadcrumb_data; ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <?= $this->showMessages(); ?>
                    <div class="page">
                        <div class="page_content">
                            <?= $this->layout()->content ?>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./ content -->
        </div>
        <!-- left-sidebar -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 m-t-10 m-b-10">
            <div id="sidebar-right" class="sidebar sidebar-right">
                <?= $this->render("layout-default/sidebar-right.phtml") ?>
            </div>
        </div>
        <!-- ./ left-sidebar -->
    </div>
</div>