<!-- footer -->

<footer id="footer" class="m-t-10">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                            <div class="footer_logo center-block text-center">
                                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true) ?>">
                                    <img src="<?php echo $this->baseUrl('img/logo_190.png'); ?>" alt="<?php echo $this->translate('Online-Racing.net') ?>" />
                                </a>
                            </div>
                            <div class="center-block text-center">
                                <?php echo $this->translate('Online-Racing.Net') ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="footer_logo center-block text-center">
					<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true) ?>"><img src="<?php echo $this->baseUrl('img/logo_190.png'); ?>" alt="<?php echo $this->translate('Online-Racing.net') ?>"></a>
				</div>
				<div class="center-block text-center"><?php echo $this->translate('Online-Racing.Net') ?></div>
			</div>
			<div class="col-lg-6">
				<?php
				if ($this->ft_menu) {
					echo $this->render("layout-default/footer/ft_menu.phtml");
				}
				?>
			</div>
			<div class="col-lg-3">
				<div class="socialNetworks_slogan center-block text-center">
					<?php echo $this->translate('Наши ссылки в социальных сетях') ?>:
				</div>
				<?php
				if ($this->ft_socialNetworks_block) {
					echo $this->render("layout-default/footer/ft_socialNetworks_block.phtml");
				}
				?>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-lg-12">
				<div class="copyright center-block text-center">
					<?php echo $this->translate('Версия сайта') ?>:
                    <?php
                        $config = Zend_Registry::get('config');
                        echo $config->site->version;
                    ?>
                    <br>
					2012-2014 © Online-Racing.net
				</div>
				<?php
				if ($this->ft_web_counters_block) {
					echo $this->render("layout-default/footer/ft_web_counters_block.phtml");
				}
				?>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</footer>
<!-- ./ footer -->