<!-- footer -->
<div id="footer" class="m-t-10">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                            <div class="footer-logo center-block text-center">
                                <a href="<?= $this->url(
                                    array('module' => 'default', 'controller' => 'index', 'action' => 'index'),
                                    'default', true
                                ) ?>">
                                    <img src="<?= $this->baseUrl('img/logo_190.png'); ?>"
                                         alt="<?= $this->translate('Online-Racing.net') ?>"/>
                                </a>
                            </div>
                            <div class="center-block text-center">
                                <?= $this->translate('Online-Racing.Net') ?>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <?php
                            echo $this->render("layout-default/footer/footer-menu.phtml");
                            ?>
                            <div class="m-t-15 text-center">
                                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                                    <input type="hidden" name="cmd" value="_s-xclick">
                                    <input type="hidden" name="hosted_button_id" value="CS2E6ELNXDPAL">
                                    <input type="image" src="https://www.paypalobjects.com/en_US/RU/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                                    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                                </form>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                            <div class="social-networks center-block text-center">
                                <h6>
                                    <?= $this->translate('Наши ссылки в социальных сетях') ?>:
                                </h6>
                            <?php
                            echo $this->render("layout-default/footer/footer-scoial-networks.phtml");
                            ?>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="copyright center-block text-center">
                                <?= $this->translate('Версия сайта') ?>:
                                <?php
                                $config = Zend_Registry::get('config');
                                echo $config->site->version;
                                ?>
                                <br>
                                2012-2014 © Online-Racing.net
                            </div>
                            <?php
                            echo $this->render("layout-default/footer/ft_web_counters_block.phtml");
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- ./ footer -->