<!-- head-line -->
<div id="head-line">
    <div id="top-navbar" class="navbar-static-top">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#top-main-menu"
                                    data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <?php
                            $default_index_url = $this->url(
                                array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default',
                                true
                            );
                            ?>
                            <a href="<?php echo $default_index_url; ?>" class="pull-left">
                                <img src="<?php echo $this->baseUrl('data-content/ui/logo_orn.png'); ?>"
                                     class="img-responsive"/>
                            </a>
                        </div>
                        <!-- User Navbar -->
                        <div id="top-main-menu" class="collapse navbar-collapse">

                            <!-- User Navigation menu  -->
                            <?php echo $this->render("common/user-nav-menu.phtml") ?>
                            <!-- /User Navigation menu  -->
                            <?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'index', 'index')) : ?>
                                <?php
                                $adminIndexUrl = $this->url(
                                    array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), 'default'
                                );
                                ?>
                                <ul class="nav navbar-nav navbar-right">
                                    <li>
                                        <a href="<?php echo $adminIndexUrl; ?>">
                                            <i class="fa fa-bolt"></i> <?php echo $this->translate('Админ. Панель'); ?>
                                        </a>
                                    </li>
                                </ul>
                            <?php endif; ?>
                            <form class="navbar-form navbar-right m-r-5" action="#" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control"
                                           placeholder="<?php echo $this->translate('Поиск'); ?>">
                                </div>
                                <button type="submit" class="btn btn-default">
                                    <?php echo $this->translate('Поиск'); ?>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="sub-navbar" class="navbar-static-top shadow-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#bottom-main-menu"
                                    data-target=".navbar-ex2-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="bottom-main-menu" class="collapse navbar-collapse">
                            <?php
                            $partial = array('parcials/main-menu.phtml', 'default');
                            $this->navigation()->menu($this->main_menu)->setPartial($partial);
                            echo $this->navigation()->menu()->render();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if (isset($this->displayHeaderAuthoSignInForm) && ($this->displayHeaderAuthoSignInForm)) : ?>
        <!-- Modal with login form -->
        <div class="modal fade" id="loginModalForm" tabindex="-1" role="dialog"
             aria-labelledby="loginModalFormLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?php echo $this->translate("Авторизация") ?></h4>
                    </div>
                    <div class="modal-body">
                        <?php
                        // check access and generate link for default/auth/sign-in
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'auth', 'sign-in')) {
                            $defaultAuthSignInUrl = $this->url(
                                array('module' => 'default', 'controller' => 'auth', 'action' => 'sign-in'),
                                'default'
                            );
                        } else {
                            $defaultAuthSignInUrl = '#';
                        }
                        ?>

                        <?php
                        $authSignInForm = new Peshkov_Form_Auth_SignIn();
                        $authSignInForm->setAction($defaultAuthSignInUrl . '?redirectTo=' . $this->url());

                        echo $authSignInForm;
                        ?>
                        <br/>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- ./ Modal with login form -->
    <?php endif; ?>
</div>
<!-- ./ head-line -->