<div class="row">
    <?php echo $this->partial("layout-default/sidebar/calendar-block.phtml"); ?>
    <?php echo $this->partial("layout-default/sidebar/chat-block.phtml"); ?>
    <?php echo $this->partial("layout-default/sidebar/servers-block.phtml"); ?>
    <?php echo $this->partial("layout-default/sidebar/online-users-block.phtml"); ?>
    <?php echo $this->partial("layout-default/sidebar/donate-block.phtml"); ?>
    <?php //echo $this->partial("layout-default/sidebar/user-map-block.phtml"); ?>
    <?php //echo $this->partial("layout-default/sidebar/online-radio-block.phtml"); ?>
</div>