<div class="row">
	<?php
	echo $this->partial("layout-default/sidebar/calendar_block.phtml");
	?>
	<?php
		echo $this->partial("layout-default/sidebar/chat_block.phtml");
	?>
	<?php
	echo $this->partial("layout-default/sidebar/online_users_block.phtml");
	?>
	<?php
	echo $this->partial("layout-default/sidebar/donate_block.phtml");
	?>
	<?php
		echo $this->partial("layout-default/sidebar/user_map_block.phtml");
	?>
	<?php
		echo $this->partial("layout-default/sidebar/online_radio_block.phtml");
	?>
</div>