<div id="slider_block" class="block m-t-10">
	<div id="carousel-main" class="carousel slide">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-main" data-slide-to="0" class="active"></li>
		</ol>
		<!-- Wrapper for slides -->
		<div class="carousel-inner">
			<div class="item active">
				<img src="/data-content/data-slider/online_racing.png" class="img-responsive" alt="Online-Racing.Net - SIM-Racing Portal">
				<div class="carousel-caption">
					<h4>Online-Racing.Net | Sim-Racing Portal</h4>
					<p>Да пребудет с вами скорость. ©</p>
				</div>
			</div>
			<div class="item">
				<div><iframe src="//www.youtube.com/embed/ivXKyX7_8YI" height="480" width="100%" allowfullscreen="" frameborder="0"></iframe></div>
				<div class="carousel-caption">
					<h4>Прямая трансляция DTM</h4>
				</div>
			</div>
		</div>
		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-main" data-slide="prev">
			<span class="icon-prev"></span>
		</a>
		<a class="right carousel-control" href="#carousel-main" data-slide="next">
			<span class="icon-next"></span>
		</a>
	</div>
</div>