<?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'add')) : ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="clearfix m-b-10">
                <?php
                $adminRacingSeriesAddUrl = $this->url(
                    array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'add'), 'default'
                );
                ?>
                <a href="<?php echo $adminRacingSeriesAddUrl; ?>" class="btn btn-success pull-right ">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Добавить гоночную серию'); ?>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->racingSeriesData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="racing-series-id">
                                <span>ID</span>
                            </th>
                            <th class="racing-series-name">
                                <span><?php echo $this->translate('Название'); ?></span>
                            </th>
                            <th class="racing-series-description">
                                <span><?php echo $this->translate('Описание'); ?></span>
                            </th>
                            <th class="racing-series-action">
                                <span><?php echo $this->translate('Действие'); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->racingSeriesData as $racingSeries): ?>
                            <?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'id')) {
                                $adminRacingSeriesIdUrl = $this->url(
                                    array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'id',
                                        'racingSeriesID' => $this->escape($racingSeries['ID'])), 'adminRacingSeriesID'
                                );
                            } else {
                                $adminRacingSeriesIdUrl = '#';
                            }
                            ?>
                            <tr>
                                <td class="racing-series-id">
                                    <span>
                                        <a href="<?php echo $adminRacingSeriesIdUrl; ?>">
                                            <?php echo $this->escape($racingSeries['ID']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="racing-series-name">
                                    <span>
                                        <a href="<?php echo $adminRacingSeriesIdUrl; ?>">
                                            <?php echo $this->escape($racingSeries['Name']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="racing-series-description">
                                    <span>
                                        <?php echo $this->renderContentTypeText($racingSeries['Description'], 'full_html'); ?>
                                    </span>
                                </td>
                                <td class="racing-series-action">
                                    <span>
                                        <?php
                                        echo $this->BlockConfigMenu($this->translate("Гоночная серия"), false)->racingSeriesMenu(
                                            $this->escape($racingSeries['ID']), true
                                        );
                                        ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="pull-right">
                        <?php echo $this->paginationControl(
                            $this->racingSeriesData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>