<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/racing-series/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'add')) : ?>
                    <?php
                    $adminRacingSeriesAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminRacingSeriesAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить гоночную серию'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="racing-series-id">
                        <span>ID</span>
                    </th>
                    <th class="racing-series-name">
                        <span><?= $this->t('Название'); ?></span>
                    </th>
                    <th class="racing-series-description">
                        <span><?= $this->t('Описание'); ?></span>
                    </th>
                    <th class="racing-series-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->racingSeriesData) : ?>
                    <?php foreach ($this->racingSeriesData as $racingSeries): ?>
                        <?php
                        // check access and generate link for admin/racing-series/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'id')) {
                            $adminRacingSeriesIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'id',
                                    'racingSeriesID' => $this->escape($racingSeries['ID'])), 'adminRacingSeriesID'
                            );
                        } else {
                            $adminRacingSeriesIdUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="racing-series-id">
                                <span>
                                    <a href="<?= $adminRacingSeriesIdUrl; ?>">
                                        <?= $this->escape($racingSeries['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="racing-series-name">
                                <span>
                                    <a href="<?= $adminRacingSeriesIdUrl; ?>">
                                        <?= $this->escape($racingSeries['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="racing-series-description">
                                <span>
                                    <?= $this->renderContentTypeText($racingSeries['Description'], 'full_html'); ?>
                                </span>
                            </td>
                            <td class="racing-series-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Гоночная серия"), false)
                                        ->racingSeriesMenu($this->escape($racingSeries['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->racingSeriesData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->racingSeriesData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
