<?php if ($this->racingSeriesData) { ?>
    <div class="m-b-10">
        <?= $this->racingSeriesDeleteForm; ?>
        <hr/>
    </div>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->racingSeriesData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->RenderContentTypeText($this->racingSeriesData['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->translate('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->translate('Гоночная серия'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->translate('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->racingSeriesData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->racingSeriesData['DateCreate']) != $this->escape($this->racingSeriesData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->translate('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->racingSeriesData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>