<p id="back-top">
    <a href="#top"><span></span><?php echo $this->translate('На подиум!') ?></a>
</p>
<script type="text/javascript">
    $(document).ready(function(){
        jQuery(function($){
            // back to top button plugin
            $(function() {
                $(function () {
                    if ($(this).scrollTop() > 100) {
                        $('#back-top').fadeIn();
                    } else {
                        $('#back-top').fadeOut();
                    }
                });

                $(function () {
                    $(window).scroll(function () {
                        if ($(this).scrollTop() > 100) {
                            $('#back-top').fadeIn();
                        } else {
                            $('#back-top').fadeOut();
                        }
                    });

                    $('#back-top a').click(function () {
                        $('body,html').animate({
                            scrollTop: 0
                        }, 300);
                        return false;
                    });
                    $('#back-top a').mouseover(function(){
                        $('#back-top a').animate({
                            opacity:'1.0'
                        },600);
                    });
                    $('#back-top a').mouseout(function(){
                        $('#back-top a').animate({
                            opacity:'0.5'
                        },300);
                    });
                });
            });
        });
    });
</script>