<!--<div id="list_vertical_tabs">
    <ul class="list_vertical_tabs">
        <li class="list_vertical_item">
            <div class="list_vertical_item_wraper">
                <div class="list_vertical_item_image">
                    <img src="<?php echo $this->baseUrl('img/soc_net/vk.gif'); ?>" />
                </div>
                <div class="list_vertical_item_content">
                    ВК
                </div>
            </div>
        </li>
        <li class="list_vertical_item">
            <div class="list_vertical_item_wraper">
                <div class="list_vertical_item_image">
                    <img src="<?php echo $this->baseUrl('img/soc_net/fb.gif'); ?>" />
                </div>
                <div class="list_vertical_item_content">
                    ФБ
                </div>
            </div>
        </li>
    </ul>
</div>-->
<!-- Version 2 -->

<ul id="list_sliding_tabs">
    <li class="sliding_tab_item liveracers">
        <div class="list_vertical_item_wraper">
            <div class="sliding_tab_item_header">
                <img src="<?php echo $this->baseUrl('img/data/logos/brands/life_racers_50.png'); ?>" />
            </div>
            <div class="sliding_tab_item_content sliding_tab_item_content_hidde1n">
                <h4>Live-Racers</h4>
                <div class="div_hr"></div>
                <p>
                    <a target="_blank" href="http://online-racing-net.liveracers.info/Live">Live</a>
                </p>
                <div id="lr-servers" theme="dark"></div>
                <script type="text/javascript">
                    window._lr = {
                        domainKey: 'b999888a-6e33-4659-8d5b-d5602eadfd36',
                        url: 'http://liveracers.info'
                    };
                    (function() {
                        var lr = document.createElement('script');
                        lr.type = 'text/javascript';
                        lr.async = true;
                        lr.src = window._lr.url + '/Scripts/api.js';
                        var s = document.getElementsByTagName('script')[0];
                        s.parentNode.insertBefore(lr, s);
                    })();
                </script>
            </div>
        </div>
    </li>
</ul>

<div id="slide_out_tab_contact" class="slide_out_tab">
    <a class="handle" href="http://likiliks.ru/js/">Contact</a>
    <h4>Помощь и контакты</h4>
    <p>
        При возникших вопросах обращайтесь по следущим контактам:<br/><br/>
        <img src="<?php echo $this->baseUrl('img/logo/skype_20.png'); ?>">Skype: dark_diesel
        <br/><br/>
        Или пишите в чат сайта.
    </p>
</div>