<div id="league_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->escape($this->league->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="league_item">
                <?php
                if ($this->league->logo != '') {
                    ?>
                    <img class="img-polaroid league_logo" src="<?php echo $this->escape($this->league->logo); ?>">
                <?php } ?>
                <div class="league_descr"><?php echo $this->escape($this->league->description); ?></div>
                <div class="league_controls">
                    <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        $mapper = new Application_Model_UserMapper();
                        $role_id = $mapper->getUserRole(Zend_Auth::getInstance()->getStorage('online-racing')->read()->id);
                        if ($role_id == 1) {
                            ?>
                            <a href = "<?php echo $this->baseUrl('league/edit/' . $this->escape($this->league->id)) ?>" class = "btn btn-small btn-inverse league_edit"><?php echo $this->translate('Редактировать') ?></a>
                            <?php
                        }
                    }
                    ?>
                </div>
                <div class="league_info">
                    <div class="league_date league_info_item"><span><?php echo $this->translate('Создана') ?>: </span><?php echo $this->escape($this->league->date); ?></div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>