<div id="league_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->escape($this->league->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="league_item article_item">
                <?php
                if ($this->league->logo != '') {
                    ?>
                    <img class="img-polaroid league_logo article_center_image" src="<?php echo $this->escape($this->league->logo); ?>">
                <?php } ?>
                <div class="article_text league_descr">
                    <?php
                    $bbcode = Zend_Markup::factory('Bbcode');
                    echo $bbcode->render((string) ($this->escape($this->league->description)));
                    ?>
                </div>
                <?php
                $add_access = $this->checkUserAccess('championship/add');
                $edit_access = $this->checkUserAccess('league/edit');
                $delete_access = $this->checkUserAccess('league/delete');

                if ($add_access || $edit_access || $delete_access) {
                    ?>
                    <div class="article_controls">
                        <?php if ($add_access) { ?>
                            <a href = "<?php echo $this->baseUrl('championship/add') ?>" class = "btn btn-small btn-inverse league_edit article_edit"><?php echo $this->translate('Добавить чемпионат') ?></a>
                        <?php } ?>
                        <?php if ($edit_access) { ?>
                            <a href = "<?php echo $this->baseUrl('league/edit/' . $this->escape($this->league->id)) ?>" class = "btn btn-small btn-inverse league_edit article_edit"><?php echo $this->translate('Редактировать') ?></a>
                        <?php } ?>
                        <?php if ($delete_access) { ?>
                            <a href = "<?php echo $this->baseUrl('league/delete/' . $this->escape($this->league->id)) ?>" class = "btn btn-small btn-inverse league_edit article_edit"><?php echo $this->translate('Удалить') ?></a>
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="league_info article_info">
                    <div class="league_admin league_info_item article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Администратор лиги') ?>: </span>
                        <a href="<?php echo $this->baseUrl('user/id/' . $this->escape($this->league->user_id)) ?>"><?php echo $this->escape($this->league->user_login); ?></a>
                    </div>
                    <div class="league_date league_info_item article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Создана') ?>: </span>
                        <?php echo $this->escape($this->league->date_create); ?>
                    </div>
                </div>
            </div>
            <!-- Championship start -->
            <center><div class="page_title"><?php echo $this->translate('Чемпионаты лиги') ?></div></center>
            <?php
            if (count($this->paginator)) {
                $bbcode = Zend_Markup::factory('Bbcode');
                ?>

                <?php foreach ($this->paginator as $championship): ?>
                    <div class="article_item">
                        <div class="article_title"><a href="<?php echo $this->baseUrl('championship/id/' . $this->escape($championship['id'])) ?>"><?php echo $this->escape($championship['name']); ?></a></div>
                        <?php if ($this->escape($championship['url_logo']) != '') { ?>
                            <img class="img-polaroid article_image" src="<?php echo $this->escape($championship['url_logo']); ?>">
                        <?php } ?>
                        <div class="article_text">
                            <?php
                            if ($championship['description'] != NULL) {
                                echo $bbcode->render((string) ($this->truncate($this->escape($championship['description']))->toLength(250)));
                            } else {
                                echo $this->translate('Нет описания');
                            }
                            ?>
                        </div>
                        <div class="article_controls">
                            <a href = "<?php echo $this->baseUrl('championship/id/' . $this->escape($championship['id'])) ?>" class = "btn btn-small btn-success article_more" title="<?php echo $this->translate('Личный зачет') ?>"><?php echo $this->translate('ЛЗ') ?></a>
                            <a href = "<?php echo $this->baseUrl('championship/id/' . $this->escape($championship['id'])) ?>" class = "btn btn-small btn-warning article_more" title="<?php echo $this->translate('Кубок конструкторов') ?>"><?php echo $this->translate('КК') ?></a>
                            <a href = "<?php echo $this->baseUrl('championship/id/' . $this->escape($championship['id'])) ?>" class = "btn btn-small btn-info article_more" title="<?php echo $this->translate('Составы команд') ?>"><?php echo $this->translate('Составы') ?></a>
                            <a href = "<?php echo $this->baseUrl('article/id/' . $this->escape($championship['article_id'])) ?>" class = "btn btn-small btn-danger article_more" title="<?php echo $this->translate('Регламент чемпионата') ?>"><?php echo $this->translate('Регламент') ?></a>
                            <a href = "<?php echo $this->baseUrl('championship/id/' . $this->escape($championship['id'])) ?>" class = "btn btn-small btn-inverse article_more" title="<?php echo $this->translate('Детальная информация о чемпионате') ?>"><?php echo $this->translate('Подробнее...') ?></a>
                        </div>
                        <div class="article_info">
                            <div class="championship_author article_info_item"><span class="bold_text"><?php echo $this->translate('Администратор чемпионата') ?>: </span><a href="<?php echo $this->baseUrl('user/id/' . $this->escape($championship['user_id'])) ?>"><?php echo $this->escape($championship['user_login']); ?></a></div>
                            <div class="championshipe_date_create article_info_item"><span class="bold_text"><?php echo $this->translate('Создан') ?>: </span><?php echo $this->escape($championship['date_create']); ?></div>
                        </div>
                    </div>
                    <div class="div_hr"></div>
                    <?php
                endforeach;
                echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/full_views_pagination_control.phtml');
            } else {
                ?>
                <div class="alert alert-error alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                    <?php echo $this->translate('Контент на сайте не найден!'); ?>
                </div>
            <?php } ?>
            <!-- Championship end -->
        <?php } ?>
    </div>
</div>