<div class="navbar-fixed-top" role="navigation">
    <div class="navbar-inverse">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#admin-main-menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php
            $admin_index_url = $this->url(array('module' => 'admin','controller' => 'index', 'action' => 'index'), 'default', true);
            ?>
            <a href="<?= $admin_index_url; ?>" class="pull-left">
                <img src="<?= $this->baseUrl('data-content/ui/logo.png'); ?>" class="img-responsive"/>
            </a>
        </div>
        <div id="admin-main-menu" class="collapse navbar-collapse">
            <!-- User Navigation menu  -->
            <?= $this->render("common/user-nav-menu.phtml") ?>
            <!-- /User Navigation menu  -->
            <?php
            $default_index_url = $this->url(
                array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true
            );
            ?>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="<?= $default_index_url;?>">
                        <i class="fa fa-globe"></i> <?= $this->translate('Сайт'); ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>