<div class="social-networks-list center-block text-center clearfix">
    <ul class="list-inline">
        <li>
            <a href="http://vk.com/OnlineRacingNet" target="_blank">
                <img src="<?= $this->baseUrl('img/soc_net/vk.gif'); ?>"/>
            </a>
        </li>
        <li>
            <a href="http://www.facebook.com/OnlineRacingNet" target="_blank">
                <img src="<?= $this->baseUrl('img/soc_net/fb.gif'); ?>"/>
            </a>
        </li>
        <li>
            <a href="http://twitter.com/OnlineRacingnet" target="_blank">
                <img src="<?= $this->baseUrl('img/soc_net/tw.gif'); ?>"/>
            </a>
        </li>
        <li>
            <a href="http://www.youtube.com/user/OnlineRacingNet" target="_blank">
                <img src="<?= $this->baseUrl('img/soc_net/yt.gif'); ?>"/>
            </a>
        </li>
    </ul>
</div>