<div class="web_counters">
    <!-- Yandex CY -->
    <div id="yandex-cy" class="pull-left m-r-5">
        <a href="http://yandex.ru/cy?base=0&amp;host=online-racing.net"><img
                src="http://www.yandex.ru/cycounter?online-racing.net" width="88" height="31" alt="Яндекс цитирования"
                border="0"/></a>
    </div>
    <!-- /Yandex CY -->

    <!-- LiveInternet Counter -->
    <div id="liveinternet-counter" class="pull-left m-r-5">
        <script type="text/javascript"><!--
            document.write("<a href='http://www.liveinternet.ru/click' " +
                "target=_blank><img src='//counter.yadro.ru/hit?t21.5;r" +
                escape(document.referrer) + ((typeof(screen) == "undefined") ? "" :
                ";s" + screen.width + "*" + screen.height + "*" + (screen.colorDepth ?
                    screen.colorDepth : screen.pixelDepth)) + ";u" + escape(document.URL) +
                ";" + Math.random() +
                "' alt='' title='LiveInternet: показано число просмотров за 24" +
                " часа, посетителей за 24 часа и за сегодня' " +
                "border='0' width='88' height='31'><\/a>")
            //--></script>
    </div>
    <!-- /LiveInternet Counter -->

    <!-- Rambler100 Counter -->
    <div id="rambler100-counter" class="pull-left m-r-5">
        <script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2784771"></script>
        <noscript>
            <a href="http://top100.rambler.ru/navi/2784771/">
                <img src="http://counter.rambler.ru/top100.cnt?2784771" alt="Rambler's Top100" border="0"/>
            </a>
        </noscript>
    </div>
    <!-- /Rambler100 Counter -->

    <!-- Rating@Mail.ru Counter -->
    <div id="mailru-counter" class="pull-left m-r-5">
        <script type="text/javascript">//<![CDATA[
            var a = '', js = 10;
            try {
                a += ';r=' + escape(document.referrer);
            } catch (e) {
            }
            try {
                a += ';j=' + navigator.javaEnabled();
                js = 11;
            } catch (e) {
            }
            try {
                s = screen;
                a += ';s=' + s.width + '*' + s.height;
                a += ';d=' + (s.colorDepth ? s.colorDepth : s.pixelDepth);
                js = 12;
            } catch (e) {
            }
            try {
                if (typeof((new Array).push('t')) === "number")js = 13;
            } catch (e) {
            }
            try {
                document.write('<a href="http://top.mail.ru/jump?from=2258389">' +
                    '<img src="http://d5.c7.b2.a2.top.mail.ru/counter?id=2258389;t=48;js=' + js + a + ';rand=' + Math.random() +
                    '" alt="Рейтинг@Mail.ru" style="border:0;" height="31" width="88" \/><\/a>');
            } catch (e) {
            }//]]></script>
        <noscript><p><a href="http://top.mail.ru/jump?from=2258389">
                    <img src="http://d5.c7.b2.a2.top.mail.ru/counter?js=na;id=2258389;t=48"
                         style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru"/></a></p></noscript>
    </div>
    <!-- /Rating@Mail.ru counter -->

    <!-- Whois Amung.us-->
    <div class="pull-left m-r-5">
        <script id="_wauxg2">var _wau = _wau || []; _wau.push(["classic", "ptw4ufs3cxvx", "xg2"]);
            (function() {var s=document.createElement("script"); s.async=true;
                s.src="http://widgets.amung.us/classic.js";
                document.getElementsByTagName("head")[0].appendChild(s);
            })();</script>
    </div>
    <!-- /Whois Amung.us-->

    <!-- Yandex.Metrika counter -->
    <div id="yandex-metrika-counter" class="pull-left m-r-5">
        <!-- Yandex.Metrika informer -->
        <a href="http://metrika.yandex.ru/stat/?id=17466829&amp;from=informer"
           target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/17466829/3_0_FFFFFFFF_EFEFEFFF_0_pageviews"
                                               style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика"
                                               title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"/></a>
        <!-- /Yandex.Metrika informer -->

        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter17466829 = new Ya.Metrika({id: 17466829, enableAll: true});
                    } catch (e) {
                    }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () {
                        n.parentNode.insertBefore(s, n);
                    };
                s.type = "text/javascript";
                s.async = true;
                s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f);
                } else {
                    f();
                }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript>
            <div><img src="//mc.yandex.ru/watch/17466829" style="position:absolute; left:-9999px;" alt=""/></div>
        </noscript>
    </div>
    <!-- /Yandex.Metrika counter -->
</div>