<?php if ($this->postTypeData) { ?>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="clearfix m-b-10">
                <?php
                $adminPostTypeAddUrl = $this->url(
                    array('module' => 'admin', 'controller' => 'post-type', 'action' => 'add'), 'default'
                );
                ?>
                <a href="<?php echo $adminPostTypeAddUrl; ?>" class="btn btn-success pull-right ">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Добавить тип статьи'); ?>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="content-type-id">
                                <span>ID</span>
                            </th>
                            <th class="content-type-name">
                                <span><?php echo $this->translate('Название'); ?></span>
                            </th>
                            <th class="content-type-description">
                                <span><?php echo $this->translate('Описание'); ?></span>
                            </th>
                            <th class="content-type-action">
                                <span><?php echo $this->translate('Действие'); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->postTypeData as $postType): ?>
                            <?php
                            $adminPostTypeIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'post-type', 'action' => 'id',
                                    'postTypeID' => $this->escape($postType['ID'])), 'adminPostTypeID'
                            );
                            $adminPostTypeEditUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'post-type', 'action' => 'edit',
                                    'postTypeID' => $this->escape($postType['ID'])), 'adminPostTypeAction'
                            );
                            $adminPostTypeDeleteUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'post-type', 'action' => 'delete',
                                    'postTypeID' => $this->escape($postType['ID'])), 'adminPostTypeAction'
                            );
                            ?>
                            <tr>
                                <td class="content-type-id">
										<span>
                                            <a href="<?php echo $adminPostTypeIdUrl; ?>">
                                                <?php echo $this->escape($postType['ID']) ?>
                                            </a>
                                        </span>
                                </td>
                                <td class="content-type-name">
										<span>
                                            <a href="<?php echo $adminPostTypeIdUrl; ?>">
                                                <?php echo $this->escape($postType['Name']) ?>
                                            </a>
                                        </span>
                                </td>
                                <td class="content-type-description">
                                    <span>
                                        <?php echo $this->RenderContentTypeText($postType['Description'], 'full_html'); ?>
                                    </span>
                                </td>
                                <td class="content-type-action">
										<span>
											<div class="pull-right action-buttons">
                                                <div class="btn-group pull-right">
                                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle"
                                                            data-toggle="dropdown">
                                                        <span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
                                                    </button>
                                                    <ul class="dropdown-menu slidedown">
                                                        <li>
                                                            <a href="<?php echo $adminPostTypeIdUrl ?>">
                                                                <i class="fa fa-eye"></i> <?php echo $this->translate(
                                                                    'Просмотреть'
                                                                ); ?>
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="<?php echo $adminPostTypeEditUrl ?>">
                                                                <i class="fa fa-pencil"></i> <?php echo $this->translate(
                                                                    'Редактировать'
                                                                ); ?>
                                                            </a>
                                                        </li>
                                                        <li>
                                                            <a href="<?php echo $adminPostTypeDeleteUrl ?>">
                                                                <i class="fa fa-trash-o"></i> <?php echo $this->translate(
                                                                    'Удалить'
                                                                ); ?>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
										</span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="pull-right">
                        <?php echo $this->paginationControl(
                            $this->postTypeData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>