<?php if ($this->paginator) { ?>
		<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="clearfix m-b-10">
				<?php
				$post_type_id_url = $this->url(array('module' => 'admin', 'controller' => 'post-type', 'action' => 'add'), 'default', true);
				?>
				<a href="<?php echo $post_type_id_url; ?>" class="btn btn-success btn-xs pull-right "><i class="fa fa-plus"></i> <?php echo $this->translate('Добавить Тип поста'); ?></a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<i class="fa fa-list"></i>
				</div>
				<div class="panel-body">
					<table class="table table-striped custab">
						<thead>
							<tr>
								<th class="post_type_id"><span>ID</span></th>
								<th class="post_type_name"><span><?php echo $this->translate('Название'); ?></span></th>
								<th class="post_type_descr"><span><?php echo $this->translate('Описание'); ?></span></th>
								<th class="post_type_action"><span><?php echo $this->translate('Действие'); ?></span></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->paginator as $post_type): ?>
								<?php
								$post_type_id_url = $this->url(array('module' => 'admin', 'controller' => 'post-type', 'action' => 'id', 'post_type_id' => $this->escape($post_type->id)), 'post_type_id', true);
								$post_type_edit_url = $this->url(array('module' => 'admin', 'controller' => 'post-type', 'action' => 'edit', 'post_type_id' => $this->escape($post_type->id)), 'post_type_action', true);
								$post_type_delete_url = $this->url(array('module' => 'admin', 'controller' => 'post-type', 'action' => 'delete', 'post_type_id' => $this->escape($post_type->id)), 'post_type_action', true);
								?>
								<tr>
									<td class="post_type_id"><span><a href="<?php echo $this->url(array('controller' => 'post-type', 'action' => 'id', 'post_type_id' => $post_type['id']), 'post_type_id', true) ?>"><?php echo $this->escape($post_type['id']) ?></a></span></td>
									<td class="post_type_name"><span><a href="<?php echo $this->url(array('controller' => 'post-type', 'action' => 'id', 'post_type_id' => $post_type['id']), 'post_type_id', true) ?>"><?php echo $this->escape($post_type['name']) ?></a></span></td>
									<td class="post_type_descr"><span><?php echo $this->truncate($this->escape($post_type['description']))->toLength(200); ?></span></td>
									<td class="post_type_action">
										<span>
											<div class="pull-right action-buttons">
												<div class="btn-group pull-right">
													<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
														<span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
													</button>
													<ul class="dropdown-menu slidedown">
														<li><a href="<?php echo $post_type_id_url ?>"><i class="fa fa-eye"></i> <?php echo $this->translate('Просмотреть'); ?></a></li>
														<li><a href="<?php echo $post_type_edit_url ?>"><i class="fa fa-pencil"></i> <?php echo $this->translate('Редактировать'); ?></a></li>
														<li><a href="<?php echo $post_type_delete_url ?>"><i class="fa fa-trash-o"></i> <?php echo $this->translate('Удалить'); ?></a></li>
													</ul>
												</div>
											</div>
										</span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="pull-right">
						<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>