<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="clearfix m-b-10">
			<?php
			$resource_id_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'add'), 'default', true);
			?>
			<a href="<?= $resource_id_url; ?>" class="btn btn-success pull-right "><i class="fa fa-plus"></i> <?= $this->t('Добавить ресурс'); ?></a>
		</div>
	</div>
</div>
<?php if ($this->paginator) { ?>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<i class="fa fa-list"></i>
				</div>
				<div class="panel-body">
					<table class="table table-striped custab">
						<thead>
							<tr>
								<th class="resource_id"><span>ID</span></th>
								<th class="resource_name"><span><?= $this->t('Название'); ?></span></th>
								<th class="resource_module"><span><?= $this->t('Модуль'); ?></span></th>
								<th class="resource_controller"><span><?= $this->t('Контроллер'); ?></span></th>
								<th class="resource_descr"><span><?= $this->t('Описание'); ?></span></th>
								<th class="resource_action"><span><?= $this->t('Действие'); ?></span></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->paginator as $resource): ?>
								<?php
								$resource_id_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'id', 'resource_id' => $this->escape($resource->id)), 'adminResourceId', true);
								$resource_edit_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'edit', 'resource_id' => $this->escape($resource->id)), 'adminResourceAction', true);
								$resource_delete_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'delete', 'resource_id' => $this->escape($resource->id)), 'adminResourceAction', true);
								$resource_add_resource_access_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'add-resource-access', 'resource_id' => $this->escape($resource->id)), 'adminResourceAction', true);
								$resource_add_privilege_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'add-privilege', 'resource_id' => $this->escape($resource->id)), 'adminResourceAction', true);
								?>
								<tr>
									<td class="resource_id"><span><a href="<?= $resource_id_url; ?>"><?= $this->escape($resource['id']) ?></a></span></td>
									<td class="resource_name"><span><a href="<?= $resource_id_url ?>"><?= $this->escape($resource['name']) ?></a></span></td>
									<td class="resource_module"><span><?= $this->escape($resource['module']) ?></span></td>
									<td class="resource_controller"><span><?= $this->escape($resource['controller']) ?></span></td>
									<td class="resource_descr"><span><?= $this->truncate($this->escape($resource['description']))->toLength(200); ?></span></td>
									<td class="resource_action">
										<span>
											<div class="pull-right action-buttons">
												<div class="btn-group pull-right">
													<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
														<span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
													</button>
													<ul class="dropdown-menu slidedown">
														<li><a href="<?= $resource_id_url ?>"><i class="fa fa-eye"></i> <?= $this->t('Просмотреть'); ?></a></li>
														<li><a href="<?= $resource_edit_url ?>"><i class="fa fa-pencil"></i> <?= $this->t('Редактировать'); ?></a></li>
														<li><a href="<?= $resource_delete_url ?>"><i class="fa fa-trash-o"></i> <?= $this->t('Удалить'); ?></a></li>
														<li class="divider"></li>
														<li><a href="<?= $resource_add_resource_access_url ?>"><i class="fa fa-wrench"></i> <?= $this->t('Настроить доступ'); ?></a></li>
														<li><a href="<?= $resource_add_privilege_url ?>"><i class="fa fa-plus"></i> <?= $this->t('Добавить привилегию'); ?></a></li>
													</ul>
												</div>
											</div>
										</span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="pull-right">
						<?= $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>