<?php
if ($this->paginator) {
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
    ?>
    <table class="table table-bordered table-hover table-striped articles_table">
        <thead>
    	<tr>
    	    <th class="resource_id"><span>#</span></th>
    	    <th class="resource_name"><span><?php echo $this->translate('Название'); ?></span></th>
    	    <th class="resource_controller"><span><?php echo $this->translate('Контроллер'); ?></span></th>
    	    <th class="resource_action"><span><?php echo $this->translate('Действие'); ?></span></th>
    	    <th class="resource_descr"><span><?php echo $this->translate('Описание'); ?></span></th>
    	    <th class="resource_action articles_table_action"><span><?php echo $this->translate('Действие'); ?></span></th>
    	</tr>
        </thead>
        <tbody>
	    <?php foreach ($this->paginator as $resource): ?>
		<tr>
		    <td class="resource_id"><span><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'id', 'resource_id' => $resource['id']), 'resource_id', true) ?>"><?php echo $this->escape($resource['id']) ?></a></span></td>
		    <td class="resource_name"><span><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'id', 'resource_id' => $resource['id']), 'resource_id', true) ?>"><?php echo $this->escape($resource['name']) ?></a></span></td>
		    <td class="resource_controller"><span><?php echo $this->escape($resource['controller']) ?></span></td>
		    <td class="resource_action"><span><?php echo $this->escape($resource['action']) ?></span></td>
		    <td class="resource_descr"><span><?php echo $this->truncate($this->escape($resource['description']))->toLength(200); ?></span></td>
		    <td class="resource_action articles_table_action">
			<span>
			    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'id', 'resource_id' => $resource['id']), 'resource_id', true) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a><br/>
			    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'edit', 'resource_id' => $resource['id']), 'resource_actions', true) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
			    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'delete', 'resource_id' => $resource['id']), 'resource_actions', true) ?>"><i class="icon-remove"></i> <?php echo $this->translate('Удал.'); ?></a><br/>
			</span>
		    </td>
		</tr>
	    <?php endforeach; ?>
        </tbody>
    </table>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
}
?>