<?php if ($this->resource) { ?>
	<div class="block">
		<?php
		foreach ($this->resource as $resource_field):
			echo $resource_field . "<br/>";
		endforeach;
		?>
	</div>
<?php } ?>

<?php if ($this->privileges_data) : ?>
	<h3><?php echo $this->translate('Привилегии ресурсов'); ?></h3>
	<?php foreach ($this->privileges_data as $privilege): ?>
		<div class="block">
			<?php foreach ($privilege as $field): ?>
				<?php echo $field . "<br/>"; ?>
			<?php endforeach; ?>
		</div>
	<?php endforeach; ?>
<?php endif; ?>
