<?php if ($this->paginator) { ?>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="clearfix m-b-10">
				<?php
				$user_id_url = $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'add'), 'default', true);
				?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<i class="fa fa-list"></i>
				</div>
				<div class="panel-body">
					<table class="table table-striped custab">
						<thead>
							<tr>
								<th class="resource_id"><span>ID</span></th>
								<th class="user_login"><span><?= $this->t('Логин'); ?></span></th>
								<th class="user_name"><span><?= $this->t('Имя'); ?></span></th>
								<th class="user_surname"><span><?= $this->t('Фамилия'); ?></span></th>
								<th class="user_last_login_ip"><span><?= $this->t('Последний IP'); ?></span></th>
								<th class="user_role"><span><?= $this->t('Роль'); ?></span></th>
								<th class="user_about"><span><?= $this->t('О себе'); ?></span></th>
								<th class="user_action"><span><?= $this->t('Действие'); ?></span></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->paginator as $user): ?>
								<?php
								$user_id_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'id', 'user_id' => $this->escape($user->id)), 'user_id', true);
								$user_edit_url = $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'user_id' => $this->escape($user->id)), 'user_action', true);
								$user_delete_url = $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'delete', 'user_id' => $this->escape($user->id)), 'user_action', true);
								$user_role_id_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'id', 'role_id' => $user['user_role_id']), 'adminRoleID', true);
								?>
								<tr>
									<td class="user_id"><span><a href="<?= $user_id_url ?>"><?= $this->escape($user['id']) ?></a></span></td>
									<td class="user_login"><span><a href="<?= $user_id_url ?>"><?= $this->escape($user['login']) ?></a></span></td>
									<td class="user_name"><span><?= $this->escape($user['name']) ?></span></td>
									<td class="user_surname"><span><?= $this->escape($user['surname']) ?></span></td>
									<td class="user_last_login_ip"><span><?= $this->escape($user['last_login_ip']) ?></span></td>
									<td class="user_role"><span><a href="<?= $user_role_id_url; ?>"><?= $this->escape($user['user_role_name']) ?></a></span></td>
									<td class="user_about"><span><?= $this->truncate($this->escape($user['about']))->toLength(200); ?></span></td>
									<td class="user_action">
										<span>
											<div class="pull-right action-buttons">
												<div class="btn-group pull-right">
													<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
														<span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
													</button>
													<ul class="dropdown-menu slidedown">
														<li><a href="<?= $user_id_url ?>"><i class="fa fa-eye"></i> <?= $this->t('Просмотреть'); ?></a></li>
														<li><a href="<?= $user_edit_url ?>"><i class="fa fa-pencil"></i> <?= $this->t('Редактировать'); ?></a></li>
														<li><a href="<?= $user_delete_url ?>"><i class="fa fa-trash-o"></i> <?= $this->t('Удалить'); ?></a></li>
													</ul>
												</div>
											</div>
										</span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="pull-right">
						<?= $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>