<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="block">
			<div class="block-body">
				<div class="row">
					<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
						<div class="panel panel-danger">
							<div class="panel-heading">
								<div class="panel-title">
									<i class="fa fa-exclamation-circle"></i> <?php echo $this->translate('Безопасность'); ?>
								</div>
							</div>
							<div class="panel-body">
								<?php
								$resources_all_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'all'), 'adminResourceAll', true);
								$privilege_all_url = $this->url(array('module' => 'admin', 'controller' => 'prvilege', 'action' => 'all'), 'adminPrivilegeAll', true);
								$resource_access_all_url = $this->url(array('module' => 'admin', 'controller' => 'resource-access', 'action' => 'all'), 'adminResourceAccessAll', true);
								$role_all_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'all'), 'adminRoleAll', true);
								?>
								<a href="<?php echo $resources_all_url; ?>" class="btn btn-success btn-lg m-b-5" role="button"><i class="fa fa-sitemap"></i><br/><?php echo $this->translate('Ресурсы'); ?></a>
								<a href="<?php echo $privilege_all_url; ?>" class="btn btn-success btn-lg m-b-5" role="button"><i class="fa fa-sitemap"></i><br/><?php echo $this->translate('Привилегии ресурсов'); ?></a>
								<a href="<?php echo $resource_access_all_url; ?>" class="btn btn-danger btn-lg m-b-5" role="button"><i class="fa fa-sitemap"></i><br/><?php echo $this->translate('Доступ к ресурсам'); ?></a>
								<a href="<?php echo $role_all_url; ?>" class="btn btn-danger btn-lg m-b-5" role="button"><i class="fa fa-sitemap"></i><br/><?php echo $this->translate('Роли пользователей'); ?></a>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
						<div class="panel panel-primary">
							<div class="panel-heading">
								<div class="panel-title">
									<i class="fa fa-users"></i> <?php echo $this->translate('Пользователи'); ?>
								</div>
							</div>
							<div class="panel-body">
								<?php
								$user_all_url = $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'all', 'page' => 1), 'adminUserAll', true);
								?>
								<a href="<?php echo $user_all_url; ?>" class="btn btn-primary btn-lg m-b-5" role="button"><i class="fa fa-user"></i><br/><?php echo $this->translate('Пользователи'); ?></a>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
						<div class="panel panel-primary">
							<div class="panel-heading">
								<div class="panel-title">
									<i class="fa fa-align-justify"></i> <?php echo $this->translate('Контент сайта'); ?>
								</div>
							</div>
							<div class="panel-body">
							</div>
						</div>
					</div>
				</div>
				<a href="<?php echo $this->baseUrl(); ?>" class="btn btn-inverse btn-lg btn-block" role="button"><i class="fa fa-globe"></i> <?php echo $this->translate('Перейти на сайт'); ?></a>
			</div>
		</div>
	</div>
</div>