<div>
    <h2>Контент</h2>

    <strong>Действия:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('post/all') ?>">Просмотреть на сайте</a></li>
        <li><a href="<?php echo $this->baseUrl('post/add') ?>">Создать</a></li>
    </ul>

    <strong>Игры и моды:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('game/all') ?>">Просмотреть игры (Мод)</a></li>
        <li><a href="<?php echo $this->baseUrl('game/add') ?>">Добавить игру (Мод)</a></li>
    </ul>
</div>
<div>
    <h2>Управление соревнованиями</h2>

    <strong>Лиги:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('league/all') ?>">Просмотреть на сайте</a></li>
        <li><a href="<?php echo $this->baseUrl('league/add') ?>">Создать</a></li>
    </ul>

    <strong>Соревнования:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('championship/all') ?>">Просмотреть все</a></li>
        <li><a href="<?php echo $this->baseUrl('championship/add') ?>">Создать</a></li>
    </ul>

    <strong>Трассы:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('admin/users') ?>">Просмотреть все</a></li>
        <li><a href="<?php echo $this->baseUrl('user/all') ?>">Добавить трассу</a></li>
    </ul>

    <strong>Гонки и результаты:</strong>
    <ul>
        <li><a href="<?php echo $this->baseUrl('admin/users') ?>">Просмотреть все</a></li>
        <li><a href="<?php echo $this->baseUrl('user/all') ?>">Создать гонку</a></li>
        <li><a href="<?php echo $this->baseUrl('user/all') ?>">Добавить результат</a></li>
    </ul>
</div>