<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-5">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= $this->t('Быстрый доступ к функциям сайта'); ?>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <?php
                        $adminPostAddUrl = $this->url(
                            array('module' => 'admin', 'controller' => 'post', 'action' => 'add'),
                            'default', true
                        );
                        ?>
                        <a class="btn btn-badge btn-default m-all-5" href="<?= $adminPostAddUrl; ?>">
                            <i class="fa fa-file-o fa-2x"></i>
                            <span class="text">
                                <?= $this->t('Добавить контент'); ?>
                            </span>
                            <span class="triangle-button green">
                                <i class="fa fa-plus"></i>
                            </span>
                        </a>
                        <?php
                        $adminChampionshipAddUrl = $this->url(
                            array('module' => 'admin', 'controller' => 'track', 'action' => 'add'),
                            'default', true
                        );
                        ?>
                        <a class="btn btn-badge btn-default m-all-5" href="<?= $adminChampionshipAddUrl; ?>">
                            <i class="fa fa-trophy fa-2x"></i>
                            <span class="text">
                                <?= $this->t('Добавить чемпионат'); ?>
                            </span>
                            <span class="triangle-button green">
                                <i class="fa fa-plus"></i>
                            </span>
                        </a>
                        <?php
                        $adminTrackAddUrl = $this->url(
                            array('module' => 'admin', 'controller' => 'track', 'action' => 'add'),
                            'default', true
                        );
                        ?>
                        <a class="btn btn-badge btn-default m-all-5" href="<?= $adminTrackAddUrl; ?>">
                            <i class="fa fa-flag-checkered fa-2x"></i>
                            <span class="text">
                                <?= $this->t('Добавить трассу'); ?>
                            </span>
                            <span class="triangle-button green">
                                <i class="fa fa-plus"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <?php
                        $adminUserAllUrl = $this->url(
                            array('module' => 'admin', 'controller' => 'user', 'action' => 'all', 'page' => 1),
                            'adminUserAll', true
                        );
                        ?>
                        <a class="btn btn-badge btn-default m-all-5" href="<?= $adminUserAllUrl; ?>">
                            <i class="fa fa-user fa-2x"></i>
                            <span class="text">
                                <?= $this->t('Пользователи'); ?>
                            </span>
                            <span class="triangle-button orange">
                                <i class="fa fa-eye"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <?php
                        $adminResourcesAllUrl = $this->url(
                            array('module' => 'admin', 'controller' => 'resource', 'action' => 'all'),
                            'adminResourceAll', true
                        );
                        ?>
                        <a class="btn btn-badge btn-default m-all-5" href="<?= $adminResourcesAllUrl; ?>">
                            <i class="fa fa-sitemap fa-2x"></i>
                            <span class="text">
                                <?= $this->t('Ресурсы сайта'); ?>
                            </span>
                            <span class="triangle-button red">
                                <i class="fa fa-exclamation-circle"></i>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>