<?php
if (count($this->paginator)) {
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
    ?>
    <div class="row">
	<?php
	$date1 = new Zend_Date();
	foreach ($this->paginator as $user):
	    ?>
	    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
		<div class="user_item block-item block-align-center">
		    <?php
		    $date2 = new Zend_Date($user['date_last_activity']);
		    if (($date1->toValue() - $date2->toValue()) <= 420) {
			?>
	    	    <img src="/img/user_online.png" class="user_light_status img-thumbnail">
		    <?php } else { ?>
	    	    <img src="/img/user_ofline.png" class="user_light_status img-thumbnail">
		    <?php } ?>
		    <div class="user_image">
			<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $user['id']), 'userId', true) ?>"><?php echo $this->setupUserAvatar($user['id'], $user['avatar_type']); ?></a>
		    </div>
		    <div class="user_flag"><img src="<?php echo $user['country_url_image_round']; ?>" title="<?php echo $user['country_name']; ?>"></div>
		    <div class="user_login"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $user['id']), 'userId', true) ?>"><?php echo $user['login']; ?></a></div>
		</div>
	    </div>
	    <?php
	endforeach;
	?>
    </div>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
} else {
    ?>
    <div class="alert alert-error alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4><?php echo $this->translate('Ошибка!'); ?></h4>
	<?php echo $this->translate('Пользователи на сайте не найдены!'); ?>
    </div>
<?php } ?>