<div id="tabs">
    <ul>
        <li><a href="#tabs-1"><?= $this->t('Личное'); ?></a></li>
        <li><a href="#tabs-2"><?= $this->t('Аватар'); ?></a></li>
        <li><a href="#tabs-3"><?= $this->t('Контакты'); ?></a></li>
        <li><a href="#tabs-4"><?= $this->t('Аккаунты'); ?></a></li>
        <li><a href="#tabs-5"><?= $this->t('Дополнительно'); ?></a></li>
    </ul>
    <div id="tabs-1">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-1" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>" enctype="<?= $this->form->getEnctype(); ?>">
			<?= $this->form->getDisplayGroup('personal_Inf'); ?>
			<?= $this->form->tab_name->setvalue('personal_Inf'); ?>
			<?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
        <script>
			$(function() {
				$("#birthday").datepicker({
					showButtonPanel: true,
					dateFormat: "yy-mm-dd",
					showAnim: "clip"
				});
			});
        </script>
    </div>
    <div id="tabs-2">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-2" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>" enctype="<?= $this->form->getEnctype(); ?>">
            <table id="table_avatar_type" class="table table-bordered">
                <tbody>
                    <tr>
                        <td><?= $this->getUserAvatar($this->user_id, 1); ?></td>
                        <td><?= $this->getUserAvatar($this->user_id, 2); ?></td>
                        <td><?= $this->getUserAvatar($this->user_id, 3); ?></td>
                    </tr>
                    <tr>
                        <td><span><?= $this->t('Загруженный'); ?></span><br /></td>
                        <td><span><?= $this->t('Ссылка с другого ресурса'); ?></span></td>
                        <td><span><?= $this->t('Gravatar'); ?></span></td>
                    </tr>
                </tbody>
            </table>
			<?= $this->form->getDisplayGroup('avatar'); ?>
			<?= $this->form->tab_name->setvalue('avatar'); ?>
			<?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
    <div id="tabs-3">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-3" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>" enctype="<?= $this->form->getEnctype(); ?>">
			<?= $this->form->getDisplayGroup('contacts_Inf'); ?>
			<?= $this->form->tab_name->setvalue('contacts_Inf'); ?>
			<?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
    <div id="tabs-4">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-4" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>" enctype="<?= $this->form->getEnctype(); ?>">
			<?= $this->form->getDisplayGroup('social_netwoks'); ?>
			<?= $this->form->tab_name->setvalue('social_netwoks'); ?>
			<?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
    <div id="tabs-5">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-5" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>" enctype="<?= $this->form->getEnctype(); ?>">
			<?= $this->form->getDisplayGroup('additional_Inf'); ?>
			<?= $this->form->tab_name->setvalue('additional_Inf'); ?>
			<?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
</div>
<script type="text/javascript" >
	jQuery(document).ready(function() {
		$('#tabs').tabs();
	});
</script>