<?php if ($this->userData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?php if ($this->getUser()->getUserStatus($this->userData['DateLastActivity']) == USER_STATUS_ONLINE) { ?>
                <?php $userStatusClass = 'user-online'; ?>
                <div class="alert alert-success">
                    <strong><?= $this->t("В паддоке") ?></strong>
                </div>
            <?php } else { ?>
                <?php $userStatusClass = 'user-offline'; ?>
                <div class="alert alert-warning">
                    <strong><?= $this->t("Вне паддока") ?></strong>
                </div>
            <?php } ?>

        </div>
    </div>
<?php } ?>

<?php if ($this->userData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="block block-default m-b-15">
                <div class="block-body">
                    <div class="m-b-15">
                        <div class="user-cover">
                            <img
                                src="<?= $this->baseUrl('/data-content/img/user-cover/user-cover-2.png'); ?>"
                                alt="" class="img-responsive"/>
                        </div>
                        <div class="img-wrapper-120-120 overflow-hide img-circle user-avatar pic <?= $userStatusClass; ?>">
                            <a href="#" data-toggle="modal" data-target=".user-<?= $this->userData['ID']; ?>"
                               title="<?= $this->escape($this->userData['ID']); ?>">
                                <?= $this->getUser()->getUserAvatar($this->userData['ID'], $this->userData['AvatarType'], 'img-responsive img-size-120', 120); ?>
                            </a>
                            <?= $this->modal(array(
                                'title' => $this->userData['NickName'],
                                'class' => 'user-' . $this->userData['ID'],
                                'content' => $this->getUser()->getUserAvatar($this->userData['ID'], $this->userData['AvatarType'], 'img-responsive img-size-640 center-block', 640)
                            )); ?>
                        </div>
                        <div class="user-name">
                            <span class="tooltip-field pull-left m-t-5" data-placement="bottom"
                                  data-title="<?= $this->escape($this->userData['Country']['EnglishName']); ?>">
                                <div class="img-wrapper-50-50">
                                    <img class="img-size-50-50 img-responsive" src="<?= $this->baseUrl(
                                        $this->escape($this->userData['Country']['ImageGlossyWaveUrl'])
                                    ); ?>"
                                         alt="<?= $this->escape($this->userData['Country']['EnglishName']); ?>">
                                </div>
                            </span>
                            <?php if (!empty($this->userData['Name']) && !empty($this->userData['Surname'])) { ?>
                                <small><?= $this->userData['Surname'], ' ', $this->userData['Name'] ?></small>
                            <?php } else { ?>
                                <small>
                                    <БЕЗ ИМЕНИ>
                                </small>
                            <?php } ?>
                            <span class="text-muted small"><small><?= $this->userData['NickName']; ?></small></span>
                        </div>
                        <a href="#" class="btn btn-xs btn-primary pull-right change-user-cover-btn" style="margin:10px;">
                            <i class="fa fa-pencil-square"></i> <?= $this->t('Изменить обложку'); ?>
                        </a>

                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="block block-default">
    <div class="block-body">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active">
            <a href="#info" data-toggle="tab"><i
                    class="fa fa-info-circle"></i> <?= $this->t('Информация'); ?>
            </a>
        </li>
        <li>
            <a href="#site-statistic" data-toggle="tab"><i
                    class="fa fa-bar-chart-o"></i> <?= $this->t('Статистика сайта'); ?>
            </a>
        </li>
        <li>
            <a href="#user-contacts" data-toggle="tab">
                <i class="fa fa-keyboard-o"></i> <?= $this->t('Контакты'); ?>
            </a>
        </li>
        <li>
            <a href="#user-social" data-toggle="tab">
                <i class="fa fa-users"></i> <?= $this->t('Социальные сети'); ?>
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="info">
            <div class="well">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tbody>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Имя') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= $this->userData['FirstName'] ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Фамилия') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= $this->userData['LastName'] ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Дата рождения') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= date_format(date_create($this->userData['DateBirthday']), 'd.m.Y') ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Страна') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= $this->userData['Country']['EnglishName'] . " ({$this->userData['Country']['NativeName']})" ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Город') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= $this->userData['City'] ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Последний визит') ?>:
                            </td>
                            <td>
                                <div class="break_word_wrap">
                                    <?= date_format(date_create($this->userData['DateLastActivity']), 'H:i d.m.Y') ?>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="site-statistic">
            <div class="well">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tbody>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Номер пользователя') ?>:
                            </td>
                            <td>
                                <?= $this->userData['ID'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Времени на сайте') ?>:
                            </td>
                            <td>
                                <?php
                                $d = new DateTime();
                                echo $d->diff(new DateTime($this->userData['DateCreate']))->format("<strong>" . $this->t('Лет') . ":</strong> %y <strong>" . $this->t('Месяцев') . ":</strong> %m <strong>" . $this->t('Дней') . ":</strong> %d");
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Дней на сайте') ?>:
                            </td>
                            <td>
                                <?php
                                echo date_diff(new DateTime(), new DateTime($this->userData['DateCreate']))->days;
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <?= $this->t('Дата регистрации') ?>:
                            </td>
                            <td>
                                <?= date_format(date_create($this->userData['DateCreate']), 'H:i d.m.Y') ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="user-contacts">
            <div class="well">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tbody>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/skype-20.png'); ?>"/>
                                <?= $this->t('Skype'), ':'; ?>
                            </td>
                            <td>
                                <?= $this->userData['Skype'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/icq-20.png'); ?>"/>
                                <?= $this->t('ICQ'), ':'; ?>
                            </td>
                            <td>
                                <?= $this->userData['Icq'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/googletalk-20.png'); ?>"/>
                                <?= $this->t('Google Talk'), ':'; ?>
                            </td>
                            <td>
                                <?= $this->userData['GoogleTalk'] ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/www-20.png'); ?>"/>
                                <?= $this->t('Веб-Сайт'), ':'; ?>
                            </td>
                            <td>
                                <?= $this->userData['WebSite'] ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="user-social">
            <div class="well">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <tbody>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/vk-20.png'); ?>"/>
                                <?= $this->t('Вконтакте'), ':'; ?>
                            </td>
                            <td>
                                <?= 'none' ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/facebook-20.png'); ?>"/>
                                <?= $this->t('Facebook'), ':'; ?>
                            </td>
                            <td>
                                <?= 'none' ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/twitter-20.png'); ?>"/>
                                <?= $this->t('Twitter'), ':'; ?>
                            </td>
                            <td>
                                <?= 'none' ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-bold">
                                <img
                                    src="<?= $this->baseUrl('data-content/ui/icons/googleplus-20.png'); ?>"/>
                                <?= $this->t('Google+'), ':'; ?>
                            </td>
                            <td>
                                <?= 'none' ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
<?php } ?>