<div id="tabs">
    <ul>
        <li><a href="#tabs-1"><?= $this->t('Язык'); ?></a></li>
        <li><a href="#tabs-2"><?= $this->t('Пароль'); ?></a></li>
    </ul>
    <div id="tabs-1">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-1" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>">
            <?= $this->form->getDisplayGroup('lang_settings'); ?>
            <?= $this->form->tab_name->setvalue('lang_settings'); ?>
            <?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
    <div id="tabs-2">
        <form id="<?= $this->form->getName(); ?>" action="<?= $this->form->getAction(); ?>#tabs-2" method="<?= $this->form->getMethod(); ?>" class="<?= $this->form->getAttrib('class'); ?>">
            <?= $this->form->getDisplayGroup('change_password'); ?>
            <?= $this->form->tab_name->setvalue('change_password'); ?>
            <?= $this->form->getDisplayGroup('form_actions'); ?>
        </form>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        $('#tabs').tabs();
    });
</script>