<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/track/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'track', 'add')) : ?>
                    <?php
                    $adminTrackAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'track', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminTrackAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить трассу'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="track-id">
                        <span>ID</span>
                    </th>
                    <th class="track-name">
                        <span><?= $this->t('Название'); ?></span>
                    </th>
                    <th class="track-year">
                        <span><?= $this->t('Год'); ?></span>
                    </th>
                    <th class="track-country">
                        <span><?= $this->t('Страна'); ?></span>
                    </th>
                    <th class="track-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->trackData) : ?>
                    <?php foreach ($this->trackData as $track): ?>
                        <?php
                        // check access and generate link for admin/track/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'track', 'id')) {
                            $adminTrackIDUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'track', 'action' => 'id',
                                    'trackID' => $this->escape($track['ID'])), 'adminTrackID'
                            );
                        } else {
                            $adminTrackIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for admin/country/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'country', 'id')) {
                            $adminCountryIDUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'country', 'action' => 'id',
                                    'countryID' => $this->escape($track['Country']['ID'])), 'adminCountryID'
                            );
                        } else {
                            $adminCountryIDUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="track-id">
                                <span>
                                    <a href="<?= $adminTrackIDUrl; ?>">
                                        <?= $this->escape($track['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="track-name">
                                <span>
                                    <a href="<?= $adminTrackIDUrl; ?>">
                                        <?= $this->escape($track['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="track-year">
                                <span>
                                    <?= $this->escape($track['Year']); ?>
                                </span>
                            </td>
                            <td class="track-country text-center">
                                <span>
                                    <a href="<?= $adminCountryIDUrl; ?>" class="tooltip-field"
                                       title="<?= $this->escape($track['Country']['EnglishName']); ?>">
                                        <img src="<?= $this->escape($track['Country']['ImageRoundUrl']); ?>"/>
                                    </a>
                                </span>
                            </td>
                            <td class="track-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Трасса"), false)
                                        ->trackMenu($this->escape($track['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->trackData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->trackData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
