<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>

<?php echo $this->championshipAddForm; ?>

<script type="text/javascript">
    $(document).ready(function () {
        <?php echo $this->CKEditor()->SetupFullHtmlEditor('Description'); ?>
        <?php echo $this->CKFinder()->setupCKEditor('Description'); ?>

        $("#DateStart").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });

        $("#DateEnd").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });
    });
</script>