<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/championship/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'championship', 'add')) : ?>
                    <?php
                    $adminChampionshipAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'championship', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminChampionshipAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить чемпионат'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="championship-id">
                        <span>ID</span>
                    </th>
                    <th class="championship-name">
                        <span><?= $this->t('Название'); ?></span>
                    </th>
                    <th class="championship-league">
                        <span><?= $this->t('Лига'); ?></span>
                    </th>
                    <th class="championship-racing-serie">
                        <span><?= $this->t('Гоночная серия'); ?></span>
                    </th>
                    <th class="championship-administrator">
                        <span><?= $this->t('Администратор'); ?></span>
                    </th>
                    <th class="championship-rule">
                        <span><?= $this->t('Регламент'); ?></span>
                    </th>
                    <th class="championship-game">
                        <span><?= $this->t('Игра'); ?></span>
                    </th>
                    <th class="championship-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->championshipData) : ?>
                    <?php foreach ($this->championshipData as $championship): ?>

                        <?php
                        // check access and generate link for default/championship/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'championship', 'id')) {
                            $defaultChampionshipIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'championship', 'action' => 'id',
                                    'championshipID' => $this->escape($championship['ID'])), 'defaultChampionshipID'
                            );
                        } else {
                            $defaultChampionshipIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/user/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                            $defaultUserIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                    'userID' => $this->escape($championship['User']['ID'])), 'defaultUserID'
                            );
                        } else {
                            $defaultUserIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/league/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'league', 'id')) {
                            $defaultLeagueIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'league', 'action' => 'id',
                                    'leagueID' => $this->escape($championship['League']['ID'])), 'defaultLeagueID'
                            );
                        } else {
                            $defaultLeagueIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/post/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'post', 'id')) {
                            $defaultPostRuleIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'post', 'action' => 'id',
                                    'postID' => $this->escape($championship['PostRule']['ID'])), 'defaultPostID'
                            );
                            $defaultPostGameIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'post', 'action' => 'id',
                                    'postID' => $this->escape($championship['PostGame']['ID'])), 'defaultPostID'
                            );
                        } else {
                            $defaultPostRuleIDUrl = '#';
                            $defaultPostGameIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/league/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'id')) {
                            $defaultRacingSeriesIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'racing-series', 'action' => 'id',
                                    'racingSeriesID' => $this->escape($championship['RacingSeries']['ID'])), 'adminRacingSeriesID'
                            );
                        } else {
                            $defaultRacingSeriesIDUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="championship-id">
                                <span>
                                    <a href="<?= $defaultChampionshipIDUrl; ?>">
                                        <?= $this->escape($championship['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-name">
                                <span>
                                    <a href="<?= $defaultChampionshipIDUrl; ?>">
                                        <?= $this->escape($championship['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-league">
                                <span>
                                    <a target="_blank" href="<?= $defaultLeagueIDUrl; ?>">
                                        <?= $this->escape($championship['League']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-racing-serie">
                                <span>
                                    <a target="_blank" href="<?= $defaultRacingSeriesIDUrl; ?>">
                                        <?= $this->escape($championship['RacingSeries']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-administrator">
                                <span>
                                    <a class="tooltip-field"
                                       title="<?= $this->escape($championship['User']['NickName']) ?>"
                                       target="_blank" href="<?= $defaultUserIDUrl; ?>">
                                        <?= $this->escape($championship['User']['LastName']) . ' ' . $this->escape($championship['User']['FirstName']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-rule">
                                <span>
                                    <a target="_blank" href="<?= $defaultPostRuleIDUrl; ?>">
                                        <?= $this->escape($championship['PostRule']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-game">
                                <span>
                                    <a target="_blank" href="<?= $defaultPostGameIDUrl; ?>">
                                        <?= $this->escape($championship['PostGame']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="championship-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Чемпионат"), false)
                                        ->championshipMenu($this->escape($championship['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->championshipData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->championshipData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>