<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>

<?= $this->championshipEditForm; ?>

<script type="text/javascript">
    $(document).ready(function () {
        <?= $this->CKEditor()->SetupFullHtmlEditor('Description'); ?>
        <?= $this->CKFinder()->setupCKEditor('Description'); ?>

        $("#DateStart").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });

        $("#DateEnd").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });
    });
</script>