<div id="article_add_page" class="page article_form">
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <?php echo $this->form; ?>
        <script type= "text/javascript" >
            $(document).ready(function(){
                 content_type = $("#content_type").find(':selected').text();
                    switch(content_type){
                        case 'bbcode':
                                bbcode();
                            break;
                        case 'text':
                                text();
                            break;
                        case 'full html':
                                full_html();
                            break;
                        default:
                                text();
                            break;
                    }
                
                function bbcode(){
                    var hEd = CKEDITOR.instances['text'];
                        if (hEd) {
                        hEd.destroy();
                    }
                    <?php
                        echo $this->setupBBCodeEditor('text');
                    ?>
                }
                
                function full_html(){
                    var hEd = CKEDITOR.instances['text'];
                        if (hEd) {
                        hEd.destroy();
                    }
                    <?php
                        echo $this->setupFullHtmlEditor('text');
                    ?>
                }
            
                function text(){
                    var hEd = CKEDITOR.instances['text'];
                    if (hEd) {
                        hEd.destroy();
                    }
                }
                
                $("#content_type").change(function(){
                    content_type = $(this).find(':selected').text();
                    switch(content_type){
                        case 'bbcode':
                                bbcode();
                            break;
                        case 'text':
                                text();
                            break;
                        case 'full html':
                                full_html();
                            break;
                        default:
                                text();
                            break;
                    }
                });
            });
        </script>
    </div>
</div>