<div id="articles_page" class="page">
    <div class="page_title"><?php echo $this->translate('Контент сайта'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            $filter = new Zend_Filter_StripTags();
            $bbcode = Zend_Markup::factory('Bbcode');
            ?>

            <?php foreach ($this->paginator as $item): ?>
                <div class="article_item">
                    <div class="article_title"><a href="<?php echo $this->baseUrl('article/view/' . $this->escape($item['id'])) ?>"><?php echo $this->escape($item['title']); ?></a></div>
                    <?php if ($this->escape($item['image']) != '') { ?>
                        <img class="img-polaroid article_image" src="<?php echo $this->escape($item['image']); ?>">
                    <?php } ?>
                    <div class="article_text"><?php echo $this->truncate($bbcode->render($filter->filter($item['text'])))->toLength(1000); ?></div>
                    <a href = "<?php echo $this->baseUrl('article/view/' . $this->escape($item['id'])) ?>" class = "btn btn-small btn-inverse article_more"><?php echo $this->translate('Подробнее...');
                    ?></a>
                    <div class="article_info">
                        <div class="article_author article_info_item"><span><?php echo $this->translate('Автор') ?>: </span><a href="<?php echo $this->baseUrl('user/info/' . $this->escape($item['user_id'])) ?>"><?php echo $item['user_id']; ?></a></div>
                        <div class="article_views article_info_item"><span><?php echo $this->translate('Просмотров') ?>: </span><?php echo $this->escape($item['views']); ?></div>
                        <div class="article_date article_info_item"><span><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($item['date']); ?></div>
                        <?php if ($item['date'] != $item['date_edit']) { ?>
                            <div class="article_date_edit article_info_item"><span><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($item['date_edit']); ?></div>
                        <?php } ?>
                    </div>
                </div>
                <?php
            endforeach;
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            ?>
            <?php
        } else {
            echo $this->translate('Контент не найден на сайте!');
        }
        ?>
    </div>
</div>