<div id="articles_page" class="page">
    <div class="page_title"><?php echo $this->translate('Контент сайта'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            $bbcode = Zend_Markup::factory('Bbcode');
            ?>

            <?php foreach ($this->paginator as $item): ?>
                <div class="article_item">
                    <div class="article_title"><a href="<?php echo $this->baseUrl('article/id/' . $this->escape($item['id'])) ?>"><?php echo $this->escape($item['title']); ?></a></div>
                    <?php if ($this->escape($item['image']) != '') { ?>
                        <img class="img-polaroid article_image" src="<?php echo $this->escape($item['image']); ?>">
                    <?php } ?>
                    <div class="article_text"><?php echo $this->truncate($bbcode->render($this->escape($item['text'])))->toLength(1000); ?></div>
                    <div class="article_controls">
                        <?php
                        if (Zend_Auth::getInstance()->hasIdentity()) {
                            if (Zend_Auth::getInstance()->getStorage('online-racing')->read()->id == $item['user_id']) {
                                ?>
                                <a href = "<?php echo $this->baseUrl('article/edit/' . $this->escape($item['id'])) ?>" class = "btn btn-small btn-inverse article_edit"><?php echo $this->translate('Редактировать') ?></a>
                                <?php
                            }
                        }
                        ?>
                        <a href = "<?php echo $this->baseUrl('article/id/' . $this->escape($item['id'])) ?>" class = "btn btn-small btn-inverse article_more"><?php echo $this->translate('Подробнее...') ?></a>
                    </div>
                    <div class="article_info">
                        <div class="article_author article_info_item"><span><?php echo $this->translate('Автор') ?>: </span><a href="<?php echo $this->baseUrl('user/info/' . $this->escape($item['user_id'])) ?>"><?php echo $item['login']; ?></a></div>
                        <div class="article_views article_info_item"><span><?php echo $this->translate('Просмотров') ?>: </span><?php echo $this->escape($item['views']); ?></div>
                        <div class="article_date article_info_item"><span><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($item['date']); ?></div>
                        <?php if ($item['date'] != $item['date_edit']) { ?>
                            <div class="article_date_edit article_info_item"><span><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($item['date_edit']); ?></div>
                        <?php } ?>
                    </div>
                </div>
                <?php
            endforeach;
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            ?>
            <?php
        } else { ?>
            <div class='alert alert-error'> <?php echo $this->translate('Контент не найден на сайте!'); ?></div>
        <?php } ?>
    </div>
</div>