<div id="article_delete_page" class="page article">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Удаление статьи') . ' :: ' . $this->escape($this->article->title);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="alert alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Предупреждение!'); ?></h4>
                <?php echo $this->translate('Вы действительно хотите удалить статью ') . '"' . $this->escape($this->article->title) . '"?'; ?>
            </div>

            <?php echo $this->form; ?>
            <div class="article_item">
                <?php
                if ($this->article->image != '') {
                    ?>
                    <img class="img-polaroid article_image" src="<?php echo $this->baseUrl($this->escape($this->article->image)); ?>">
                <?php } ?>
                <div class="article_text">
                    <?php 
                        echo $this->RenderContentTypeText($this->article->text, $this->article->content_type_name);
                    ?>
                </div>
                <div class="article_info">
                    <div class="article_type_name article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Тип статьи') ?>: </span><?php echo $this->escape($this->article->article_type_name); ?>
                    </div>
                    <div class="article_author article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Автор') ?>: </span>
                        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $this->escape($this->article->user_id)), 'user', true) ?>" target="_blank"><?php echo $this->escape($this->article->user_login); ?></a>
                    </div>
                    <div class="article_views article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Просмотров') ?>: </span><?php echo $this->escape($this->article->views); ?>
                    </div>
                    <div class="article_date_create article_info_item">
                        <span class="bold_text"><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->article->date_create); ?>
                    </div>
                    <?php if ($this->escape($this->article->date_create) != $this->escape($this->article->date_edit)) { ?>
                        <div class="article_date_edit article_info_item">
                            <span class="bold_text"><?php echo $this->translate('Редактировалось') ?>: </span><?php echo $this->escape($this->article->date_edit); ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>