<div id="article_edit_page" class="page article_form">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Редактировать') . ' ➛ ' . $this->escape($this->form->title->getvalue());
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <?php echo $this->form; ?>
        <?php
        echo $this->setupBBCodeEditor('text');
        ?>
    </div>
</div>