<div id="article_edit_page" class="page">
    <div class="page_title"><?php echo $this->translate('Редактировать').' > '.$this->form->title->getvalue(); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="messages errors">' . $this->errMessage . '</div>';
        }
        ?>
        <?php echo $this->form; ?>
    </div>
</div>