<div id="article_edit_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Редактировать') . ' ➛ ' . $this->escape($this->form->title->getvalue());
        } else {
            echo $this->translate('Ошибка!!!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="messages errors">' . $this->errMessage . '</div>';
        }
        ?>
        <?php echo $this->form; ?>
        <?php
            $this->ckeditor = 'ckeditor';
            echo $this->setupBBCodeEditor('text');
        ?>
    </div>
</div>