<div id="users_page" class="page">
    <div class="page_title"><?php if (!$this->errMessage != "") { echo $this->article->title; } ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="messages errors">' . $this->errMessage . '</div>';
        } else {
        ?>
        <?php echo $this->article->text; ?>
        <div><span><?php echo $this->translate('Автор')?>: </span><?php echo $this->article->user_id; ?></div>
        <div><span><?php echo $this->translate('Дата публикации')?>: </span><?php echo $this->article->date; ?></div>
        <?php if ($this->article->date != $this->article->date_edit) { ?>
            <div class="article_date_edit"><span><?php echo $this->translate('Последнее редактирование')?>: </span><?php echo $this->article->date ?></div>
        <?php } ?>
        <div><span><?php echo $this->translate('Просмотров')?>: </span><?php echo $this->article->views; ?></div>
        <?php }?>
    </div>
</div>