<div class="border_box">
    <div class="box_skitter box_skitter_large">

    </div>
</div>

<div id="rss_block">
    <h3>Новости из мира Formula-1:</h3>
    <?php
    $url = 'http://www.f1news.ru/export/news.xml';

    $xml = xml_parser_create();
    xml_parser_set_option($xml, XML_OPTION_SKIP_WHITE, 1);
    xml_parse_into_struct($xml, file_get_contents($url), $element, $index);
    xml_parser_free($xml);

    $count = 10;

    for ($i = 1; $i < $count; $i++) {
        echo '<div><h6 class="rss_title">' . '<a href="#">' . $element[$index["TITLE"][$i + 1]]["value"] . '</a>' . '</h6>';
        echo '<div class="rss_description">' . $element[$index["DESCRIPTION"][$i]]["value"];
        echo '<a class="rss_more" href="' . $element[$index["LINK"][$i + 1]]["value"] . '" target="_BLINK">' . "Подробнее на сайте F1-News.ru ..." . '</a></div></div>';
    }
    ?>
</div>
<script>
    jQuery(document).ready(function(){
        $("#rss_block").accordion({ header: "h6" });
        
    });
</script>