<div class="border_box">
						<div class="box_skitter box_skitter_large">
							<ul>
								<li><a href="http://google.com"><img src="img/slider/posts/post_1.jpg"/></a><div class="label_text"><p>Открытие сайта</p></div></li>
								<li><a href="#cubeRandom"><img src="img/slider/posts/002.jpg"/></a><div class="label_text"><p>Регистрация в чемпионате</p></div></li>
							</ul>
						</div>
					</div>

<p>
Привет-привет<br>
Заходи, не стесняйся. Новый сайт для соревнований по сим рейсингу.
</p>