<div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
    <div id="main-content" >
            <div class="row">
                    <div id="main-content-top" class="clearfix">
                        <div class="page-header pull-left">
                            <h3><?= $this->pageTitle() ?></h3>
                        </div>
                    </div>
            </div>
            <?= $this->showMessages(); ?>
            <?= $this->layout()->content ?>
    </div>
</div>