<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12 p-all-0">
        <header id="header">
            <nav class="navbar-static-top navbar-inverse" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target="#admin-main-menu">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <?php
                        $admin_index_url = $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), 'default', true);
                        ?>
                        <a href="<?= $admin_index_url; ?>" class="pull-left">
                            <img src="<?= $this->baseUrl('data-content/data-themes/layout-admin/img/logo.png'); ?>"
                                 class="img-responsive"/>
                        </a>
                    </div>
                    <div id="admin-main-menu" class="collapse navbar-collapse">
                        <!-- User Navigation menu  -->
                        <?= $this->render("common/user-nav-menu.phtml") ?>
                        <!-- /User Navigation menu  -->
                        <?php
                        $default_index_url = $this->url(
                            array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true
                        );
                        ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="<?= $default_index_url; ?>">
                                    <i class="fa fa-globe"></i> <?= $this->translate('Сайт'); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </nav>
        </header>
    </div>
</div>