<div class="main-content">
<div class="container">
    <div class="row">

        <div class="area-top clearfix">
            <div class="pull-left header">
                <h3 class="title">
                    <i class="fa fa-dashboard"></i>
                    Dashboard
                </h3>
                <h5>
            <span>
              A subtitle can go here
            </span>
                </h5>
            </div>

            <ul class="list-inline pull-right sparkline-box">

                <li class="sparkline-row">
                    <h4 class="blue"><span>Orders</span> 847</h4>
                    <div class="sparkline big" data-color="blue"><!--25,11,5,28,25,19,27,6,4,23,20,6--></div>
                </li>

                <li class="sparkline-row">
                    <h4 class="green"><span>Reviews</span> 223</h4>
                    <div class="sparkline big" data-color="green"><!--28,26,13,18,8,6,24,19,3,6,19,6--></div>
                </li>

                <li class="sparkline-row">
                    <h4 class="red"><span>New visits</span> 7930</h4>
                    <div class="sparkline big"><!--16,23,28,8,12,9,25,11,16,16,17,13--></div>
                </li>

            </ul>
        </div>
    </div>
</div>

<div class="container padded">
    <div class="row">

        <!-- Breadcrumb line -->

        <div id="breadcrumbs">
            <div class="breadcrumb-button blue">
                <span class="breadcrumb-label"><i class="fa fa-home"></i> Home</span>
                <span class="breadcrumb-arrow"><span></span></span>
            </div>



            <div class="breadcrumb-button">
          <span class="breadcrumb-label">
            <i class="fa fa-dashboard"></i> Dashboard
          </span>
                <span class="breadcrumb-arrow"><span></span></span>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?= $this->layout()->content ?>
        </div>
    </div>
</div>