<div class="sidebar-background">
    <div class="primary-sidebar-background"></div>
</div>

<div class="primary-sidebar">
    <!-- Main nav -->
    <ul class="nav navbar-collapse collapse navbar-collapse-primary">
        <li>
            <span class="glow"></span>
            <a href="<?php echo $this->baseUrl(); ?>">
                <i class="fa fa-globe fa-2x"></i>
                <span><?php echo $this->translate('Перейти на сайт'); ?></span>
            </a>
        </li>
        <li class="active">
            <span class="glow"></span>
            <?php
            $adminIndexUrl = $this->url(
                array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), 'default', true
            )
            ?>
            <a href="<?php echo $adminIndexUrl; ?>">
                <i class="fa fa-dashboard fa-2x"></i>
                <span><?php echo $this->translate('Панель управления'); ?></span>
            </a>
        </li>
        <li class="dark-nav">
            <span class="glow"></span>
            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#sidebar-site-content-links">
                <i class="fa fa-file fa-2x"></i>
                    <span>
                      <?php echo $this->translate('Контент'); ?>
                      <i class="fa fa-caret-down"></i>
                    </span>
            </a>
            <ul id="sidebar-site-content-links" class="collapse ">
                <li>
                    <?php
                    $adminPostAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'post', 'action' => 'all'),
                        'adminPostAll', true
                    )
                    ?>
                    <a href="<?php echo $adminPostAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Контент сайта'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminContentTypeAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'content-type', 'action' => 'all'),
                        'adminContentTypeAll', true
                    )
                    ?>
                    <a href="<?php echo $adminContentTypeAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Типы контента'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminPostCategoryAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'post-category', 'action' => 'all'),
                        'adminPostCategoryAll', true
                    )
                    ?>
                    <a href="<?php echo $adminPostCategoryAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Категории постов'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li class="dark-nav">
            <span class="glow"></span>
            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#sidebar-site-security-links">
                <i class="fa fa-exclamation-circle fa-2x"></i>
                    <span>
                      <?php echo $this->translate('Безопасность'); ?>
                        <i class="fa fa-caret-down"></i>
                    </span>
            </a>
            <ul id="sidebar-site-security-links" class="collapse ">
                <li>
                    <?php
                    $adminResourceAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'resource', 'action' => 'all'),
                        'adminResourceAll', true
                    )
                    ?>
                    <a href="<?php echo $adminResourceAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Ресурсы сайта'); ?>
                    </a>
                </li>

                <li>
                    <?php
                    $adminPrivelegeAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'privilege', 'action' => 'all'),
                        'adminPrivilegeAll', true
                    )
                    ?>
                    <a href="<?php echo $adminPrivelegeAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Привилегии ресурсов'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminResourceAccessAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'resource-access',
                            'action' => 'all'), 'adminResourceAccessAll', true
                    )
                    ?>
                    <a href="<?php echo $adminResourceAccessAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Доступ к ресурсам'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li class="dark-nav">
            <span class="glow"></span>
            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#sidebar-users-links">
                <i class="fa fa-users fa-2x"></i>
                    <span>
                      <?php echo $this->translate('Пользователи'); ?>
                        <i class="fa fa-caret-down"></i>
                    </span>
            </a>
            <ul id="sidebar-users-links" class="collapse ">
                <li>
                    <?php
                    $adminUserAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'user', 'action' => 'all',
                            'page'   => 1), 'adminUserAll', true
                    )
                    ?>
                    <a href="<?php echo $adminUserAllUrl; ?>">
                        <i class="fa fa-users"></i>
                        <?php echo $this->translate('Пользователи'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminRoleAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'role', 'action' => 'all'),
                        'adminRoleAll', true
                    )
                    ?>
                    <a href="<?php echo $adminRoleAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Роли пользователей'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li class="dark-nav">
            <span class="glow"></span>
            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#sidebar-leagues-champs-links">
                <i class="fa fa-trophy fa-2x"></i>
                    <span>
                      <?php echo $this->translate('Лиги и Чемпионаты'); ?>
                        <i class="fa fa-caret-down"></i>
                    </span>
            </a>
            <ul id="sidebar-leagues-champs-links" class="collapse ">
                <li>
                    <?php
                    $adminLeagueAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'league', 'action' => 'all'),
                        'adminLeagueAll', true
                    )
                    ?>
                    <a href="<?php echo $adminLeagueAllUrl; ?>">
                        <i class="fa fa-users"></i>
                        <?php echo $this->translate('Лиги'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminChampionshipAllUrl =$this->url(
                        array('module' => 'admin', 'controller' => 'championship', 'action' => 'all'),
                        'adminChampionshipAll', true
                    )
                    ?>
                    <a href="<?php echo $adminChampionshipAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Чемпионаты'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminRacingSeriesAllUrl =$this->url(
                        array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'all'),
                        'adminRacingSeriesAll', true
                    )
                    ?>
                    <a href="<?php echo $adminRacingSeriesAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Гоночные серии'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminTrackAllUrl =$this->url(
                        array('module' => 'admin', 'controller' => 'track', 'action' => 'all'),
                        'adminTrackAll', true
                    )
                    ?>
                    <a href="<?php echo $adminTrackAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Трассы'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminTeamAllUrl =$this->url(
                        array('module' => 'admin', 'controller' => 'team', 'action' => 'all'),
                        'adminTeamAll', true
                    )
                    ?>
                    <a href="<?php echo $adminTeamAllUrl; ?>">
                        <i class="fa fa-file-text"></i>
                        <?php echo $this->translate('Команды'); ?>
                    </a>
                </li>
            </ul>
        </li>
        <li class="dark-nav">
            <span class="glow"></span>
            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#sidebar-site-components-links">
                <i class="fa fa-gavel fa-2x"></i>
                    <span>
                      <?php echo $this->translate('Компоненты сайта'); ?>
                        <i class="fa fa-caret-down"></i>
                    </span>
            </a>
            <ul id="sidebar-site-components-links" class="collapse ">
                <li>
                    <?php
                    $adminCountryAllUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'country', 'action' => 'all'),
                        'adminCountryAll'
                    )
                    ?>
                    <a href="<?php echo $adminCountryAllUrl; ?>">
                        <i class="fa fa-users"></i>
                        <?php echo $this->translate('Страны'); ?>
                    </a>
                </li>
                <li>
                    <?php
                    $adminFileManagerUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'file-manager', 'action' => 'index'),
                        'default', true
                    )
                    ?>
                    <a href="<?php echo $adminFileManagerUrl; ?>">
                        <i class="fa fa-users"></i>
                        <?php echo $this->translate('Файловый менеджер'); ?>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- ./ Main nav -->

    <div class="hidden-sm hidden-xs">
        <div class="text-center" style="margin-top: 60px">
            <div class="easy-pie-chart-percent" style="display: inline-block" data-percent="89"><span>89%</span></div>
            <div style="padding-top: 20px"><b>CPU Usage</b></div>
        </div>

        <hr class="divider" style="margin-top: 60px">

        <div class="sparkline-box side">

            <div class="sparkline-row">
                <h4 class="gray"><span>Orders</span> 847</h4>

                <div class="sparkline big" data-color="gray"><!--16,7,23,13,12,11,15,4,19,18,4,24--></div>
            </div>

            <hr class="divider">
            <div class="sparkline-row">
                <h4 class="dark-green"><span>Income</span> $43.330</h4>

                <div class="sparkline big" data-color="darkGreen"><!--6,3,24,25,27,29,14,26,20,8,12,20--></div>
            </div>

            <hr class="divider">
            <div class="sparkline-row">
                <h4 class="blue"><span>Reviews</span> 223</h4>

                <div class="sparkline big" data-color="blue"><!--11,19,20,20,5,18,11,6,16,20,26,11--></div>
            </div>

            <hr class="divider">
        </div>
    </div>
</div>