<div class="sidebar-background">
    <div class="primary-sidebar-background"></div>
</div>
<div class="primary-sidebar">

    <!-- Main nav -->
    <ul class="nav navbar-collapse collapse navbar-collapse-primary">



        <li class="active">
            <span class="glow"></span>
            <a href="dashboard.html">
                <i class="fa fa-dashboard fa-2x"></i>
                <span>Dashboard</span>
            </a>
        </li>






        <li class="dark-nav ">

            <span class="glow"></span>



            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#yJ6h3Npe7C">
                <i class="fa fa-beaker fa-2x"></i>
                    <span>
                      UI Lab
                      <i class="fa fa-caret-down"></i>
                    </span>

            </a>

            <ul id="yJ6h3Npe7C" class="collapse ">

                <li class="">
                    <a href="../ui_lab/buttons.html">
                        <i class="fa fa-hand-up"></i> Buttons
                    </a>
                </li>

                <li class="">
                    <a href="../ui_lab/general.html">
                        <i class="fa fa-beaker"></i> General elements
                    </a>
                </li>

                <li class="">
                    <a href="../ui_lab/icons.html">
                        <i class="fa fa-info-sign"></i> Icons
                    </a>
                </li>

                <li class="">
                    <a href="../ui_lab/grid.html">
                        <i class="fa fa-th-large"></i> Grid
                    </a>
                </li>

                <li class="">
                    <a href="../ui_lab/tables.html">
                        <i class="fa fa-table"></i> Tables
                    </a>
                </li>

                <li class="">
                    <a href="../ui_lab/widgets.html">
                        <i class="fa fa-plus-sign-alt"></i> Widgets
                    </a>
                </li>

            </ul>

        </li>






        <li class="">
            <span class="glow"></span>
            <a href="../forms/forms.html">
                <i class="fa fa-edit fa-2x"></i>
                <span>Forms</span>
            </a>
        </li>






        <li class="">
            <span class="glow"></span>
            <a href="../charts/charts.html">
                <i class="fa fa-bar-chart fa-2x"></i>
                <span>Charts</span>
            </a>
        </li>






        <li class="dark-nav ">

            <span class="glow"></span>



            <a class="accordion-toggle collapsed " data-toggle="collapse" href="#WLGsdJPav9">
                <i class="fa fa-link fa-2x"></i>
                    <span>
                      Others
                      <i class="fa fa-caret-down"></i>
                    </span>

            </a>

            <ul id="WLGsdJPav9" class="collapse ">

                <li class="">
                    <a href="../other/wizard.html">
                        <i class="fa fa-magic"></i> Wizard
                    </a>
                </li>

                <li class="">
                    <a href="../other/login.html">
                        <i class="fa fa-user"></i> Login Page
                    </a>
                </li>

                <li class="">
                    <a href="../other/sign_up.html">
                        <i class="fa fa-user"></i> Sign Up Page
                    </a>
                </li>

                <li class="">
                    <a href="../other/full_calendar.html">
                        <i class="fa fa-calendar"></i> Full Calendar
                    </a>
                </li>

                <li class="">
                    <a href="../other/error404.html">
                        <i class="fa fa-ban-circle"></i> Error 404 page
                    </a>
                </li>

            </ul>

        </li>




    </ul>

    <div class="hidden-sm hidden-xs">
        <div class="text-center" style="margin-top: 60px">
            <div class="easy-pie-chart-percent" style="display: inline-block" data-percent="89"><span>89%</span></div>
            <div style="padding-top: 20px"><b>CPU Usage</b></div>
        </div>

        <hr class="divider" style="margin-top: 60px">

        <div class="sparkline-box side">

            <div class="sparkline-row">
                <h4 class="gray"><span>Orders</span> 847</h4>
                <div class="sparkline big" data-color="gray"><!--16,7,23,13,12,11,15,4,19,18,4,24--></div>
            </div>

            <hr class="divider">
            <div class="sparkline-row">
                <h4 class="dark-green"><span>Income</span> $43.330</h4>
                <div class="sparkline big" data-color="darkGreen"><!--6,3,24,25,27,29,14,26,20,8,12,20--></div>
            </div>

            <hr class="divider">
            <div class="sparkline-row">
                <h4 class="blue"><span>Reviews</span> 223</h4>
                <div class="sparkline big" data-color="blue"><!--11,19,20,20,5,18,11,6,16,20,26,11--></div>
            </div>

            <hr class="divider">
        </div>
    </div>


</div>