<?php
$default_game_id_url = $this->url(
    array('module'  => 'default', 'controller' => 'post', 'action' => 'id',
          'post_id' => $this->escape($this->championship_data->game_id)),
    'defaultPostId', true
);
$default_rule_id_url = $this->url(
    array('module'  => 'default', 'controller' => 'post', 'action' => 'id',
          'post_id' => $this->escape($this->championship_data->rule_id)),
    'defaultPostId', true
);
$default_championship_drivers_url = $this->url(
    array('module'          => 'default', 'controller' => 'championship', 'action' => 'drivers',
          'league_id'       => $this->escape($this->championship_data->league_id),
          'championship_id' => $this->escape($this->championship_data->id)), 'defaultChampionshipAction', true
);
$default_championship_calendar_url = $this->url(
    array('module'          => 'default', 'controller' => 'championship', 'action' => 'calendar',
          'league_id'       => $this->escape($this->championship_data->league_id),
          'championship_id' => $this->escape($this->championship_data->id)), 'defaultChampionshipAction', true
);

$default_championship_driver_standings_url = $this->url(
    array('module'          => 'default', 'controller' => 'championship', 'action' => 'ds',
          'league_id'       => $this->escape($this->championship_data->league_id),
          'championship_id' => $this->escape($this->championship_data->id)), 'defaultChampionshipAction', true
);
$default_championship_team_standings_url = $this->url(
    array('module'          => 'default', 'controller' => 'championship', 'action' => 'ts',
          'league_id'       => $this->escape($this->championship_data->league_id),
          'championship_id' => $this->escape($this->championship_data->id)), 'defaultChampionshipAction', true
);
?>
<!-- start championship menu block -->
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
        <div class="block m-b-15">
            <div class="block-body">
                <nav class="navbar navbar-default m-b-0" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#championship-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <span class="navbar-brand tooltip-field" data-placement="bottom"
                                  data-title="<?php echo $this->championship_data->name; ?>"><i
                                    class="fa fa-trophy"></i></span>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="championship-navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="<?php echo $default_championship_drivers_url ?>"
                                       title="<?php echo $this->translate('Гонщики') ?>"><?php echo $this->translate(
                                            'Гонщики'
                                        ) ?></a></li>
                                <li><a href="<?php echo $default_championship_calendar_url ?>"
                                       title="<?php echo $this->translate('Календарь') ?>"><?php echo $this->translate(
                                            'Календарь'
                                        ) ?></a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle"
                                       data-toggle="dropdown"><?php echo $this->translate('Зачеты') ?> <b
                                            class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $default_championship_driver_standings_url; ?>"
                                               title="<?php echo $this->translate(
                                                   'Личный зачет'
                                               ) ?>"><?php echo $this->translate('ЛЗ') ?></a></li>
                                        <li><a href="<?php echo $default_championship_team_standings_url; ?>"
                                               title="<?php echo $this->translate(
                                                   'Командный зачет'
                                               ) ?>"><?php echo $this->translate('КЗ') ?></a></li>
                                    </ul>
                                </li>
                            </ul>
                            <a class="btn btn-success navbar-btn m-l-10" href="<?php echo $default_game_id_url ?>"
                               title="<?php echo $this->translate('Игра для проведения') ?>"
                               target="_blank"><?php echo $this->translate('Игра') ?></a>
                            <a class="btn btn-danger navbar-btn m-l-10" href="<?php echo $default_rule_id_url ?>"
                               title="<?php echo $this->translate('Регламент чемпионата') ?>"
                               target="_blank"><?php echo $this->translate('Регламент') ?></a>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
            </div>
        </div>
    </div>
</div><!-- end championship menu block -->