<?php if ($this->championship_data->hotlap_ip): ?>
    <!-- strat hotlap block -->
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
            <div class="block block-default block-hotlap m-b-15">
                <div class="block-body">
                    <nav class="navbar navbar-default m-b-0" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#hotlap-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="hotlap-navbar-collapse" class="collapse navbar-collapse">
                            <p class="navbar-text hotlap-marquee">
                                <iframe src="http://<?php echo $this->championship_data->hotlap_ip; ?>/rFactorHotlaps/Marquee.htm" name="standings" width="625" height="25" scrolling="no" id="standings" frameborder="0" style="background:none;"></iframe>
                            </p>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate("Ссылки"); ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="http://<?php echo $this->championship_data->hotlap_ip; ?>/rFactorLive" target="_BLINK"><?php echo $this->translate('Прямой эфир') ?></a></li>
                                        <li><a href="http://<?php echo $this->championship_data->hotlap_ip; ?>/rFactorHotlaps?max=25" target="_BLINK"><?php echo $this->translate('Рекорды') ?></a></li>
                                        <li class="divider"></li>
                                        <li><a href="http://<?php echo $this->championship_data->hotlap_ip; ?>/rFactorLeagues" target="_BLINK"><?php echo $this->translate('Лиги') ?></a></li>
                                        <li><a href="http://<?php echo $this->championship_data->hotlap_ip; ?>/rFactorResults" target="_BLINK"><?php echo $this->translate('Результаты') ?></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div><!-- end hotlap block -->
<?php endif; ?>