<?php if ($this->championshipData['HotLapsIP']): ?>
    <!-- strat hotlap block -->
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
            <div class="block block-default block-hotlap m-b-15">
                <div class="block-body">
                    <nav class="navbar navbar-default m-b-0" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#hotlap-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="hotlap-navbar-collapse" class="collapse navbar-collapse">
                            <p class="navbar-text hotlap-marquee">
                                <iframe
                                    src="http://<?= $this->championshipData['HotLapsIP']; ?>/rFactorHotlaps/Marquee.htm"
                                    name="standings" width="625" height="25" scrolling="no" id="standings"
                                    frameborder="0" style="background:none;"></iframe>
                            </p>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <?= $this->t("Ссылки"); ?> <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="http://<?= $this->championshipData['HotLapsIP']; ?>/rFactorLive"
                                               target="_blank">
                                                <?= $this->t('Прямой эфир') ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://<?= $this->championshipData['HotLapsIP']; ?>/rFactorHotlaps?max=25"
                                               target="_blank">
                                                <?= $this->t('Рекорды') ?>
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="http://<?= $this->championshipData['HotLapsIP']; ?>/rFactorLeagues"
                                               target="_blank">
                                                <?= $this->t('Лиги') ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://<?= $this->championshipData['HotLapsIP']; ?>/rFactorResults"
                                               target="_blank">
                                                <?= $this->t('Результаты') ?>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div><!-- end hotlap block -->
<?php endif; ?>