<?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'league', 'add')) : ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="clearfix m-b-10">
                <?php
                $adminLeagueAddUrl = $this->url(
                    array('module' => 'admin', 'controller' => 'league', 'action' => 'add'), 'default'
                );
                ?>
                <a href="<?php echo $adminLeagueAddUrl; ?>" class="btn btn-success pull-right ">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Добавить лигу'); ?>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->leagueData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="league-id">
                                <span>ID</span>
                            </th>
                            <th class="league-name">
                                <span><?php echo $this->translate('Название'); ?></span>
                            </th>
                            <th class="league-admin">
                                <span><?php echo $this->translate('Администратор'); ?></span>
                            </th>
                            <th class="league-description">
                                <span><?php echo $this->translate('Описание'); ?></span>
                            </th>
                            <th class="league-action">
                                <span><?php echo $this->translate('Действие'); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->leagueData as $league): ?>
                            <?php if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'league', 'id')) {
                                $adminLeagueIdUrl = $this->url(
                                    array('module' => 'admin', 'controller' => 'league', 'action' => 'id',
                                        'leagueID' => $this->escape($league['ID'])), 'defaultLeagueID'
                                );
                            } else {
                                $adminLeagueIdUrl = '#';
                            }
                            ?>

                            <?php if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                                $defaultUserIdUrl = $this->url(
                                    array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                        'user_id' => $this->escape($league['User']['id'])), 'defaultUserId'
                                );
                            } else {
                                $defaultUserIdUrl = '#';
                            }
                            ?>
                            <tr>
                                <td class="league-id">
                                    <span>
                                        <a href="<?php echo $adminLeagueIdUrl; ?>">
                                            <?php echo $this->escape($league['ID']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="league-name">
                                    <span>
                                        <a href="<?php echo $adminLeagueIdUrl; ?>">
                                            <?php echo $this->escape($league['Name']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="league-admin">
                                    <span>
                                        <a target="_blank" href="<?php echo $defaultUserIdUrl; ?>">
                                            <?php echo $this->escape($league['User']['login']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="league-description">
                                    <span>
                                        <?php echo $this->renderContentTypeText($league['Description'], 'full_html'); ?>
                                    </span>
                                </td>
                                <td class="league-action">
                                    <span>
                                        <?php
                                        echo $this->BlockConfigMenu($this->translate("Лига"), false)->leagueMenu(
                                            $this->escape($league['ID']), true
                                        );
                                        ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="pull-right">
                        <?php echo $this->paginationControl(
                            $this->leagueData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>