<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/league/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'league', 'add')) : ?>
                    <?php
                    $adminLeagueAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'league', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminLeagueAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить лигу'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="league-id">
                        <span>ID</span>
                    </th>
                    <th class="league-name">
                        <span><?= $this->t('Название'); ?></span>
                    </th>
                    <th class="league-administrator">
                        <span><?= $this->t('Администратор'); ?></span>
                    </th>
                    <th class="league-description">
                        <span><?= $this->t('Описание'); ?></span>
                    </th>
                    <th class="league-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->leagueData) : ?>
                    <?php foreach ($this->leagueData as $league): ?>
                        <?php
                        // check access and generate link for default/league/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'league', 'id')) {
                            $defaultLeagueIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'league', 'action' => 'id',
                                    'leagueID' => $this->escape($league['ID'])), 'defaultLeagueID'
                            );
                        } else {
                            $defaultLeagueIDUrl = '#';
                        }
                        ?>
                        <?php
                        // check access and generate link for default/user/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                            $defaultUserIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                    'userID' => $this->escape($league['User']['ID'])), 'defaultUserID'
                            );
                        } else {
                            $defaultUserIDUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="league-id">
                                <span>
                                    <a href="<?= $defaultLeagueIDUrl; ?>">
                                        <?= $this->escape($league['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="league-name">
                                <span>
                                    <a href="<?= $defaultLeagueIDUrl; ?>">
                                        <?= $this->escape($league['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="league-administrator">
                                <span>
                                    <a class="tooltip-field"
                                       title="<?= $this->escape($league['User']['NickName']) ?>"
                                       target="blank" href="<?= $defaultUserIDUrl; ?>">
                                        <?= $this->escape($this->getUser($league['User'])->getFullName()); ?>
                                    </a>
                                </span>
                            </td>
                            <td class="league-description">
                                <span>
                                    <?= $this->renderContentTypeText($league['Description'], 'full_html'); ?>
                                </span>
                            </td>
                            <td class="league-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Лига"), false)
                                        ->leagueMenu($this->escape($league['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->leagueData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->leagueData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
