<?php if ($this->leagueData) { ?>
    <div class="m-b-10">
        <?= $this->leagueDeleteForm; ?>
        <hr/>
    </div>
    <?php
    // check access and generate link for default/user/id
    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
        $defaultUserIDUrl = $this->url(
            array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                'userID' => $this->escape($this->leagueData['User']['ID'])), 'defaultUserID'
        );
    } else {
        $defaultUserIDUrl = '#';
    }
    ?>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->leagueData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Логотип лиги'); ?></span>
                    </td>
                    <td>
                        <span>
                            <img class="img-responsive"
                                src="<?= $this->baseUrl($this->escape($this->leagueData['LogoUrl'])); ?>" />
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Администратор'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a class="tooltip-field"
                           title="<?= $this->escape($this->leagueData['User']['NickName']) ?>"
                           target="blank" href="<?= $defaultUserIDUrl; ?>">
                            <?= $this->escape($this->getUser($this->leagueData['User'])->getFullName()); ?>
                        </a>
                    </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->RenderContentTypeText($this->leagueData['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->translate('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->translate('Лига'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->translate('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->leagueData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->leagueData['DateCreate']) != $this->escape($this->leagueData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->translate('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->leagueData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>