<?php
$raceEvent = $this->raceEventData;
?>

<?php if ($raceEvent) { ?>
    <div class="m-b-10">
        <?= $this->raceEventDeleteForm; ?>
        <hr/>
    </div>

    <?php
    // check access and generate link for default/championship/id
    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'championship', 'id')) {
        $adminChampionshipIDUrl = $this->url(
            array('module' => 'default', 'controller' => 'championship', 'action' => 'id',
                'championshipID' => $this->escape($raceEvent['ID'])), 'defaultChampionshipID'
        );
    } else {
        $adminChampionshipIDUrl = '#';
    }
    ?>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr class="race-event-name">
                    <td class="text-bold">
                        <span><?= $this->t('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($raceEvent['Name']); ?></span>
                    </td>
                </tr>
                <tr class="race-event-description">
                    <td class="text-bold">
                        <span><?= $this->t('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->RenderContentTypeText($raceEvent['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                <tr class="race-event-championship">
                    <td class="text-bold">
                        <span><?= $this->t('Чемпионат'); ?></span>
                    </td>
                    <td>
                        <span>
                            <a href="<?= $adminChampionshipIDUrl; ?>">
                                <?= $this->escape($raceEvent['Championship']['Name']) ?>
                            </a>
                        </span>
                    </td>
                </tr>
                <tr class="race-event-order-in-champ">
                    <td class="text-bold">
                        <span><?= $this->t('Порядковый номер в чемпионате'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($raceEvent['OrderInChamp']); ?></span>
                    </td>
                </tr>
                <tr class="race-event-date-start">
                    <td class="text-bold">
                        <span><?= $this->t('Дата старта'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($raceEvent['DateStart']); ?></span>
                    </td>
                </tr>
                <tr class="race-event-date-end">
                    <td class="text-bold">
                        <span><?= $this->t('Дата окончания'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($raceEvent['DateEnd']); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->t('Гоночное событие'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->t('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($raceEvent['DateCreate']); ?>
            </div>
            <?php if ($this->escape($raceEvent['DateCreate']) != $this->escape($raceEvent['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->t('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($raceEvent['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>