<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>

<?php $this->minifyHeadLink()->appendStylesheet("/library/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"); ?>
<?php $this->MinifyHeadScript()->appendFile("/library/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"); ?>
<?php $this->MinifyHeadScript()->appendFile("/library/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.ru.js"); ?>

<?= $this->raceEventEditForm; ?>

<script type="text/javascript">
    $(document).ready(function () {
        <?= $this->CKEditor()->SetupFullHtmlEditor('Description'); ?>
        <?= $this->CKFinder()->setupCKEditor('Description'); ?>


        $('#DateStart, #DateEnd').datetimepicker({
            language:  'ru',
            format: "yyyy-mm-dd hh:ii:00",
            weekStart: 1,
            todayBtn:  1,
            todayHighlight: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            forceParse: 1
        });
    });
</script>