<div id="game_add_page" class="page">
    <div class="page_title"><?php echo $this->translate('Добавить игру'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class="alert alert-info alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4><?php echo $this->translate('Информация!'); ?></h4>
            <?php echo $this->translate('Это страницы добавления игры. Чтобы добавить игру, обязательно выберите тип Game, иначе вы не сможете создать игру!!! И введите все необходимые данные.'); ?>
        </div>
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <?php echo $this->form; ?>
        <?php
            $this->ckeditor = 'ckeditor';
            echo $this->setupBBCodeEditor('text');
        ?>
    </div>
</div>