<div id="race_add_page" class="page">
    <div class="page_content">
        <?php echo $this->form; ?>
        <script>
            jQuery(document).ready(function() {
                $("#date_race").datetimepicker({
                    showButtonPanel: true,
                    dateFormat: "yy-mm-dd",
                    showAnim: "clip",
                    showSecond: true,
                    timeFormat: 'HH:mm:ss',
                    stepHour: 1,
                    stepSecond: 10
                });
            });
        </script>
    </div>
</div>