<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>
<?= $this->form; ?>
<script>
	jQuery(document).ready(function() {
		$("#race_date").datetimepicker({
			showButtonPanel: true,
			dateFormat: "yy-mm-dd",
			showAnim: "clip",
			showSecond: true,
			timeFormat: 'HH:mm:ss',
			stepHour: 1,
			stepSecond: 10
		});
		<?php
		echo $this->CKEditor()->SetupFullHtmlEditor('description');
		echo $this->CKFinder()->setupCKEditor('description');
		?>
	});
</script>