<?php if ($this->race_data): ?>

    <?php echo $this->render('championship/common/championship_menu.phtml') ?>

    <?php echo $this->render('championship/common/hotlap_menu.phtml') ?>

    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="panel block">
                <?php
                echo $this->BlockConfigMenu($this->translate("Гонка"))->championshipRaceMenu($this->escape($this->league_data->id), $this->escape($this->championship_data->id), $this->escape($this->race_data->id));
                ?>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <blockquote class="pull-right">
                                <h3><?php echo $this->escape($this->race_data->track_name); ?></h3>

                                <h1>
                                    <small><?php echo $this->translate('Раунд'); ?>: <span
                                            class="label label-info"><?php echo $this->escape($this->race_data->race_number); ?></span>
                                    </small>
                                </h1>
                            </blockquote>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <?php if ($this->escape($this->race_data->track_url_scheme) != '') : ?>
                                <div class="m-b-15 center-block text-center">
                                    <a href="#" data-toggle="modal" data-target=".champ-race-<?php print $this->race_data->id; ?>"
                                       title="<?php echo $this->escape($this->race_data->name); ?>" class="">
                                        <img class="img-responsive img-thumbnail"
                                             src="<?php echo $this->baseUrl($this->escape($this->race_data->track_url_scheme)); ?>">
                                    </a>
                                    <?php echo $this->modal(array(
                                        'title' => $this->race_data->track_name,
                                        'class' => 'champ-race-'.$this->race_data->id,
                                        'content' => '<img src="'.$this->baseUrl($this->escape($this->race_data->track_url_scheme)).'" class="img-responsive img-rounded center-block" alt="">'
                                    )); ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php if ($this->race_data->track_url_logo): ?>
                            <div class="col-lg-6">
                                <div class="center-block text-center m-b-10">
                                    <img class="img-responsive img-thumbnail img-size-150"
                                         src="<?php echo $this->baseUrl($this->escape($this->race_data->track_url_logo)); ?>">
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#track-description"
                                                      data-toggle="tab"><?php echo $this->translate('О трассе'); ?></a>
                                </li>
                                <li><a href="#race-description"
                                       data-toggle="tab"><?php echo $this->translate('О гонке'); ?></a></li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="track-description">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <span><?php echo $this->RenderContentTypeText($this->race_data->track_description, 'full_html'); ?></span>
                                        </div>
                                        <!-- Table -->
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                <tr>
                                                    <th><span><?php echo $this->translate('Страна'); ?></span></th>
                                                    <th><span><?php echo $this->translate('Год конфигурации'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><span><?php echo $this->translate('Длина круга'); ?></span>
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="text-vertical-m">
                                                        <span class="tooltip-field" data-placement="bottom"
                                                              data-title="<?php print $this->escape($this->race_data->country_english_name); ?>">
                                                            <img
                                                                src="<?php echo $this->escape($this->race_data->country_url_image_round); ?>">
                                                        </span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?php echo $this->escape($this->race_data->track_year); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?php echo $this->escape($this->race_data->track_length); ?></span>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="race-description">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <span><?php echo $this->RenderContentTypeText($this->race_data->description, 'full_html'); ?></span>
                                        </div>
                                        <!-- Table -->
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                <tr>
                                                    <th><span><?php echo $this->translate('Номер этапа'); ?></span></th>
                                                    <th><span><?php echo $this->translate('Дата проведения'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><span><?php echo $this->translate('Количество кругов'); ?></span>
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="text-vertical-m">
                                                        <span><?php echo $this->escape($this->race_data->race_number); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?php echo $this->escape($this->race_data->race_date); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?php echo $this->escape($this->race_data->race_laps); ?></span>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>