<?php if ($this->race_data): ?>

    <?= $this->render('championship/common/championship-menu.phtml') ?>
    <?= $this->render('championship/common/hotlaps-menu.phtml') ?>

    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="panel block block-default">
                <?php
                echo $this->BlockConfigMenu($this->t("Гонка"))->championshipRaceMenu(
                    $this->escape($this->leagueData['ID']),
                    $this->escape($this->championship_data->id),
                    $this->escape($this->race_data->id),
                    $this->escape($this->race_data->track_id)
                );
                ?>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <blockquote class="pull-right">
                                <h3><?= $this->escape($this->race_data->track_name); ?></h3>
                                <h1>
                                    <small><?= $this->t('Раунд'); ?>: <span
                                            class="label label-info"><?= $this->escape($this->race_data->race_number); ?></span>
                                    </small>
                                </h1>
                            </blockquote>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
                            <?php if ($this->escape($this->race_data->track_url_scheme)) : ?>
                                <div class="m-b-15 center-block text-center">
                                    <a href="#" data-toggle="modal" data-target=".champ-race-<?php print $this->race_data->id; ?>"
                                       title="<?= $this->escape($this->race_data->name); ?>" class="">
                                        <img class="img-responsive img-thumbnail"
                                             src="<?= $this->baseUrl($this->escape($this->race_data->track_url_scheme)); ?>" />
                                    </a>
                                    <?= $this->modal(array(
                                        'title' => $this->race_data->track_name,
                                        'class' => 'champ-race-'.$this->race_data->id,
                                        'content' => '<img src="'.$this->baseUrl($this->escape($this->race_data->track_url_scheme)).'" class="img-responsive img-rounded center-block" alt="">'
                                    )); ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php if ($this->race_data->track_url_logo): ?>
                            <div class="col-lg-6">
                                <div class="center-block text-center m-b-10">
                                    <img class="img-responsive img-thumbnail img-size-150"
                                         src="<?= $this->baseUrl($this->escape($this->race_data->track_url_logo)); ?>" />
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#track-description"
                                                      data-toggle="tab"><?= $this->t('О трассе'); ?></a>
                                </li>
                                <li><a href="#race-description"
                                       data-toggle="tab"><?= $this->t('О гонке'); ?></a></li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="track-description">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <span><?= $this->RenderContentTypeText($this->race_data->track_description, 'full_html'); ?></span>
                                        </div>
                                        <!-- Table -->
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                <tr>
                                                    <th>
                                                        <span><?= $this->t('Страна'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><?= $this->t('Год конфигурации'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><?= $this->t('Длина круга'); ?></span>
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="text-vertical-m">
                                                        <span class="tooltip-field" data-placement="bottom"
                                                              data-title="<?php print $this->escape($this->race_data->country_EnglishName); ?>">
                                                            <img
                                                                src="<?= $this->escape($this->race_data->country_ImageRoundUrl); ?>">
                                                        </span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?= $this->escape($this->race_data->track_year); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?= $this->escape($this->race_data->track_length); ?></span>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="race-description">
                                    <div class="panel">
                                        <div class="panel-body">
                                            <span><?= $this->RenderContentTypeText($this->race_data->description, 'full_html'); ?></span>
                                        </div>
                                        <!-- Table -->
                                        <div class="table-responsive">
                                            <table class="table table-bordered">
                                                <thead>
                                                <tr>
                                                    <th>
                                                        <span><?= $this->t('Номер этапа'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><?= $this->t('Дата проведения'); ?></span>
                                                    </th>
                                                    <th>
                                                        <span><?= $this->t('Количество кругов'); ?></span>
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td class="text-vertical-m">
                                                        <span><?= $this->escape($this->race_data->race_number); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?= $this->escape($this->race_data->race_date); ?></span>
                                                    </td>
                                                    <td class="text-vertical-m">
                                                        <span><?= $this->escape($this->race_data->race_laps); ?></span>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>