<?php
    $raceEvents = $this->raceEventData;
?>

<div class="row">
<!-- List of portal news -->
<div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 m-t-10">
    <div class="block block-default block-ui-bordered block-list">
        <div class="block-header">
            <div class="block-title text-uppercase text-bold">
                <?= $this->t('Новости портала') ?>
            </div>
        </div>
        <div class="block-body">
            <?php if (count($this->postData) > 0) { ?>
                <?php
                $filter = new Zend_Filter();
                $filter->addFilter(new Zend_Filter_StripTags())
                    ->addFilter(new Zend_Filter_StringTrim());
                $bbcode = Zend_Markup::factory('Bbcode');
                ?>
                <?php foreach ($this->postData as $post) : ?>
                    <?php
                    // check access and generate link for default/post/id
                    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'post', 'id')) {
                        $defaultPostIDUrl = $this->url(
                            array('module' => 'default', 'controller' => 'post', 'action' => 'id',
                                'postID' => $this->escape($post['ID'])), 'defaultPostID'
                        );
                    } else {
                        $defaultPostIDUrl = '#';
                    }
                    ?>

                    <?php
                    //TODO: Add method for comment model for countiong comments

                    $query = Doctrine_Query::create()
                        ->from('Default_Model_Comment c')
                        ->leftJoin('c.User u')
                        ->where('c.PostID = ?', $post['ID']);
                    $commentResult = $query->fetchArray();

                    $commentsСount = count($commentResult);
                    ?>
                    <div class="block block-default block-ui-bordered m-b-5">
                        <?php
                        echo $this->BlockConfigMenu($this->t("Контент"))->postMenu(
                            $this->escape($post['ID'])
                        );
                        ?>
                        <div class="block-body clearfix">
                            <?php if ($post['ImageUrl']) : ?>
                                <a class="pull-left m-r-10" href="<?= $defaultPostIDUrl; ?>">
                                    <div class="img-wrapper-100-100">
                                        <img class="media-object img-thumbnail img-responsive img-size-100"
                                             src="<?= $post['ImageUrl']; ?>" alt="<?= $post['Name']; ?>"/>
                                    </div>
                                </a>
                            <?php endif; ?>
                            <h4 class="block-title m-b-10">
                                <a href="<?= $defaultPostIDUrl; ?>">
                                    <?= $this->truncate($this->escape($post['Name']))->toLength(100); ?>
                                </a>
                            </h4>
                            <?php
                            if ($post['Preview'] != '') {
                                echo $this->escape($post['Preview']);
                            } else {
                                echo $bbcode->render(
                                    (string)($this->truncate($this->escape($post['Text']))->toLength(250))
                                );
                            }
                            ?>
                        </div>
                        <div class="block-footer clearfix">
                            <div class="pull-left m-r-15 tooltip-field"
                                 data-title="<?= $this->t('Просмотров'); ?>" data-placement="bottom">
                                <i class="fa fa-eye fa-lg"></i>
                                <?= $this->escape($post['Views']); ?>
                            </div>
                            <div class="pull-left m-r-15 tooltip-field"
                                 data-title="<?= $this->t('Комментарии'); ?>" data-placement="bottom">
                                <i class="fa fa-comments-o fa-lg"></i>
                                <?= $commentsСount ?>
                            </div>
                            <div class="pull-right tooltip-field"
                                 data-title="<?= $this->t('Читать дальше'); ?>" data-placement="bottom">
                                <a href="<?= $defaultPostIDUrl ?>"
                                   class="block-content-button-more">
                                    <i class="fa fa-arrow-right fa-lg"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php } else { ?>
                <?php
                /*
                 * TODO: Сделать хелпер для вывода ошибок.
                 */
                ?>
                <div class="alert alert-error">
                    <?= $this->t('Ошибка!'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<!-- ./ List of portal news -->
<!-- Next Races  -->
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 m-t-10">
    <div class="block block-default block-ui-bordered block-table">
        <div class="block-header">
            <div class="block-title text-uppercase text-bold" style="border:0; padding:0;">
                <?= $this->t('Ближайшие события') ?>
            </div>
        </div>
        <div class="block-body">
            <?php if ($raceEvents) { ?>
                <table class="table table-hover">
                    <tbody>
                    <?php foreach ($raceEvents as $raceEvent): ?>
                        <?php
                        // check access and generate link for admin/race-event/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'race-event', 'id')) {
                            $defaultRaceEventIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'race-event', 'action' => 'id',
                                    'raceEventID' => $this->escape($raceEvent['ID'])), 'defaultRaceEventID'
                            );
                        } else {
                            $defaultRaceEventIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/championship/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'championship', 'id')) {
                            $adminChampionshipIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'championship', 'action' => 'id',
                                    'championshipID' => $this->escape($raceEvent['Championship']['ID'])), 'defaultChampionshipID'
                            );
                        } else {
                            $adminChampionshipIDUrl = '#';
                        }
                        ?>
                        <tr>
                            <td>
                                <span class="text-bold">
                                    <a href="<?= $defaultRaceEventIDUrl; ?>"><?= $raceEvent['Name']; ?></a>
                                </span>
                                <br/>
                                <small>
                                    <a class="text-black" href="<?= $adminChampionshipIDUrl; ?>">
                                        <?= $raceEvent['Championship']['Name']; ?>
                                    </a>
                                </small>
                            </td>
                            <td class="text-italic text-right">
                                <small><time><?= $raceEvent['DateStart']; ?></time></small>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <?php
                /*
                * TODO: Сделать хелпер для вывода ошибок.
                */
                ?>
                <div class="alert alert-info">
                    <?= $this->t('В ближайшее время события отсутствуют.'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<!-- ./ Next Races -->
<!-- List of leagues -->
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 m-t-10">
    <div class="block block-default block-ui-bordered block-media-list">
        <div class="block-header">
            <div class="block-title text-uppercase text-bold">
                <?= $this->t('Лиги портала') ?>
            </div>
        </div>
        <div class="block-body">
            <ul class="media-list">
                <?php foreach ($this->leagueData as $league): ?>
                    <?php $defaultLeagueIDAllURL = $this->url(
                        array('module' => 'default', 'controller' => 'league', 'action' => 'id',
                            'leagueID' => $this->escape($league['ID'])), 'defaultLeagueID', true
                    ); ?>
                    <li class="media">
                        <a class="pull-left" href="<?= $defaultLeagueIDAllURL; ?>">
                            <img class="media-object img-thumbnail img-responsive img-size-100"
                                 src="<?= $league['LogoUrl']; ?>" alt="<?= $league['Name']; ?>">
                        </a>

                        <div class="media-body">
                            <h4 class="media-heading">
                                <a href="<?= $defaultLeagueIDAllURL; ?>"><?= $league['Name']; ?></a>
                            </h4>
                            <?= $league['Description']; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<!-- ./ List of leagues -->
<!-- RSS news from F1news.ru -->
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 m-t-10">
    <div class="block block-default block-ui-bordered block-media-list block-media-list-rss">
        <div class="block-header">
            <div class="block-title text-uppercase text-bold">
                <?= $this->t('Новости из мира автоспорта') ?>
            </div>
        </div>
        <div class="block-body">
            <ul class="media-list">
                <?php for ($i = 1; $i < $this->rss_count; $i++) : ?>
                    <?php $rss_url = $this->rss_element[$this->rss_index["LINK"][$i + 1]]["value"]; ?>
                    <li class="media">
                        <div class="media-body">
                            <h4 class="media-heading">
                                <a href="<?= $rss_url; ?>" target="_blank">
                                    <?= $this->rss_element[$this->rss_index["TITLE"][$i + 1]]["value"]; ?>
                                </a>
                            </h4>
                            <?= $this->rss_element[$this->rss_index["DESCRIPTION"][$i]]["value"]; ?>
                        </div>
                    </li>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
</div>
<!-- ./ RSS news from F1news.ru -->
</div>
<!-- Slider with partners -->
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 m-t-10">
        <div class="block block-default block-ui-bordered">
            <div class="block-header">
                <div class="block-title text-uppercase text-bold">
                    <?= $this->t('Друзья и Партнеры'); ?>
                </div>
            </div>
            <div class="block-body">
                <div class="carousel slide media-carousel" id="our-friends-carousel" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="item  active">
                            <div class="row">
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    <a class="thumbnail" href="http://pit-line.com.ua/" target="_blank">
                                        <img alt=""
                                             src="/data-content/ui/icons/partners/pit-line-com-ua-logo-250.png"
                                             class="img-responsive">
                                    </a>
                                </div>
                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    <a class="thumbnail" href="http://i-src.ru/" target="_blank">
                                        <img
                                            alt="<?= $this->t(''); ?>"
                                            src="/data-content/ui/icons/partners/i-src-ru-logo-250.png"
                                            class="img-responsive">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a data-slide="prev" href="#our-friends-carousel" class="left carousel-control">
                        <i class="fa fa-chevron-left"></i>
                    </a>
                    <a data-slide="next" href="#our-friends-carousel" class="right carousel-control">
                        <i class="fa fa-chevron-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ./ Slider with partners -->