<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="block">
			<div class="hero-unit" style="text-align:center; font-family:'Faster One'; padding:25px 0;">
				<span style="font-size:50px">Online-<span style="color:#C41D1D">Racing</span>.Net</span>
				<p><span style="color:#C41D1D">sim</span>-racing <span style="color:#C41D1D">portal</span></p>
			</div>
		</div>
	</div>
</div>
<div class="row m-t-15">
	<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
		<div class="block block-ui-bordered">
			<div class="block-header">
				<div class="block-title">
					<?php echo $this->translate('Новости нашего портала') ?>
				</div>
			</div>
			<div class="block-body">
				<?php if (count($this->posts_data) > 0) : ?>
					<?php
					$filter = new Zend_Filter();
					$filter->addFilter(new Zend_Filter_StripTags())
							->addFilter(new Zend_Filter_StringTrim());
					$bbcode = Zend_Markup::factory('Bbcode');
					?>
					<ul class="media-list">
						<?php foreach ($this->posts_data as $post) : ?>
							<?php $post_id_url = $this->url(array('module' => 'default', 'controller' => 'post', 'action' => 'id', 'post_id' => $this->escape($post->id)), 'postId', true); ?>
							<li class="media">
								<?php if (!$post->image == "") { ?>
									<a class="pull-left" href="<?php echo $post_id_url; ?>">
										<img class="media-object img-thumbnail img-responsive img-size-150" src="<?php echo $post->image; ?>" alt="<?php echo $post->title; ?>">
									</a>

								<?php } ?>
								<div class="media-body">
									<h4 class="media-heading"><a href="<?php echo $post_id_url; ?>"><?php echo $this->truncate($post->title)->toLength(100); ?></a></h4>
									<?php
									if ($post->annotation != '') {
										echo $this->escape($post->annotation);
									} else {
										echo $bbcode->render((string) ($this->truncate($this->escape($post->text))->toLength(250)));
									}
									?>
								</div>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
		<div class="block block-ui-bordered">
			<div class="block-header">
				<div class="block-title">
					<?php echo $this->translate('Наши лиги') ?>
				</div>
			</div>
			<div class="block-body">
				<ul class="media-list">
					<?php foreach ($this->leagues_data as $league): ?>
						<?php $league_url = $this->url(array('module' => 'default', 'controller' => 'league', 'action' => 'id', 'league_id' => $this->escape($league->id)), 'leagueIdAll', true); ?>
						<li class="media">
							<a class="pull-left" href="<?php echo $league_url; ?>">
								<img class="media-object img-thumbnail img-responsive img-size-100" src="<?php echo $league->url_logo; ?>" alt="<?php echo $league->name; ?>">
							</a>
							<div class="media-body">
								<h4 class="media-heading"><a href="<?php echo $league_url; ?>"><?php echo $league->name; ?></a></h4>
								<?php //echo $league->description; ?>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="block-item m-t-15">
    <div class="section-title m-b-15"><?php echo $this->translate('Новости нашего портала') ?>:</div>
	<?php if (count($this->posts_data) != 0) { ?>
		<div id="home-posts-last">
			<?php
			$filter = new Zend_Filter();
			$filter->addFilter(new Zend_Filter_StripTags())
					->addFilter(new Zend_Filter_StringTrim());
			$bbcode = Zend_Markup::factory('Bbcode');

			foreach ($this->posts_data as $post) :
				?>
				<h6><a href="#"><?php echo $this->truncate($post->title)->toLength(100); ?></a></h6>
				<div>
					<?php if (!$post->image == "") { ?>
						<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
							<img src='<?php echo $post->image; ?>' width="150px" height="100px" class='img-thumbnail img-responsive'>
						</div>
					<?php } ?>
					<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
						<p>
							<?php
							if ($post->annotation != '') {
								echo $this->escape($post->annotation);
							} else {
								echo $bbcode->render((string) ($this->truncate($this->escape($post->text))->toLength(250)));
							}
							?>
						</p>
					</div>
					<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'post', 'action' => 'id', 'post_id' => $this->escape($post->id)), 'postId', true) ?>" class="btn btn-sm btn-primary pull-right" style="color:#fff;">
						<?php echo $this->translate("Подробнее...") ?>
					</a>
				</div>
			<?php endforeach; ?>
		</div>
		<script type="text/javascript">
			$(document).ready(function() {
				$("#home-posts-last").accordion({header: "h6"});
			});
		</script>
	<?php } else {
		?>
		<div class="alert alert-warning alert-block">
			<h4><?php echo $this->translate('Ошибка!'); ?></h4>
			<?php echo $this->translate('Контент на сайте не найден.'); ?>
		</div>
	<?php } ?>
</div>
<div class="block-item m-t-15">
    <div class="section-title"><?php echo $this->translate('Новости из мира Формулы-1') ?>:</div>
    <div id="rss_block">
		<?php for ($i = 1; $i < $this->rss_count; $i++) { ?>
			<h6 class="rss_title">
				<a href="#"><?php echo $this->rss_element[$this->rss_index["TITLE"][$i + 1]]["value"]; ?></a>
			</h6>
			<div class="rss_description">
				<p class="rss_text">
					<?php echo $this->rss_element[$this->rss_index["DESCRIPTION"][$i]]["value"] ?>
				</p>
				<a class="rss_more btn btn-sm btn-primary" href="<?php echo $this->rss_element[$this->rss_index["LINK"][$i + 1]]["value"]; ?>" target="_BLINK"><?php echo $this->translate("Подробнее на F1-News.ru") ?></a>
			</div>
		<?php } ?>
    </div>
    <script type="text/javascript">
		$(document).ready(function() {
			$("#rss_block").accordion({header: "h6"});
		});
    </script>
</div>