<div id="event_add_page" class="page">
    <div class="page_title"><?php echo $this->translate('Произошла ошибка'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class="alert alert-warning alert-block">
            <!--<button type="button" class="close" data-dismiss="alert">×</button>-->
            <h2><?php echo $this->translate('Ошибка!'); ?></h2>
                <dl>
                    <dd><h4><?php echo $this->message; ?></h4></dd>
                </dl>
                <?php if (isset($this->exception)): ?>
                    <h3><?php echo $this->translate('Информация об ошибке'); ?>:</h3>
                    <dl>
                        <dd><b>Message:</b> <?php echo $this->exception->getMessage() ?></dd>
                    </dl>
                    <h3>Stack trace:</h3>
                    <pre><?php echo $this->exception->getTraceAsString() ?>
                    </pre>
                    <h3>Request Parameters:</h3>
                    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
                    </pre>
                <?php endif ?>
        </div>
    </div>
</div>