<!-- start user_map block -->
<div class="col-lg-12 col-md-4 col-sm-6 col-xs-12">
    <div id="online-drivers" class="block block-ui-bordered block-sidebar m-b-10">
        <div class="block-header">
            <div class="block-title">
                <i class="fa fa-user fa-lg"></i> <?php echo $this->translate("Паддок") ?>
            </div>
        </div>
        <div class="block-body">
            <i><?php echo $this->translate('Cейчас в паддоке'); ?>:</i>
            <span>
                <?php

                $date = new Zend_Date();
                $date->sub(7, Zend_Date::MINUTE);
                $date = $date->toString('yyyy-MM-dd HH:mm:ss');

                $query = Doctrine_Query::create()
                    ->from('Default_Model_User u')
                    ->leftJoin('u.UserRole ur')
                    ->leftJoin('ur.Role r')
                    ->where('u.DateLastActivity >= ?', $date);

                $userResult = $query->fetchArray();

                if ($userResult) {
                    $userCount = count($userResult);
                } else {
                    $userCount = '0';
                }
                ?>
                <strong><?php echo $userCount; ?></strong> <?php echo $this->translate('гонщик(-а, -ов)'); ?>
            </span>

            <div class="row m-t-10">
                <?php
                if ($userResult) {
                    foreach ($userResult as $user): ?>

                        <?php
                        // check access and generate link for default/user/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                            $defaultUserIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                    'userID' => $this->escape($user['ID'])), 'defaultUserID'
                            );
                        } else {
                            $defaultUserIDUrl = '#';
                        }
                        ?>
                        <?php
                        if ($this->getUser()->getUserStatus($user['DateLastActivity']) == USER_STATUS_ONLINE) {
                            $userStatusClass = 'user-online';
                        } else {
                            $userStatusClass = 'user-offline';
                        }
                        ?>

                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div class="block block-user m-b-10">
                                <div
                                    class="img-wrapper-50-50 overflow-hide img-circle center-block user-avatar tooltip-field <?php echo $userStatusClass; ?>"
                                    data-title="<?php echo $user['Login']; ?>" data-placement="bottom">
                                    <a target="_blank" href="<?php echo $defaultUserIDUrl; ?>">
                                        <?php echo $this->getUser()->getUserAvatar($user['ID'], $user['AvatarType'], 'media-object img-responsive img-size-50', 50); ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php
                    endforeach;
                }
                ?>
            </div>
        </div>
    </div>
</div>
<!-- end user_map block -->