<!-- start user_map block -->
<div class="col-lg-12 col-md-4 col-sm-6 col-xs-12">
	<div id="online-drivers" class="block block-ui-bordered block-sidebar m-b-10">
		<div class="block-header">
			<div class="block-title">
				<i class="fa fa-user fa-lg"></i> <?php echo $this->translate("Паддок") ?>
			</div>
		</div>
		<div class="block-body">
			<i><?php echo $this->translate('Cейчас в паддоке'); ?>:</i>
			<span>
				<?php
				$user_db = new Application_Model_DbTable_User();

				$date = new Zend_Date();
				$date->sub(7, Zend_Date::MINUTE);
				$date = $date->toString('yyyy-MM-dd HH:mm:ss');

				$user_data = $user_db->getAll(array('date_last_activity' => array('value' => $date, 'sign' => '>=')));

				if ($user_data) {
					$user_count = count($user_data);
				} else {
					$user_count = '0';
				}
				?>
				<strong><?php echo $user_count; ?></strong> <?php echo $this->translate('гонщик(-а, -ов)'); ?>
			</span>
			<div class="row m-t-10">
				<?php
				if ($user_data) {
					foreach ($user_data as $user):
						$default_user_id_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'id', 'user_id' => $user->id), 'defaultUserId', true);

						if ($this->getUserStatus($user->date_last_activity) == 'online') {
							$user_status_class = 'user-online';
						} else {
							$user_status_class = 'user-offline';
						}
						?>

						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
							<div class="block block-user m-b-10">
								<div class="img-wrapper-50-50 overflow-hide img-circle center-block user-avatar tooltip-field <?php echo $user_status_class; ?>" data-title="<?php echo $user->login; ?>" data-placement="bottom">
									<a href="<?php echo $default_user_id_url; ?>" target="_blank"><?php echo $this->getUserAvatar($user->id, $user->avatar_type, 'media-object img-responsive img-size-50', 50); ?></a>
								</div>
							</div>
						</div>
						<?php
					endforeach;
				}
				?>
			</div>
		</div>
	</div>
</div>
<!-- end user_map block -->