<!-- start calendar block -->
<div class="hidden-xs hidden-sm col-md-4 col-lg-12">
    <div id="calendar" class="block block-sidebar block-ui-bordered  m-b-10">
        <div class="block-header">
            <div class="block-title">
                <i class="fa fa-clock-o fa-lg"></i> <?= $this->translate("LiveRacers") ?>
            </div>
        </div>
        <div class="block-body">
<!--            <p>-->
<!--                <a target="_blank" href="http://online-racing-net.liveracers.info/Live">-->
<!--                    --><?php ////echo $this->translate('Наши сервера'); ?>
<!--                </a>-->
<!--            </p>-->

            <div id="lr-servers" orientation="horizontal"></div>
        </div>
    </div>
</div>
<!-- end calendar block -->