<?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'content-type', 'add')) : ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="clearfix m-b-10">
                <?php
                $adminContentTypeAddUrl = $this->url(
                    array('module' => 'admin', 'controller' => 'content-type', 'action' => 'add'), 'default'
                );
                ?>
                <a href="<?php echo $adminContentTypeAddUrl; ?>" class="btn btn-success pull-right ">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Добавить тип контента'); ?>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->contentTypeData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="content-type-id">
                                <span>ID</span>
                            </th>
                            <th class="content-type-name">
                                <span><?php echo $this->translate('Название'); ?></span>
                            </th>
                            <th class="content-type-description">
                                <span><?php echo $this->translate('Описание'); ?></span>
                            </th>
                            <th class="content-type-action">
                                <span><?php echo $this->translate('Действие'); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->contentTypeData as $contentType): ?>
                            <?php
                            if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'country', 'id')) {
                                $adminContentTypeIdUrl = $this->url(
                                    array('module' => 'admin', 'controller' => 'content-type', 'action' => 'id',
                                        'contentTypeID' => $this->escape($contentType['ID'])), 'adminContentTypeID'
                                );
                            } else {
                                $adminContentTypeIdUrl = '#';
                            }
                            ?>
                            <tr>
                                <td class="content-type-id">
										<span>
                                            <a href="<?php echo $adminContentTypeIdUrl; ?>">
                                                <?php echo $this->escape($contentType['ID']) ?>
                                            </a>
                                        </span>
                                </td>
                                <td class="content-type-name">
										<span>
                                            <a href="<?php echo $adminContentTypeIdUrl; ?>">
                                                <?php echo $this->escape($contentType['Name']) ?>
                                            </a>
                                        </span>
                                </td>
                                <td class="content-type-description">
                                    <span>
                                        <?php echo $this->RenderContentTypeText($contentType['Description'], 'full_html'); ?>
                                    </span>
                                </td>
                                <td class="content-type-action">
										<span>
											<?php
                                            echo $this->BlockConfigMenu($this->translate("Тип контента"), false)->contentTypeMenu(
                                                $this->escape($contentType['ID']), true
                                            );
                                            ?>
										</span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="pull-right">
                        <?php echo $this->paginationControl(
                            $this->contentTypeData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>