<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/content-type/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'content-type', 'add')) : ?>
                    <?php
                    $adminContentTypeAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'content-type', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminContentTypeAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->translate('Добавить тип контента'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="content-type-id">
                        <span>ID</span>
                    </th>
                    <th class="content-type-name">
                        <span><?= $this->translate('Название'); ?></span>
                    </th>
                    <th class="content-type-description">
                        <span><?= $this->translate('Описание'); ?></span>
                    </th>
                    <th class="content-type-action">
                        <span><?= $this->translate('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->contentTypeData) : ?>
                    <?php foreach ($this->contentTypeData as $contentType): ?>
                        <?php
                        // check access and generate link for admin/content-type/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'content-type', 'id')) {
                            $adminContentTypeIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'content-type', 'action' => 'id',
                                    'contentTypeID' => $this->escape($contentType['ID'])), 'adminContentTypeID'
                            );
                        } else {
                            $adminContentTypeIdUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="content-type-id">
                                <span>
                                    <a href="<?= $adminContentTypeIdUrl; ?>">
                                        <?= $this->escape($contentType['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="content-type-name">
                                <span>
                                    <a href="<?= $adminContentTypeIdUrl; ?>">
                                        <?= $this->escape($contentType['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="content-type-description">
                                <span>
                                    <?= $this->RenderContentTypeText($contentType['Description'], 'full_html'); ?>
                                </span>
                            </td>
                            <td class="content-type-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->translate("Тип контента"), false)
                                        ->contentTypeMenu($this->escape($contentType['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->contentTypeData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->contentTypeData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>