<?php if ($this->contentTypeData) { ?>
    <div class="m-b-10">
        <?php echo $this->contentTypeDeleteForm; ?>
        <hr/>
    </div>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?php echo $this->escape($this->contentTypeData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?php echo $this->RenderContentTypeText($this->contentTypeData['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php } ?>