<div id="Hot_Laps_F1">
    <div class="Marquee">
        <iframe src="http://83.242.255.227:27012/rFactorHotlaps/Marquee.htm" name="standings" width="370" height="25" scrolling="no" id="standings" frameborder="0" style="background:none;"></iframe>
    </div>
    <div class="hot_laps_links">
        <span style="color:#fff">|</span>
        <a href="http://83.242.255.227:27012/rFactorLive" target="_BLINK"><?php echo $this->translate('Трансляция')?></a>
        <a href="http://83.242.255.227:27012/rFactorHotlaps?max=25" target="_BLINK"><?php echo $this->translate('Рекорды')?></a>
    </div>
</div>
