<div id="box_main_menu">
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <?php
            $partial = array('menu_layout/main_menu.phtml', 'default');
            $this->navigation()->menu($this->main_menu)->setPartial($partial);
            echo $this->navigation()->menu()->render();
            ?>
            <form class="navbar-search pull-right">
                <input type="text" class="search-query" placeholder="<?php echo $this->translate('Поиск'); ?>">
            </form>
        </div>
    </div>
</div>