<div id="admin_toolbar">
    <ul id="admin_menu">
        <li class="home"><a href="<?php echo $this->baseUrl(''); ?>">Home</a></li>
        <li class="expanded">
            <a href="<?php echo $this->baseUrl('admin/articles'); ?>">Контент</a>
            <ul class="menu">
                <li><a href="<?php echo $this->baseUrl('admin/articles'); ?>">Просмотр</a></li>
                <li><a href="<?php echo $this->baseUrl('article/add'); ?>">Добавить</a></li>
            </ul>
        </li>
        <li class="expanded">
            <a href="<?php echo $this->baseUrl('admin/users'); ?>">Пользователи</a>
            <ul class="menu">
                <li><a href="<?php echo $this->baseUrl('admin/users'); ?>">Просмотр</a></li>
                <li><a href="<?php echo $this->baseUrl('user/index'); ?>">Добавить флаг</a></li>
            </ul>
        </li>
        <li class="name"><a href="<?php echo $this->baseUrl('admin'); ?>">Online-Racing Master</a></li>
    </ul>
</div>