<div class="web_counters">
	<?php
	if ($this->wc_live_internet_block) {
		echo $this->render("default_layout/footer/user_counters/wc_live_internet_block.phtml");
	}
	?>
	<?php
	if ($this->wc_rambler100_block) {
		echo $this->render("default_layout/footer/user_counters/wc_rambler100_block.phtml");
	}
	?>
	<?php
	if ($this->wc_mail_ru_block) {
		echo $this->render("default_layout/footer/user_counters/wc_mail_ru_block.phtml");
	}
	?>
	<?php
	if ($this->wc_yandex_block) {
		echo $this->render("default_layout/footer/user_counters/wc_yandex_block.phtml");
	}
	?>
</div>