<ul class="slide-out-tabs">
    <li class="slide-out-tab liveracers">
		<div class="slide-out-tab-icon">
			<img src="<?php echo $this->baseUrl('data-content/ui/icons/life-racers-50.png'); ?>" />
		</div>
		<div class="slide-out-tab-body">
			<h4>LiveRacers</h4>
			<div class="div_hr"></div>
			<p>
				<a target="_blank" href="http://online-racing-net.liveracers.info/Live">Online-Racing Live</a>
			</p>
			<div id="lr-servers" orientation="horizontal" ></div>
        </div>
    </li>
    <li class="slide-out-tab teamspeak">
		<div class="slide-out-tab-icon">
			<img src="<?php echo $this->baseUrl('data-content/ui/icons/team-speak-50.png'); ?>" />
		</div>
		<div class="slide-out-tab-body">
			<h4>TeamSpeak Server</h4>
			<div class="div_hr"></div>
			<p>
				<strong>IP Сервера : </strong>85.112.55.36:9987<br/>
				<strong>Пароль: </strong><i>обратится к администраторам в личку.</i><br/>
			</p>
			<p>
				За подробной информацией обращатесь:
				<br/>
				<img src="<?php echo $this->baseUrl('data-content/ui/icons/skype-20.png'); ?>"><strong>Skype: </strong><u>dark_diesel</u>
			</p>
        </div>
    </li>
    <li class="slide-out-tab question">
		<div class="slide-out-tab-icon">
			<img src="<?php echo $this->baseUrl('data-content/ui/icons/question-50.png'); ?>" />
		</div>
		<div class="slide-out-tab-body">
			<h4>Помощь</h4>
			<div class="div_hr"></div>
			<p>
				При возникших вопросах обращайтесь по следущим контактам:<br/><br/>
				<img src="<?php echo $this->baseUrl('data-content/ui/icons/skype-20.png'); ?>">Skype: dark_diesel
				<br/><br/>
				Или пишите в чат сайта.
			</p>
		</div>
	</li>
</ul>