<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/post/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'post', 'add')) : ?>
                    <?php
                    $adminPostAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'post', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminPostAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->translate('Добавить контент'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="post-id">
                        <span>ID</span>
                    </th>
                    <th class="post-publish">
                        <span><?= $this->translate('Опубликована'); ?></span>
                    </th>
                    <th class="post-name">
                        <span><?= $this->translate('Название'); ?></span>
                    </th>
                    <th class="post-user">
                        <span><?= $this->translate('Автор'); ?></span>
                    </th>
                    <th class="post-post-category">
                        <span><?= $this->translate('Категория поста'); ?></span>
                    </th>
                    <th class="post-action">
                        <span><?= $this->translate('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->postData) : ?>
                    <?php foreach ($this->postData as $post): ?>

                        <?php
                        // check access and generate link for default/post/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'post', 'id')) {
                            $defaultPostIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'post', 'action' => 'id',
                                    'postID' => $this->escape($post['ID'])), 'defaultPostID'
                            );
                        } else {
                            $defaultPostIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for default/user/id
                        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                            $defaultUserIDUrl = $this->url(
                                array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                    'userID' => $this->escape($post['User']['ID'])), 'defaultUserID'
                            );
                        } else {
                            $defaultUserIDUrl = '#';
                        }
                        ?>

                        <?php
                        // check access and generate link for admin/post-category/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'post-category', 'id')) {
                            $adminPostCategoryIdUrl = $this->url(
                                array('module' => 'default', 'controller' => 'post-category', 'action' => 'id',
                                    'postCategoryID' => $this->escape($post['PostCategory']['ID'])), 'adminPostCategoryID'
                            );
                        } else {
                            $adminPostCategoryIdUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="post-id">
                                <span>
                                    <a href="<?= $defaultPostIDUrl; ?>">
                                        <?= $this->escape($post['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="post-publish text-center">
                                <span>
                                    <?php if ($this->escape($post['Publish'])) { ?>
                                        <span class='label label-success'><i
                                                class="fa fa-check fa-lg"></i></i></span>
                                    <?php } else { ?>
                                        <span class='label label-danger'><i
                                                class="fa fa-times fa-lg"></i></span>
                                    <?php } ?>
                                </span>
                            </td>
                            <td class="post-name">
                                <span>
                                    <a href="<?= $defaultPostIDUrl; ?>">
                                        <?= $this->escape($post['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="post-user">
                                <span>
                                    <a class="tooltip-field"
                                       title="<?= $this->escape($post['User']['NickName']) ?>"
                                       target="blank" href="<?= $defaultUserIDUrl; ?>">
                                        <?= $this->escape($post['User']['LastName']) . ' ' . $this->escape($post['User']['FirstName']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="post-post-category">
                                <span>
                                    <a target="blank" href="<?= $adminPostCategoryIdUrl; ?>">
                                        <?= $this->escape($post['PostCategory']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="post-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->translate("Пост"), false)
                                        ->postMenu($this->escape($post['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->postData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->postData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>