<?php if ($this->postData) { ?>
    <div class="m-b-10">
        <?= $this->postDeleteForm; ?>
        <hr/>
    </div>
    <?php
    // check access and generate link for user
    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
        $defaultUserIDUrl = $this->url(
            array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                'userID' => $this->escape($this->postData['User']['ID'])), 'defaultUserID'
        );
    } else {
        $defaultUserIDUrl = '#';
    }
    ?>

    <?php
    // check access and generate link for post-category
    if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'post-category', 'id')) {
        $adminPostCategoryIdUrl = $this->url(
            array('module' => 'default', 'controller' => 'post-category', 'action' => 'id',
                'postCategoryID' => $this->escape($this->postData['PostCategory']['ID'])), 'adminPostCategoryID'
        );
    } else {
        $adminPostCategoryIdUrl = '#';
    }
    ?>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->postData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Опубликована'); ?></span>
                    </td>
                    <td>
                        <span>
                            <?php if ($this->escape($this->postData['Publish'])) { ?>
                                <span class='label label-success'><i
                                        class="fa fa-check fa-lg"></i></i></span>
                            <?php } else { ?>
                                <span class='label label-danger'><i
                                        class="fa fa-times fa-lg"></i></span>
                            <?php } ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Картинка поста'); ?></span>
                    </td>
                    <td>
                        <span>
                            <img
                                src="<?= $this->baseUrl($this->escape($this->postData['ImageUrl'])); ?>">
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Автор'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a target="_blank" href="<?= $defaultUserIDUrl; ?>">
                            <?= $this->escape($this->postData['User']['NickName']); ?>
                        </a>
                    </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Категория поста'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a target="blank" href="<?= $adminPostCategoryIdUrl; ?>">
                            <?= $this->escape($this->postData['PostCategory']['Name']) ?>
                        </a>
                    </span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->translate('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->translate('Пост'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->translate('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->postData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->postData['DateCreate']) != $this->escape($this->postData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->translate('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->postData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>