<?php
$post = $this->postData;
?>

<?php if ($post) { ?>
    <div class="m-b-10">
        <?= $this->postDeleteForm; ?>
        <hr/>
    </div>
    <?php
    // check access and generate link for /default/user/id
    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
        $defaultUserIDUrl = $this->url(
            array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                'userID' => $this->escape($post['User']['ID'])), 'defaultUserID'
        );
    } else {
        $defaultUserIDUrl = '#';
    }
    ?>

    <?php
    // check access and generate link for admin/post-category/id
    if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'post-category', 'id')) {
        $adminPostCategoryIDUrl = $this->url(
            array('module' => 'admin', 'controller' => 'post-category', 'action' => 'id',
                'postCategoryID' => $this->escape($post['PostCategory']['ID'])), 'adminPostCategoryID'
        );
    } else {
        $adminPostCategoryIDUrl = '#';
    }
    ?>

    <?php
    // check access and generate link for admin/content-type/id
    if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'content-type', 'id')) {
        $adminContentTypeIDUrl = $this->url(
            array('module' => 'admin', 'controller' => 'content-type', 'action' => 'id',
                'contentTypeID' => $this->escape($post['ContentType']['ID'])), 'adminContentTypeID'
        );
    } else {
        $adminContentTypeIDUrl = '#';
    }
    ?>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr class="post-name">
                    <td class="text-bold">
                        <span><?= $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($post['Name']); ?></span>
                    </td>
                </tr>
                <tr class="post-publish">
                    <td class="text-bold">
                        <span><?= $this->translate('Опубликована'); ?></span>
                    </td>
                    <td>
                        <span>
                            <?php if ($this->escape($post['Publish'])) { ?>
                                <span class='label label-success'><i
                                        class="fa fa-check fa-lg"></i></i></span>
                            <?php } else { ?>
                                <span class='label label-danger'><i
                                        class="fa fa-times fa-lg"></i></span>
                            <?php } ?>
                        </span>
                    </td>
                </tr>
                <tr class="post-image">
                    <td class="text-bold">
                        <span><?= $this->translate('Картинка поста'); ?></span>
                    </td>
                    <td>
                        <span>
                            <?php if ($this->escape($post['ImageUrl'])): ?>
                                <img src="<?= $this->baseUrl($this->escape($post['ImageUrl'])); ?>" />
                            <?php endif; ?>
                        </span>
                    </td>
                </tr>
                <tr class="post-user">
                    <td class="text-bold">
                        <span><?= $this->translate('Автор'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a target="_blank" href="<?= $defaultUserIDUrl; ?>">
                            <?= $this->escape($post['User']['NickName']); ?>
                        </a>
                    </span>
                    </td>
                </tr>
                <tr class="post-category">
                    <td class="text-bold">
                        <span><?= $this->translate('Категория поста'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a target="blank" href="<?= $adminPostCategoryIDUrl; ?>">
                            <?= $this->escape($post['PostCategory']['Name']) ?>
                        </a>
                    </span>
                    </td>
                </tr>
                <tr class="post-content-type">
                    <td class="text-bold">
                        <span><?= $this->translate('Тип контента'); ?></span>
                    </td>
                    <td>
                    <span>
                        <a target="blank" href="<?= $adminContentTypeIDUrl; ?>">
                            <?= $this->escape($post['ContentType']['Name']) ?>
                        </a>
                    </span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->translate('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->translate('Пост'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->translate('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($post['DateCreate']); ?>
            </div>
            <?php if ($this->escape($post['DateCreate']) != $this->escape($post['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->translate('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($post['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php } ?>