<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>
<?php echo $this->form; ?>
<script>
	jQuery(document).ready(function() {
<?php echo $this->CKEditor()->setupBBCodeEditor('preview'); ?>

		var content_type = $("#content_type").find(':selected').text();

		switch (content_type) {
			case 'bbcode':
				bbcode();
				break;
			case 'text':
				text();
				break;
			case 'full html':
				full_html();
				break;
			default:
				text();
				break;
		}

		function bbcode() {
			var ck_editor_finder = CKEDITOR.instances['text'];
			if (ck_editor_finder) {
				ck_editor_finder.destroy();
			}
			<?php
			echo $this->CKEditor()->setupBBCodeEditor('text');
			echo $this->CKFinder()->setupCKEditor('text');
			?>
		}


		function full_html() {
			var ck_editor_finder = CKEDITOR.instances['text'];
			if (ck_editor_finder) {
				ck_editor_finder.destroy();
			}
			<?php
			echo $this->CKEditor()->SetupFullHtmlEditor('text');
			echo $this->CKFinder()->setupCKEditor('text');
			?>
		}

		function text() {
			var ck_editor_finder = CKEDITOR.instances['text'];
			if (ck_editor_finder) {
				ck_editor_finder.destroy();
			}
		}

		$(".page_content").on('change', "#content_type", function() {
			content_type = $(this).find(':selected').text();
			switch (content_type) {
				case 'bbcode':
					bbcode();
					break;
				case 'text':
					text();
					break;
				case 'full html':
					full_html();
					break;
				default:
					text();
					break;
			}
		});
	});
</script>