<?php $this->CKEditor()->init(); ?>
<?php $this->CKFinder()->init(); ?>

<?php echo $this->postEditForm; ?>

<script type="text/javascript">
    $(document).ready(function () {
        <?php echo $this->CKEditor()->setupBBCodeEditor('Preview'); ?>

        selectCKEditor();

        function bbcode() {
            var ck_editor_finder = CKEDITOR.instances['Text'];
            if (ck_editor_finder) {
                ck_editor_finder.destroy();
            }
            <?php
                echo $this->CKEditor()->setupBBCodeEditor('Text');
                echo $this->CKFinder()->setupCKEditor('Text');
            ?>
        }

        function full_html() {
            var ck_editor_finder = CKEDITOR.instances['Text'];
            if (ck_editor_finder) {
                ck_editor_finder.destroy();
            }
            <?php
                echo $this->CKEditor()->SetupFullHtmlEditor('Text');
                echo $this->CKFinder()->setupCKEditor('Text');
            ?>
        }

        function text() {
            var ck_editor_finder = CKEDITOR.instances['Text'];
            if (ck_editor_finder) {
                ck_editor_finder.destroy();
            }
        }

        $("#ContentTypeID").on('change', function () {
            selectCKEditor();
        });

        function selectCKEditor(){
            var content_type = $("#ContentTypeID").find(':selected').text();
            switch (content_type) {
                case 'bbcode':
                    bbcode();
                    break;
                case 'text':
                    text();
                    break;
                case 'full html':
                    full_html();
                    break;
                default:
                    text();
                    break;
            }
        }
    });
</script>