<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="block m-b-15">
            <div class="block-body">
                <object id="videoplayer11383" class="center-block" type="application/x-shockwave-flash" data="http://rfactor2.ru/championat/tv/player/player.swf" width="826" height="473"><param name="bgcolor" value="#ffffff" /><param name="allowFullScreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="movie" value="http://rfactor2.ru/championat/tv/player/player.swf" /><param name="flashvars" value="uid=videoplayer11383&amp;comment=Rush TV&amp;st=21AEZBUfcLSYIa3xao0uORnpdQVQQm5fp2U6hTd0nNrBGnZsN2DR2MbIT2NtYW5iIzv5f17mwcY2Nr3zm5ntKu0c9BMrn&amp;file=21AEEsAabexa5ne3GVTiW5J=jaiDejaD1ZJYT8SORb=J5ntsu0o9v0r7&amp;poster=82AE0d0qLkGcR6wFnQW5fp2UhTd0nNKBGnZsNDR2MbI2N2tYW5Izv5f1mwcYT2N3zm5ntu0c9BMrD" /></object>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-lg-offset-6">
        <div class="block center-block m-b-15">
            <div class="block-body">
                <iframe src="http://rfactor2.ru/championat/tv/player/rasp.html" width="100%" height="300px" scrolling="yes" frameborder="0"></iframe>
            </div>
        </div>
    </div>
</div>

