<div id="event_add_page" class="page">
    <div class="page_title"><?php echo $this->translate('Добавить событие'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <?php echo $this->form; ?>
        <script>
            jQuery(document).ready(function() {
                $("#date_event").datetimepicker({
                    showButtonPanel: true,
                    dateFormat: "yy-mm-dd",
                    showAnim: "clip",
                    showSecond: true,
                    timeFormat: 'HH:mm:ss',
                    stepHour: 1,
                    stepSecond: 10
                });
            });
        </script>
    </div>
</div>