<div id="event_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Событие') . ' :: ' . $this->escape($this->event->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="event_item">
                <table class="table table-striped table-bordered article_table">
                    <tbody>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Название'); ?></span></td>
                            <td><span><?php echo $this->escape($this->event->name); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Описание'); ?></span></td>
                            <td><span><?php echo $this->escape($this->event->description); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Дата события'); ?></span></td>
                            <td><span><?php echo $this->escape($this->event->date_event); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Ссылка на событие'); ?></span></td>
                            <td><span><a href="<?php echo $this->escape($this->event->url_event); ?>"><?php echo $this->translate('Ссылка'); ?></a></span></td>
                        </tr>
                    </tbody>
                </table>
                <?php
                $acl = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('Acl');

                $edit_access = $acl->checkUserAccess('event/edit');
                $delete_access = $acl->checkUserAccess('event/delete');

                if ($edit_access || $delete_access) {
                    ?>
                    <div class = "article_controls" >
                        <?php if ($edit_access) { ?>
                            <a href = "<?php echo $this->baseUrl('event/edit/' . $this->escape($this->event->id)) ?>" class = "btn btn-sm btn-primary content_edit"><?php echo $this->translate('Редактировать') ?></a>
                        <?php } ?>
                        <?php if ($delete_access) { ?>
                            <a href = "<?php echo $this->baseUrl('event/delete/' . $this->escape($this->event->id)) ?>" class = "btn btn-sm btn-primary content_delete"><?php echo $this->translate('Удалить') ?></a>
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="article_info">
                    <div class="event_name article_info_item"><span class="bold_text"><?php echo $this->translate('Вид контента') ?>: </span><?php echo $this->translate('Событие'); ?></div>
                    <div class="event_date_create article_info_item"><span class="bold_text"><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->event->date_create); ?></div>
                    <?php if ($this->escape($this->event->date_create) != $this->escape($this->event->date_edit)) { ?>
                        <div class="event_date_edit article_info_item"><span class="bold_text"><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($this->event->date_edit); ?></div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>