<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/role/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'role', 'add')) : ?>
                    <?php
                    $adminRoleAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'role', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminRoleAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->translate('Добавить роль'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="role-id">
                        <span>ID</span>
                    </th>
                    <th class="role-name">
                        <span><?= $this->translate('Название'); ?></span>
                    </th>
                    <th class="role-system-name">
                        <span><?= $this->translate('Системное имя'); ?></span>
                    </th>
                    <th class="role-parent-role">
                        <span><?= $this->translate('Родительская роль'); ?></span>
                    </th>
                    <th class="role-description">
                        <span><?= $this->translate('Описание'); ?></span>
                    </th>
                    <th class="role-action">
                        <span><?= $this->translate('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->roleData) : ?>
                    <?php foreach ($this->roleData as $role): ?>
                        <?php
                        // check access and generate link for admin/role/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'role', 'id')) {
                            $adminRoleIDUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'role', 'action' => 'id',
                                    'roleID' => $this->escape($role['ID'])), 'adminRoleID'
                            );
                            $adminParentRoleIDUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'role', 'action' => 'id',
                                    'roleID' => $this->escape($role['ParentRoleID'])), 'adminRoleID'
                            );
                        } else {
                            $adminRoleIDUrl = '#';
                            $adminParentRoleIDUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="role-id">
                                <span>
                                    <a href="<?= $adminRoleIDUrl; ?>">
                                        <?= $this->escape($role['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="role-name">
                                <span>
                                    <a href="<?= $adminRoleIDUrl; ?>">
                                        <?= $this->escape($role['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="role-system-name">
                                <span>
                                    <a href="<?= $adminRoleIDUrl; ?>">
                                        <?= $this->escape($role['SystemName']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="role-parent-role">
                                <span>
                                    <?php if ($this->escape($role['ParentRoleID'])) { ?>
                                        <a href="<?= $adminParentRoleIDUrl; ?>">
                                            <?= $this->escape($role['Role'][0]['Name']) ?>
                                        </a>
                                    <?php } ?>
                                </span>
                            </td>
                            <td class="role-description">
                                <span>
                                    <?= $this->RenderContentTypeText($role['Description'], 'full_html'); ?>
                                </span>
                            </td>
                            <td class="role-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->translate("Роль пользователя"), false)
                                        ->roleMenu($this->escape($role['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->roleData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->roleData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>