<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="clearfix m-b-10">
			<?php
			$role_id_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'add'), 'default', true);
			?>
			<a href="<?php echo $role_id_url; ?>" class="btn btn-success btn-xs pull-right "><i class="fa fa-plus"></i> <?php echo $this->translate('Добавить Роль'); ?></a>
		</div>
	</div>
</div>
<?php if ($this->roles_data) { ?>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<i class="fa fa-list"></i>
				</div>
				<div class="panel-body">
					<table class="table table-striped custab">
						<thead>
							<tr>
								<th class="role_id"><span>ID</span></th>
								<th class="role_name"><span><?php echo $this->translate('Название'); ?></span></th>
								<th class="role_parent"><span><?php echo $this->translate('Родительская роль'); ?></span></th>
								<th class="role_descr"><span><?php echo $this->translate('Описание'); ?></span></th>
								<th class="role_action"><span><?php echo $this->translate('Действие'); ?></span></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->roles_data as $role): ?>
								<?php
								$role_id_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'id', 'role_id' => $this->escape($role->id)), 'adminRoleId', true);
								$role_edit_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'edit', 'role_id' => $this->escape($role->id)), 'adminRoleAction', true);
								$role_delete_url = $this->url(array('module' => 'admin', 'controller' => 'role', 'action' => 'delete', 'role_id' => $this->escape($role->id)), 'adminRoleAction', true);
								?>
								<tr>
									<td class="role_id"><span><a href="<?php echo $role_id_url; ?>"><?php echo $this->escape($role->id) ?></a></span></td>
									<td class="role_name"><span><a href="<?php echo $role_id_url ?>"><?php echo $this->escape($role->name) ?></a></span></td>
									<td class="role_parent"><span><?php echo $this->escape($role->parent_role_id); ?></span></td>
									<td class="role_descr"><span><?php echo $this->truncate($this->escape($role->description))->toLength(200); ?></span></td>
									<td class="role_action">
										<span>
											<div class="pull-right action-buttons">
												<div class="btn-group pull-right">
													<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
														<span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
													</button>
													<ul class="dropdown-menu slidedown">
														<li><a href="<?php echo $role_id_url ?>"><i class="fa fa-eye"></i> <?php echo $this->translate('Просмотреть'); ?></a></li>
														<li><a href="<?php echo $role_edit_url ?>"><i class="fa fa-pencil"></i> <?php echo $this->translate('Редактировать'); ?></a></li>
														<li><a href="<?php echo $role_delete_url ?>"><i class="fa fa-trash-o"></i> <?php echo $this->translate('Удалить'); ?></a></li>
													</ul>
												</div>
											</div>
										</span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="pull-right">
						<?php echo $this->paginationControl($this->roles_data, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>