<?php if ($this->roleData) : ?>
    <div class="block block-default block-ui-bordered">
        <?php
        echo $this->BlockConfigMenu($this->t("Роль пользователя"))->roleMenu(
            $this->escape($this->roleData['ID'])
        );
        ?>
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->roleData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Системное Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->roleData['SystemName']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Родительская роль'); ?></span>
                    </td>
                    <td>
                        <span>
                            <?php if ($this->escape($this->roleData['ParentRoleID'])) { ?>
                                <?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'role', 'id')) { ?>
                                    <?php
                                    $adminRoleIDUrl = $this->url(
                                        array('module' => 'admin', 'controller' => 'role', 'action' => 'id', 'roleID' => $this->escape($this->roleData['ParentRoleID'])), 'adminRoleID'
                                    );
                                    ?>
                                <?php } else { ?>
                                    <?php $adminRoleIDUrl = '#'; ?>
                                <?php } ?>
                                <a href="<?= $adminRoleIDUrl; ?>">
                                    <?= $this->escape($this->roleData['Role'][0]['Name']) ?>
                                </a>
                            <?php } ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->RenderContentTypeText($this->roleData['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->t('Роль пользователя'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->t('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->roleData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->roleData['DateCreate']) != $this->escape($this->roleData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->t('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->roleData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>