<ul class="nav navbar-nav">
    <?php
    $html = array();

    foreach ($this->container as $page) {
	if (!empty($page->pages)) {
	    if ($page->isActive(true)) {
		$html[] = "<li class=\"dropdown active\">";
	    } else {
		$html[] = "<li class=\"dropdown\">";
	    }
	    //$html[] = $this->menu()->htmlify($page) . PHP_EOL;

	    if ($href = $page->getHref()) {
		$page->getTitle() ? $title = $this->translate($page->getTitle()) : $title = "";
		$html[] = "<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" title=\"{$title}\">";
		$html[] = $this->translate($page->getLabel());
		$html[] = "<b class=\"caret\"></b></a>";
	    }

	    $html[] = "<ul class='dropdown-menu'>";
	    foreach ($page->pages as $subpage) {
		if ($subpage->isActive(true)) {
		    $html[] = "<li class=\"active\">";
		} else {
		    $html[] = "<li>";
		}

		if ($href = $subpage->getHref()) {
		    $subpage->getTitle() ? $title = $this->translate($subpage->getTitle()) : $title = "";

		    $html[] = "<a href=\"{$href}\" title=\"{$title}\">";
		}
		else
		    $html[] = "<span>";

		$html[] = $subpage->getLabel();

		if ($href)
		    $html[] = "</a>";
		else
		    $html[] = "</span>";
		$html[] = "</li>";
	    }
	    $html[] = "</ul>";
	}
	else {
	    $html[] = "<li>";
	    if ($page->isActive(true)) {
		$html[] = "<li class=\"active\">";
	    } else {
		$html[] = "<li>";
	    }
	    $html[] = $this->menu()->htmlify($page) . PHP_EOL;
	}

	$html[] = "</li>";
    }

    echo join(PHP_EOL, $html);
    ?>
</ul>