<div id="article_type_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->escape($this->article_type->name);
        } else {
            echo $this->translate('Ошибка!!!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="article_type_item">
                <span>Название:</span>
                <div class="article_type_name"><?php echo $this->escape($this->article_type->name); ?></div>
                <br>
                <span>Описание:</span>
                <div class="article_type_descr"><?php echo $this->escape($this->article_type->description); ?></div>
            </div>
        <?php } ?>
    </div>
</div>