<?php if ($this->leagueData) : ?>
    <?php foreach ($this->leagueData as $league): ?>
        <?php
        // check access and generate link for default/user/id
        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
            $defaultUserIDUrl = $this->url(
                array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                    'userID' => $this->escape($league['User']['ID'])), 'defaultUserID'
            );
        } else {
            $defaultUserIDUrl = '#';
        }
        ?>
        <?php
        // check access and generate link for default/league/id
        if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'league', 'id')) {
            $defaultLeagueIDUrl = $this->url(
                array('module' => 'default', 'controller' => 'league', 'action' => 'id',
                    'leagueID' => $this->escape($league['ID'])), 'defaultLeagueID'
            );
        } else {
            $defaultLeagueIDUrl = '#';
        }
        ?>
        <div class="block block-default block-ui-bordered m-b-10">
            <?php
            echo $this->BlockConfigMenu($this->translate("Лига"))->leagueMenu(
                $this->escape($league['ID'])
            );
            ?>
            <div class="block-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                        <div class="text-center">
                            <?php if ($this->escape($league['ImageLogoUrl'])) { ?>
                                <div class="m-b-15 center-block text-center">
                                    <a href="<?php echo $defaultLeagueIDUrl; ?>">
                                        <img class="img-thumbnail img-responsive" src="<?php echo $this->escape($league['ImageLogoUrl']); ?>"/>
                                    </a>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                        <div class="block block-default">
                            <div>
                                <table class="table table-striped table-bordered m-b-0">
                                    <tbody>
                                    <tr>
                                        <td class="text-bold">
                                            <span><?php echo $this->translate('Название'); ?></span>
                                        </td>
                                        <td>
                                            <span>
                                                <a href="<?php echo $defaultLeagueIDUrl; ?>">
                                                    <?php echo $this->escape($league['Name']); ?>
                                                </a>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold">
                                            <span><?php echo $this->translate('Администратор'); ?></span>
                                        </td>
                                        <td>
                                        <span>
                                            <a target="_blank" href="<?php echo $defaultUserIDUrl; ?>">
                                                <?php echo $this->escape($league['User']['NickName']); ?>
                                            </a>
                                        </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold">
                                            <span><?php echo $this->translate('Описание'); ?></span>
                                        </td>
                                        <td>
                                            <span><?php echo $this->RenderContentTypeText($league['Description'], 'full_html'); ?></span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
            <div class="block-item m-t-15">
                <div class="pull-right">
                    <?php echo $this->paginationControl($this->leagueData, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
<?php endif; ?>