<?php if ($this->paginator) { ?>
	<?php foreach ($this->paginator as $league):
		?>
		<div class="panel panel-default panel-inverse block-item">
			<?php
			echo $this->ConfigureBlockItemMenu($this->translate("Лига"))->league_menu($this->escape($league['id']));
			?>
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-refresh"></i>
					<a href="<?php echo $this->url(array('controller' => 'league', 'action' => 'id', 'league_id' => $this->escape($league['id']), 'page' => 1), 'leagueIdAll', true); ?>"><?php echo $this->escape($league['name']); ?></a>
				</h3>
			</div>
			<div class="panel-body">
				<?php if ($this->escape($league['url_logo']) != '') { ?>
					<div class="league_all_logo_wrapper_200_200 img-wrapper-200-200 img-thumbnail pull-left overflow-hide m-r-5">
						<img class="league_all_logo_200 img-size-200 img-responsive" src="<?php echo $this->baseUrl($this->escape($league['url_logo'])); ?>">
					</div>
				<?php } ?>
				<div class="league_description">
					<?php
					if ($league['description']) {
						echo $this->RenderContentTypeText($league['description'], 'text', 500);
					}
					?>
				</div>
				<div class="pull-right m-t-10">
					<?php
					$league_id_all_url = $this->url(array('controller' => 'league', 'action' => 'id', 'league_id' => $this->escape($league['id']), 'page' => 1), 'leagueIdAll', true);
					?>
					<a href = "<?php echo $league_id_all_url ?>" class = "btn btn-sm btn-inverse block-content-button-more"><?php echo $this->translate('Подробнее') ?> <i class="fa fa-angle-double-right"></i></a>
				</div>
			</div>
			<div class="panel-footer">
				<small>
					<div class="pull-left">
						<span class="font-bold font-color-black"><?php echo $this->translate('Создана') ?>: 
						</span><?php echo $this->escape($league['date_create']); ?>
					</div>
					<div class="pull-left m-l-10">
						<span class="font-bold font-color-black"><i class="fa fa-filter font-color-gray"></i> <?php echo $this->translate('Категория контента') ?>: </span>
						<?php echo $this->translate('Лига'); ?>
					</div>
					<div class="pull-left m-l-10">
						<span class="font-bold font-color-black"><i class="fa fa-user font-color-gray"></i> <?php echo $this->translate('Администратор лиги') ?>: </span>
						<a target="_blank" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $this->escape($league['user_id'])), 'userId', true); ?>"><?php echo $this->escape($league['user_login']); ?></a>
					</div>
				</small>
				<div class="clearfix"></div>
			</div>
		</div>
	<?php endforeach; ?>
	<div class="block-item m-t-15">
		<div class="pull-right">
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
		</div>
		<div class="clearfix"></div>
	</div>
<?php } ?>