<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="block block-default block-ui-bordered">
            <div class="block-header">
                <div class="block-title text-bold text-uppercase">
                    <?= $this->t('Яндекс деньги'); ?>
                </div>
            </div>
            <div class="block-body center-block text-center">
                <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/shop.xml?account=410012351080501&quickpay=shop&payment-type-choice=on&writer=buyer&targets-hint=&default-sum=5&button-text=04&fio=on&mail=on" width="450" height="195"></iframe>
            </div>
        </div>
    </div>
</div>
