<?php if (!$this->raceEventData) : return; endif; ?>

<?php
$raceEvent = $this->raceEventData;
$races = $this->raceData;
?>

<?= $this->render('championship/common/championship-menu.phtml') ?>
<?= $this->render('championship/common/hotlaps-menu.phtml') ?>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="block block-default">
            <div class="block-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <blockquote class="pull-right">
                            <h3><?= $this->escape($raceEvent['Name']); ?></h3>

                            <h1>
                                <small>
                                    <?= $this->t('Номер этапа'); ?>:
                            <span class="label label-info">
                                <?= $this->escape($raceEvent['OrderInChamp']); ?>
                            </span>
                                </small>
                            </h1>
                        </blockquote>
                    </div>
                </div>
                <?php if ($raceEvent['Description']): ?>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="well well-sm">
                                <?= $this->RenderContentTypeText($raceEvent['Description'], 'full_html'); ?></span>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="section-title section-title-bottom m-t-15 m-b-15">
            <?= $this->t('Гонки'); ?>
        </div>
    </div>
</div>

<?php foreach ($races as $race): ?>

    <?php
    $defaultRaceIDUrl = $this->url(
        array('module' => 'default', 'controller' => 'race', 'action' => 'id',
            'raceID' => $race['ID']), 'defaultRaceID'
    );
    ?>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="block block-race m-b-15">
                <?= $this->BlockConfigMenu($this->t("Гонка"))
                    ->raceMenu($this->escape($race['ID']));
                ?>
                <?php if ($this->escape($race['Track']['SchemeUrl'])) : ?>
                    <div class="">
                        <a href="#" data-toggle="modal" data-target=".race-<?= $race['ID']; ?>"
                           title="<?= $this->escape($race['Name']); ?>" class="thumbnail">
                            <img class="img-responsive img-thumbnail"
                                 src="<?= $this->baseUrl($this->escape($race['Track']['SchemeUrl'])); ?>"/>
                        </a>
                        <?= $this->modal(array(
                            'title' => $race['Track']['Name'],
                            'class' => 'race-' . $race['ID'],
                            'content' => '<img src="'
                                . $this->baseUrl($this->escape($race['Track']['SchemeUrl']))
                                . '" class="img-responsive img-rounded center-block" alt="" />'
                        )); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <div class="block block-default block-ui-bordered block-race">
                <?= $this->BlockConfigMenu($this->t("Гонка"))
                    ->raceMenu($this->escape($race['ID']));
                ?>
                <div class="block-body">
                    <h4 class="race-name">
                        <?= $this->escape($race['Name']); ?>
                    </h4>
                    <hr/>
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                        <?= $this->t('О гонке'); ?>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>
                                                    <span><?= $this->t('Номер этапа'); ?></span>
                                                </th>
                                                <th>
                                                    <span><?= $this->t('Дата проведения'); ?></span>
                                                </th>
                                                <th>
                                                    <span><?= $this->t('Круги / Время'); ?></span>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td class="text-vertical-m">
                                                    <span class="label label-danger">
                                                        <?= $race['OrderInEvent'] ?>
                                                    </span>
                                                </td>
                                                <td class="text-vertical-m">
                                                    <span>
                                                        <i class="fa fa-calendar fa-lg"></i>
                                                        <span>
                                                            <?= date_format(date_create($this->escape($race['DateStart'])), 'd-m, Y'); ?>
                                                        </span>
                                                        <i class="fa fa-clock-o fa-lg"></i>
                                                        <span>
                                                            <?= date_format(date_create($this->escape($race['DateStart'])), 'H:i:s'); ?>
                                                        </span>
                                                    </span>
                                                </td>
                                                <td class="text-vertical-m">
                                                    <span>
                                                        <?php if ($race['LapsCount']): ?>
                                                            <?= $this->escape($race['LapsCount']); ?>
                                                        <?php endif; ?>

                                                        <?php if ($race['TimeDuration']): ?>
                                                            <?= $this->escape($race['TimeDuration']); ?>
                                                        <?php endif; ?>
                                                    </span>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <?php if ($race['Description']) : ?>
                                        <div class="well well-sm">
                                            <?= $this->RenderContentTypeText($race['Description'], 'full_html'); ?></span>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                        <?= $this->t('О трассе'); ?>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                            <div class="tooltip-field"
                                                 title="<?= $this->escape($race['Track']['Country']['EnglishName']); ?>">
                                                <img
                                                    src="<?= $this->escape($race['Track']['Country']['ImageGlossyWaveUrl']); ?>"/>
                                            </div>
                                            <!-- detail information for race  -->
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                    <tr>
                                                        <th>
                                                            <?= $this->t('Круги / Время'); ?>
                                                        </th>
                                                        <th>
                                                            <?= $this->t('Год конфиг. трассы'); ?>
                                                        </th>
                                                        <th>
                                                            <?= $this->t('Круг (км)'); ?>
                                                        </th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    <tr>
                                                        <td>
                                                            <?php if ($race['LapsCount']): ?>
                                                                <?= $this->escape($race['LapsCount']); ?>
                                                            <?php endif; ?>

                                                            <?php if ($race['TimeDuration']): ?>
                                                                <?= $this->escape($race['TimeDuration']); ?>
                                                            <?php endif; ?>
                                                        </td>
                                                        <td>
                                                            <?= $this->escape($race['Track']['Year']); ?>
                                                        </td>
                                                        <td>
                                                            <?= $this->escape($race['Track']['Length']); ?>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <!-- end detail information for race  -->
                                            <?php if ($race['Track']['Description']) : ?>
                                            <div class="well well-sm">
                                                <?= $this->RenderContentTypeText($race['Track']['Description'], 'full_html'); ?></span>
                                            </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>