<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php if ($this->paginator) : ?>
            <div class="block block-timeline">
                <?php
                $block_class = 'block-timeline-inverted';

                //create comment db model
                $comment_db = new Application_Model_DbTable_Comment();
                ?>
                <?php foreach ($this->paginator as $post): ?>
                    <?php
                    if ($block_class == 'block-timeline-inverted') {
                        $block_class = '';
                    } else {
                        $block_class = 'block-timeline-inverted';
                    }
                    $default_post_id_url = $this->url(
                        array('module' => 'default', 'controller' => 'post', 'action' => 'id', 'post_id' => $this->escape($post->id)),
                        'defaultPostId', true
                    );
                    $default_user_id_url = $this->url(
                        array('module'  => 'default', 'controller' => 'user', 'action' => 'id',
                              'user_id' => $this->escape($post->user_id)), 'defaultUserId', true
                    );
                    /*
                     * TODO: Add method for comment model for countiong comments
                     */
                    $comment_idencity_args = array('post_id' => $post->id);
                    $post_comment_data = $comment_db->getAll($comment_idencity_args);
                    if ($post_comment_data){
                        $comments_count = count($post_comment_data);
                    } else {
                        $comments_count = 0;
                    }

                    ?>
                <div class="block-timeline-item <?php echo  $block_class; ?>">
                    <div class="block-timeline-badge primary">
                        <a>
                            <i class="fa fa-dot-circle-o fa-lg"" rel="tooltip"
                               title="<?php echo $this->translate('Добавлено').': '.$this->escape($post->date_create); ?>" id=""></i>
                        </a>
                    </div>
                    <div class="block block-default block-ui-bordered">
                        <?php
                        echo $this->BlockConfigMenu($this->translate("Контент"))->postMenu(
                            $this->escape($post->id)
                        );
                        ?>
                        <div class="block-header">
                            <h4>
                                <div class="block-title text-bold">
                                    <a href="<?php echo $default_post_id_url; ?>">
                                        <?php echo $this->truncate($this->escape($post->name))->toLength(100); ?>
                                    </a>
                                </div>
                            </h4>
                            <?php if ($this->escape($post->image) != '') { ?>
                                <div class="img-wrapper-250-250 overflow-hide center-block">
                                    <img class="img-thumbnail img-responsive img-size-250"
                                         src="<?php echo $this->escape($post->image); ?>" />
                                </div>
                            <?php } ?>
                        </div>
                        <div class="block-body">
                            <?php
                            if ($post->preview) {
                                echo $this->RenderContentTypeText($this->escape($post->preview), 'bbcode');
                            } else {
                                echo $this->RenderContentTypeText($this->escape($post->text), 'bbcode', 250);
                            }
                            ?>
                        </div>
                        <div class="block-footer clearfix">
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?php echo $this->translate('Просмотров');?>" data-placement="bottom">
                                <i class="fa fa-eye fa-lg"></i>
                                <?php echo $this->escape($post->views); ?>
                            </div>
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?php echo $this->translate('Комментарии');?>" data-placement="bottom">
                                <i class="fa fa-comments-o fa-lg"></i>
                                <?php echo $comments_count; ?>
                            </div>
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?php echo $this->translate('Автор');?>" data-placement="bottom">
                                <a href="<?php echo $default_user_id_url; ?>" target="_blank">
                                    <i class="fa fa-user fa-lg"></i>
                                    <?php echo $this->escape($post->user_login); ?>
                                </a>
                            </div>
                            <div class="pull-right tooltip-field" data-title="<?php echo $this->translate('Читать дальше');?>" data-placement="bottom">
                                <a href="<?php echo $default_post_id_url ?>"
                                   class="block-content-button-more">
                                    <i class="fa fa-hand-o-right fa-lg"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
                <div class="clearfix"></div>
            </div>
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="block-item m-t-15">
                        <div class="pull-right">
                            <?php echo $this->paginationControl(
                                $this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                            ); ?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>