<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php if ($this->postData) : ?>
            <div class="block block-timeline">
                <?php
                $block_class = 'block-timeline-inverted';
                ?>
                <?php foreach ($this->postData as $post): ?>
                    <?php
                    if ($block_class == 'block-timeline-inverted') {
                        $block_class = '';
                    } else {
                        $block_class = 'block-timeline-inverted';
                    }?>
                    <?php
                    // check access and generate link for default/post/id
                    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'post', 'id')) {
                        $defaultPostIDUrl = $this->url(
                            array('module' => 'default', 'controller' => 'post', 'action' => 'id',
                                'postID' => $this->escape($post['ID'])), 'defaultPostID'
                        );
                    } else {
                        $defaultPostIDUrl = '#';
                    }
                    ?>
                    <?php
                    // check access and generate link for default/user/id
                    if ($this->checkUserAccess('default' . Acl::RESOURCE_SEPARATOR . 'user', 'id')) {
                        $defaultUserIDUrl = $this->url(
                            array('module' => 'default', 'controller' => 'user', 'action' => 'id',
                                'userID' => $this->escape($post['User']['ID'])), 'defaultUserID'
                        );
                    } else {
                        $defaultUserIDUrl = '#';
                    }
                    ?>

                    <?php
                    //TODO: Add method for comment model for counting comments

                    $query = Doctrine_Query::create()
                        ->from('Default_Model_Comment c')
                        ->leftJoin('c.User u')
                        ->where('c.PostID = ?', $post['ID']);
                    $commentResult = $query->fetchArray();

                    $commentsСount = count($commentResult);
                    ?>
                <div class="block-timeline-item <?=  $block_class; ?>">
                    <div class="block-timeline-badge primary">
                        <a href="<?= $defaultPostIDUrl;?>">
                            <i class="fa fa-dot-circle-o fa-lg"" rel="tooltip" title="<?= $this->t('Добавлено').': '.$this->escape($post['DateCreate']); ?>" id=""></i>
                        </a>
                    </div>
                    <div class="block block-default block-ui-bordered">
                        <?php
                        echo $this->BlockConfigMenu($this->t("Контент"))->postMenu(
                            $this->escape($post['ID'])
                        );
                        ?>
                        <div class="block-header">
                            <h4>
                                <div class="block-title text-bold">
                                    <a href="<?= $defaultPostIDUrl; ?>">
                                        <?= $this->truncate($this->escape($post['Name']))->toLength(100); ?>
                                    </a>
                                </div>
                            </h4>
                            <?php if ($this->escape($post['ImageUrl']) != '') { ?>
                                <div class="img-wrapper-250-250 overflow-hide center-block">
                                    <img class="img-thumbnail img-responsive img-size-250" src="<?= $this->escape($post['ImageUrl']); ?>" />
                                </div>
                            <?php } ?>
                        </div>
                        <div class="block-body">
                            <?php
                            if ($post['Preview']) {
                                echo $this->RenderContentTypeText($this->escape($post['Preview']), 'bbcode');
                            } else {
                                echo $this->RenderContentTypeText($this->escape($post['Text']), 'bbcode', 250);
                            }
                            ?>
                        </div>
                        <div class="block-footer clearfix">
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Просмотров');?>" data-placement="bottom">
                                <i class="fa fa-eye fa-lg"></i>
                                <?= $this->escape($post['Views']); ?>
                            </div>
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Комментарии');?>" data-placement="bottom">
                                <i class="fa fa-comments-o fa-lg"></i>
                                <?= $commentsСount; ?>
                            </div>
                            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Автор');?>" data-placement="bottom">
                                <a target="_blank" href="<?= $defaultUserIDUrl; ?>" >
                                    <i class="fa fa-user fa-lg"></i>
                                    <?= $this->escape($post['User']['NickName']); ?>
                                </a>
                            </div>
                            <div class="pull-right tooltip-field" data-title="<?= $this->t('Читать дальше');?>" data-placement="bottom">
                                <a href="<?= $defaultPostIDUrl ?>" class="block-content-button-more">
                                    <i class="fa fa-arrow-right fa-lg"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
                <div class="clearfix"></div>
            </div>
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <div class="block-item m-t-15">
                        <div class="pull-right">
                            <?= $this->paginationControl(
                                $this->postData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                            ); ?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>