<?php if ($this->post) { ?>
    <?php echo $this->form; ?>
    <div class="post_item block_item">
        <div class="block_item_content">
	    <?php if ($this->post['image'] != '') { ?>
		<div class="block-align-center">
		    <div class="img-thumbnail font-align-center post_id_logo_wrapper_690 image_wrapper_690 overflow-hide">
			<img class="post_id_logo image_size_690" src="<?php echo $this->escape($this->post['image']); ?>">
		    </div>
		</div>
	    <?php } ?>
    	<div class="block-content-text">
		<?php
		echo $this->RenderContentTypeText($this->post['text'], $this->post['content_type_name']);
		?>
    	</div>
    	<div class="post_info block_item_info_bottom">
    	    <div class="content_category block_item_info_bottom_item">
    		<span class="font-bold font-color-black"><?php echo $this->translate('Категория контента') ?>: </span><?php echo $this->escape($this->post['article_type_name']); ?>
    	    </div>
    	    <div class="post_author block_item_info_bottom_item">
    		<span class="font-bold font-color-black"><?php echo $this->translate('Автор') ?>: </span>
    		<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $this->escape($this->post['user_id'])), 'userId', true) ?>" target="_blank"><?php echo $this->escape($this->post['user_login']); ?></a>
    	    </div>
    	    <div class="post_views block_item_info_bottom_item">
    		<span class="font-bold font-color-black"><?php echo $this->translate('Просмотров') ?>: </span><?php echo $this->escape($this->post['views']); ?>
    	    </div>
    	    <div class="post_date_create block_item_info_bottom_item">
    		<span class="font-bold font-color-black"><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->post['date_create']); ?>
    	    </div>
		<?php if ($this->escape($this->post['date_create']) != $this->escape($this->post['date_edit'])) { ?>
		    <div class="post_date_edit block_item_info_bottom_item">
			<span class="font-bold font-color-black"><?php echo $this->translate('Редактировалось') ?>: </span><?php echo $this->escape($this->post['date_edit']); ?>
		    </div>
		<?php } ?>
    	</div>
        </div>
    </div>
<?php } ?>