<?php $this->CKEditor()->setup(); ?>
<?php echo $this->form; ?>
<script>
    jQuery(document).ready(function() {
	<?php echo $this->setupBBCodeEditor('annotation'); ?>

	var content_type = $("#content_type").find(':selected').text();

	switch (content_type) {
	    case 'bbcode':
		bbcode();
		break;
	    case 'text':
		text();
		break;
	    case 'full html':
		full_html();
		break;
	    default:
		text();
		break;
	}

	function bbcode() {
	    var hEd = CKEDITOR.instances['text'];
	    if (hEd) {
		hEd.destroy();
	    }
	    <?php
	    echo $this->setupBBCodeEditor('text');
	    ?>
	}


	function full_html() {
	    var hEd = CKEDITOR.instances['text'];
	    if (hEd) {
		hEd.destroy();
	    }
	    <?php
	    echo $this->setupFullHtmlEditor('text');
	    ?>
	}

	function text() {
	    var hEd = CKEDITOR.instances['text'];
	    if (hEd) {
		hEd.destroy();
	    }
	}

	$(".page_content").on('change', "#content_type", function() {
	    content_type = $(this).find(':selected').text();
	    switch (content_type) {
		case 'bbcode':
		    bbcode();
		    break;
		case 'text':
		    text();
		    break;
		case 'full html':
		    full_html();
		    break;
		default:
		    text();
		    break;
	    }
	});
    });
</script>