<?php if ($this->post_data) { ?>
    <?php
    $default_user_id_url = $this->url(
        array('module'  => 'default', 'controller' => 'user', 'action' => 'id',
              'user_id' => $this->escape($this->post_data->user_id)), 'defaultUserId', true
    );

    if ($this->post_comment_data) {
        $comments_count = count($this->post_comment_data);
    } else {
        $comments_count = 0;
    }

    ?>
    <div class="row m-t-10">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="block block-default">
                <?php
                echo $this->BlockConfigMenu($this->translate("Контент"))->postMenu(
                    $this->escape($this->post_data->id)
                );
                ?>
                <div class="block-header block-header-info clearfix">
                    <div class="pull-right m-r-15 tooltip-field" data-title="<?php echo $this->translate('Просмотров');?>" data-placement="bottom">
                        <i class="fa fa-eye fa-lg"></i>
                        <?php echo $this->escape($this->post_data->views); ?>
                    </div>
                    <div class="pull-right m-r-15 tooltip-field" data-title="<?php echo $this->translate('Комментарии');?>" data-placement="bottom">
                        <i class="fa fa-comments-o fa-lg"></i>
                        <?php echo $comments_count; ?>
                    </div>
                    <div class="pull-left m-r-15 tooltip-field" data-title="<?php echo $this->translate('Автор');?>" data-placement="bottom">
                        <a href="<?php echo $default_user_id_url; ?>" target="_blank">
                            <i class="fa fa-user fa-lg"></i>
                            <?php echo $this->escape($this->post_data->user_login); ?>
                        </a>
                    </div>
                </div>
                <div class="block-body">
                    <?php if ($this->escape($this->post_data->image)) { ?>
                        <div class="m-b-15 center-block text-center">
                            <a href="#" data-toggle="modal" data-target=".post-<?php print $this->post_data->id; ?>"
                               title="<?php echo $this->escape($this->post_data->name); ?>" class="">
                                <img class="img-thumbnail img-responsive"
                                     src="<?php echo $this->escape($this->post_data->image); ?>"/>
                            </a>
                            <?php echo $this->modal(array(
                                'title' => $this->post_data->name,
                                'class' => 'post-'.$this->post_data->id,
                                'content' => '<img src="'.$this->escape($this->post_data->image).'" class="img-responsive img-rounded center-block" alt="">'
                            )); ?>
                        </div>
                    <?php } ?>
                    <div class="block-content-text">
                        <?php
                        echo $this->RenderContentTypeText(
                            $this->post_data['text'], $this->post_data->content_type_name
                        );
                        ?>
                    </div>
                    <div class="button-like-wrapper">
                        <div id="vk-like-button" class="button-like">
                            <!-- VK Like -->
                            <script type="text/javascript" src="//vk.com/js/api/openapi.js?96"></script>
                            <script type="text/javascript">
                                VK.init({apiId: 3649896, onlyWidgets: true});
                            </script>
                            <div id="vk_like"></div>
                            <script type="text/javascript">
                                VK.Widgets.Like("vk_like", {type: "mini", height: 18});
                            </script>
                        </div>
                        <div class="fb-like-button button-like">
                            <!-- Facebook like-->
                            <div id="fb-root"></div>
                            <script>(function (d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (d.getElementById(id))
                                        return;
                                    js = d.createElement(s);
                                    js.id = id;
                                    js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
                                    fjs.parentNode.insertBefore(js, fjs);
                                }(document, 'script', 'facebook-jssdk'));</script>
                            <div class="fb-like" data-href="<?php echo $this->url() ?>" data-width="450"
                                 data-layout="button_count" data-show-faces="true" data-send="false"></div>
                            <!-- Facebook like END-->
                        </div>
                        <div class="gp-like-button button-like">
                            <div class="g-plusone" data-size="medium"></div>
                            <script type="text/javascript">
                                window.___gcfg = {lang: 'en-GB'};

                                (function () {
                                    var po = document.createElement('script');
                                    po.type = 'text/javascript';
                                    po.async = true;
                                    po.src = 'https://apis.google.com/js/plusone.js';
                                    var s = document.getElementsByTagName('script')[0];
                                    s.parentNode.insertBefore(po, s);
                                })();
                            </script>
                        </div>
                        <div class="tw-like-button button-like">
                            <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                            <script>!function (d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
                                    if (!d.getElementById(id)) {
                                        js = d.createElement(s);
                                        js.id = id;
                                        js.src = p + '://platform.twitter.com/widgets.js';
                                        fjs.parentNode.insertBefore(js, fjs);
                                    }
                                }(document, 'script', 'twitter-wjs');</script>
                        </div>
                        <div class="all-like-button button-like">
                            <!-- AddThis Button BEGIN -->
                            <div class="addthis_toolbox addthis_default_style">
                                <a class="addthis_counter addthis_pill_style"></a>
                            </div>
                            <script type="text/javascript"
                                    src="//s7.addthis.com/js/300/addthis_widget.js#pubid=undefined"></script>
                            <!-- AddThis Button END -->
                        </div>
                    </div>
                </div>
                <div class="block-footer clearfix">
                    <div class="pull-left m-r-15 tooltip-field" data-title="<?php echo $this->translate('Тип контента');?>" data-placement="bottom">
                        <i class="fa fa-filter fa-lg"></i>
                        <?php echo $this->escape($this->post_data->post_type_name); ?>
                    </div>
                    <div class="pull-right m-r-15 tooltip-field" data-title="<?php echo $this->translate('Дата создания');?>" data-placement="bottom">
                        <i class="fa fa-calendar fa-lg"></i>
                        <?php echo $this->escape($this->post_data->date_create); ?>
                    </div>
                    <?php if ($this->escape($this->post_data->date_create) != $this->escape($this->post_data->date_edit)) : ?>
                        <div class="pull-right m-r-15 tooltip-field" data-title="<?php echo $this->translate('Дата редактирования');?>" data-placement="bottom">
                            <i class="fa fa-pencil fa-lg"></i>
                            <?php echo $this->escape($this->post_data['date_edit']); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <!-- comments -->
    <?php
    $comment_add_access = $this->checkUserAccess(
        'default' . Acl::RESOURCE_SEPARATOR . 'comment', 'add'
    );
    ?>

    <!-- post comments list -->
    <div class="row m-t-10">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="block block-default block-ui-bordered comment-block">
                <div class="block-header">
                    <div class="block-title text-uppercase text-bold">
                        <?php echo $this->translate('Комментарии'); ?>
                    </div>
                </div>
                <div class="block-body">
                    <div class="comments" id="post-comments">
                        <?php if ($this->post_comment_data) { ?>
                            <?php foreach ($this->post_comment_data as $comment): ?>
                                <?php
                                $default_user_id_url = $this->url(
                                    array('module'  => 'default', 'controller' => 'user', 'action' => 'id',
                                          'user_id' => $this->escape($comment->user_id)), 'defaultUserId', true
                                );
                                $user_db = new Application_Model_DbTable_User();
                                $user_data = $user_db->getItem($comment->user_id);

                                if ($this->getUserStatus($user_data->date_last_activity) == 'online') {
                                    $user_status_class = 'user-online';
                                } else {
                                    $user_status_class = 'user-offline';
                                }
                                ?>

                                <div class="message-item" id="m7">
                                    <div class="message-inner">
                                        <div class="message-head clearfix">
                                            <div class="avatar pull-left">
                                                <div class="block-user">
                                                    <div
                                                        class="img-wrapper-40-40 overflow-hide img-circle center-block user-avatar tooltip-field <?php echo $user_status_class; ?>"
                                                        data-title="<?php echo $user_data->login; ?>"
                                                        data-placement="bottom">
                                                        <a href="<?php echo $default_user_id_url; ?>" target="_blank">
                                                            <?php echo $this->getUserAvatar(
                                                                $user_data->id, $user_data->avatar_type,
                                                                'media-object img-responsive img-size-40', 40
                                                            ); ?>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="user-detail">
                                                <?php if ($comment->title) { ?>
                                                    <h5 class="text-bold handle">
                                                        <?php echo $comment->title; ?>
                                                    </h5>
                                                <?php } ?>
                                                <div class="post-meta">
                                                    <div class="asker-meta">
                                                        <span class="qa-message-what"></span>
                                                        <span class="qa-message-when">
                                                            <span class="qa-message-when-data">
                                                                <?php echo $comment->date_create; ?>
                                                            </span>
                                                        </span>
                                                        <span class="qa-message-who">
                                                            <span class="qa-message-who-pad"> </span>
                                                            <span class="qa-message-who-data">
                                                                <a href="<?php echo $default_user_id_url; ?>"
                                                                   target="_blank">
                                                                    <?php echo $user_data->login; ?>
                                                                </a>
                                                            </span>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="qa-message-content">
                                            <?php echo $comment->content; ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php } else { ?>
                            <div class="alert alert-info">
                                <?php echo $this->translate('Для данной записи нет комментариев!'); ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ./ post comments list -->

    <!-- post comment form -->
    <div class="row m-t-10">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="block block-default block-ui-bordered">
                <div class="block-header">
                    <div class="block-title text-uppercase text-bold">
                        <?php echo $this->translate('Добавить комментарий'); ?>
                    </div>
                </div>
                <div class="block-body">
                    <?php if ($comment_add_access) { ?>
                        <?php echo $this->comment_add_form; ?>
                    <?php } else { ?>
                        <div class="alert alert-warning">
                            <?php echo $this->translate(
                                'Добавлять комментарии могут только зарегестированные пользователи!'
                            ); ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <!-- ./ post comment form -->
    <!-- ./ comments -->
<?php } ?>