<script type="text/javascript">
    // back to top button plugin
    $(function() {
        $("#back-top").hide();

        $(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('#back-top').fadeIn();
                } else {
                    $('#back-top').fadeOut();
                }
            });

            $('#back-top a').click(function () {
                $('body,html').animate({
                    scrollTop: 0
                }, 800);
                return false;
            });
        });
    });
</script>
<p id="back-top">
    <a href="#top"><span></span>На подиум!</a>
</p>