<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->minifyHeadLink() ?>
	<?php echo $this->headScript() ?>
	<?php //echo $this->minifyHeadScript() ?>
    </head>
    <body>
        <!-- HeadLine -->
	<?php echo $this->render("default_layout/head_line.phtml"); ?>
        <div id="page_wrapper">
            <div id="page">
		<?php echo $this->render("default_layout/header.phtml") ?>
                <div id="main_wrapper" class="container">
                    <div id="main" class="row clearfix">
                        <!-- Content -->
                        <div class="col-lg-9 col-lg-push-3">
			    <div id="content">
				<?php
				$breadcrumb = Zend_Registry::get('breadcrumb');
				$page_title = $this->pageTitle();
				if ($page_title != "" || $breadcrumb['show']) :
				    ?>
    				<div id="page_title_wrapper" class="block_item">
					<?php if ($this->pageTitle() != ""): ?>
					    <div class="page_title"><h4><?php echo $this->pageTitle() ?></h4></div>
					<?php endif; ?>
					<?php
					if ($breadcrumb['show']) {
					    echo $this->render("default_layout/breadcrumb.phtml");
					}
					?>
    				</div>
				<?php endif; ?>
				<?php echo $this->showMessages(); ?>
				<div id="<?php echo ("{$this->module}_{$this->controller}_{$this->action}"); ?>" class="page">
				    <div class="page_content">
					<?php echo $this->layout()->content ?>
				    </div>
				</div>
			    </div>
			</div>
                        <!-- Left sidebar -->
			<?php echo $this->render("default_layout/left_sidebar.phtml") ?>
                    </div>
                </div>
		<?php echo $this->render("default_layout/footer.phtml") ?>
            </div>
	    <?php
	    if ($this->back_to_top_btn) {
		echo $this->render("default_layout/blocks/back_to_top_btn.phtml");
	    }
	    ?>
	    <?php
	    if ($this->share_block) {
		echo $this->render("default_layout/blocks/share_block.phtml");
	    }
	    ?>

        </div>
	<?php
	if ($this->page_scroller_block) {
	    echo $this->render("default_layout/blocks/page_scroller_block.phtml");
	}
	?>
	<?php
	if ($this->slide_out_tabs_block) {
	    echo $this->render("default_layout/blocks/slide_out_tabs_block.phtml");
	}
	?>
	<div id="background-wrapper"></div>
        <script type="text/javascript">
	    var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', 'UA-32674101-2']);
	    _gaq.push(['_trackPageview']);

	    (function() {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	    })();
        </script>
    </body>
</html>