<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headLink() ?>
		<?php echo $this->headStyle() ?>
		<?php echo $this->minifyHeadLink() ?>
		<?php echo $this->headScript() ?>
		<?php //echo $this->minifyHeadScript() ?>
    </head>
    <body>
		<div id="page_wrapper">
			<div id="page">
				<div id="main_wrapper" class="container">
					<?php //echo $this->showMessages(); ?>
					<div class="row m-t-15">
						<div class="col-lg-12">
							<div class="text-center">
								<img class="img-responsive img-size-365 block-center" src="/img/or-logo-round.png" />
							</div>
						</div>
					</div>
					<div class="row m-t-15">
						<div class="col-lg-12">
							<div class="panel">
								<div class="panel-body block-center text-center">
									<div class="error-template text-center">
										<h1><?php echo $this->translate('УПС!'); ?></h1>
										<h2><?php echo $this->translate('Ошибка 404. Страница не найдена!'); ?></h2>
										<div class="error-details">
											<?php echo $this->translate('Приносим свои извинения. На сайте проиозошла ошибка, запрашиваемая страница не найдена!'); ?>
										</div>
										<div class="error-actions m-t-15">
											<a href="<?php echo $this->baseUrl(); ?>" class="btn btn-primary btn-lg">
												<i class="fa fa-home"></i> <?php echo $this->translate('Перейти на главную страницу?'); ?>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="row m-t-15">
						<div class="col-md-12">
							<?php echo $this->layout()->content ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="background-wrapper"></div>
        <script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-32674101-2']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script');
				ga.type = 'text/javascript';
				ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(ga, s);
			})();
        </script>
    </body>
</html>