<div class="footer_box footer_left">
    <div class="footer_logo">
        <a href="http://online-racing.net"><img src="<?php echo $this->baseUrl('img/logo_190.png'); ?>" alt="<?php echo $this->translate('Online-Racing.net') ?>"></a>
    </div>
    <div><?php echo $this->translate('Online-Racing.net') ?></div>
</div>
<div class="footer_box footer_center">
    <div class="footer_menu">
        <?php echo $this->render("footer_menu.phtml") ?>
    </div>
</div>
<div class="footer_box footer_right">
    <div class="socialNetworks_slogan">
        <?php echo $this->translate('Наши ссылки в социальных сетях') ?>:
    </div>
    <div class="socialNetworks">
        <?php echo $this->render("socialNetworks_block.phtml") ?>
    </div>
</div>
<div class="footer_bootom">
    <div class="copyright">
        <?php echo $this->translate('Версия сайта') ?> 0.5.2b<br>
        2012 © Online-Racing.net
    </div>
    <div class="web_counters">
        <div class="liveinternet">
            <?php echo $this->render("live_internet_block.phtml") ?>
        </div>
        <div class="rambler100">
            <?php echo $this->render("rambler100_block.phtml") ?>
        </div>
        <div class="yandex">
            <?php echo $this->render("yandex_block.phtml") ?>
        </div>
    </div>
</div>