<div class="footer_box footer_left">
    <div class="footer_logo">
        <a href="http://online-racing.net"><img src="<?php echo $this->baseUrl('img/logo_190.png'); ?>" alt=""></a>
    </div>
    <div>online-racing.net</div>
</div>
<div class="footer_box footer_center">
    <div class="footer_menu">
        <?php echo $this->render("footer_menu.phtml") ?>
    </div>
    <div class="copyright">2012 © Online-Racing.net</div>
</div>
<div class="footer_box footer_right">
    <div class="liveinternet">
        <?php echo $this->render("live_internet.phtml") ?>
    </div>
    <div class="socialNetworks">
        <a href="http://vk.com/OnlineRacingNet" target="_blank"><div class="socnet vk"></div></a>
        <a href="http://www.facebook.com/OnlineRacingNet" target="_blank"><div class="socnet fb"></div></a>
    </div>
</div>
