<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->minifyHeadLink() ?>
	<?php echo $this->headScript() ?>
	<?php //echo $this->minifyHeadScript() ?>
    </head>
    <body>
	<h3>Forum</h3>

	<?php echo $this->layout()->content ?>
	<script type="text/javascript">             var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', 'UA-32674101-2']);
	    _gaq.push(['_trackPageview']);

	    (function() {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	    })();
        </script>
    </body>