<div class="footer_menu">
    <ul id="footer_menu">
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Главная') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Чемпионат') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("user/all") ?>"><?php echo $this->translate('Гонщики') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("article/all") ?>"><?php echo $this->translate('Статьи') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Файлы') ?></a></li>
        <li><a href="http://formula1osr.forum2x2.ru/" target="_BLINK"><?php echo $this->translate('Форум') ?></a></li>
    </ul>
</div>