<!-- Site Logo -->
<div id="logo_box">
    <a id="logo" href="<?php echo $this->baseUrl(''); ?>"><img src="<?php echo $this->baseUrl('logo.png'); ?>" alt="Главная" /></a>
</div>

<!-- User ToolBar -->
<?php echo $this->partial('user_toolbar.phtml'); ?>

<!-- Main Menu -->
<?php echo $this->partial('main_menu.phtml'); ?>

<!-- Moving text-->
<?php echo $this->partial('mooving_text.phtml'); ?>