<div id="headline">
    <div id="headline_wraper">
        <!-- User ToolBar -->
        <?php echo $this->partial('header/hd_user_toolbar.phtml'); ?>
        <!-- Site Logo -->
        <div id="logo_box">
            <a id="logo" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true); ?>"><img src="<?php echo $this->baseUrl('img/logo.png'); ?>" alt="<?php echo $this->translate('Главная') ?>" /></a>
        </div>
    </div>
</div>