<?php
$this->minifyHeadLink()->appendStylesheet("/library/font-awesome/css/font-awesome.min.css"); //font-awesome fonts

$this->minifyHeadLink()->appendStylesheet('/css/layout-admin.css');
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>

    <?php echo $this->jQuery(); ?>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <script type="text/javascript">
        //<![CDATA[
        try {
            if (!window.CloudFlare) {
                var CloudFlare = [
                    {verbose: 0, p: 0, byc: 0, owlid: "cf", bag2: 1, mirage2: 0, oracle: 0, paths: {cloudflare: "/cdn-cgi/nexp/dokv=88e434a982/"}, atok: "a23e8157bed2bc0c5702622f44444bb6", petok: "91196379a0088d28e34fd5875931c101d8644086-1410272845-1800", zone: "beer2code.com", rocket: "0", apps: {}}
                ];
                CloudFlare.push({"apps": {"ape": "4042b8e14b93b0877da373b10ae14fc5"}});
                !function (a, b) {
                    a = document.createElement("script"), b = document.getElementsByTagName("script")[0], a.async = !0, a.src = "//ajax.cloudflare.com/cdn-cgi/nexp/dokv=97fb4d042e/cloudflare.min.js", b.parentNode.insertBefore(a, b)
                }()
            }
        } catch (e) {
        }
        ;
        //]]>
    </script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800"

</head>
<body>
<?php echo $this->render("layout-admin/navbar.phtml") ?>

<?php echo $this->render("layout-admin/sidebar.phtml") ?>

<div class="main-content">
<div class="container">
    <div class="row">

        <div class="area-top clearfix">
            <div class="pull-left header">
                <h3 class="title">
                    <i class="fa fa-dashboard"></i>
                    Dashboard
                </h3>
                <h5>
            <span>
              A subtitle can go here
            </span>
                </h5>
            </div>

            <ul class="list-inline pull-right sparkline-box">

                <li class="sparkline-row">
                    <h4 class="blue"><span>Orders</span> 847</h4>
                    <div class="sparkline big" data-color="blue"><!--25,11,5,28,25,19,27,6,4,23,20,6--></div>
                </li>

                <li class="sparkline-row">
                    <h4 class="green"><span>Reviews</span> 223</h4>
                    <div class="sparkline big" data-color="green"><!--28,26,13,18,8,6,24,19,3,6,19,6--></div>
                </li>

                <li class="sparkline-row">
                    <h4 class="red"><span>New visits</span> 7930</h4>
                    <div class="sparkline big"><!--16,23,28,8,12,9,25,11,16,16,17,13--></div>
                </li>

            </ul>
        </div>
    </div>
</div>

<div class="container padded">
    <div class="row">

        <!-- Breadcrumb line -->

        <div id="breadcrumbs">
            <div class="breadcrumb-button blue">
                <span class="breadcrumb-label"><i class="fa fa-home"></i> Home</span>
                <span class="breadcrumb-arrow"><span></span></span>
            </div>



            <div class="breadcrumb-button">
          <span class="breadcrumb-label">
            <i class="fa fa-dashboard"></i> Dashboard
          </span>
                <span class="breadcrumb-arrow"><span></span></span>
            </div>
        </div>
    </div>
</div>

<div class="container">
<div class="row">

    <div class="col-md-3">
        <!-- find me in partials/action_nav_normal -->

        <!--big normal buttons-->
        <div class="action-nav-normal">

            <div class="row action-nav-row">
                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="New Project">
                        <i class="fa fa-file-alt"></i>
                        <span>New Project</span>
                    </a>
                    <span class="triangle-button red"><i class="fa fa-plus"></i></span>
                </div>

                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="Messages">
                        <i class="fa fa-comments-alt"></i>
                        <span>Messages</span>
                    </a>
                    <span class="label label-black">14</span>
                </div>
            </div>

            <div class="row action-nav-row">
                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="Files">
                        <i class="fa fa-folder-open-alt"></i>
                        <span>Files</span>
                    </a>
                </div>

                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="Users">
                        <i class="fa fa-user"></i>
                        <span>Users</span>
                    </a>
                    <span class="triangle-button green"><span class="inner">+3</span></span>
                </div>
            </div>

            <div class="row action-nav-row">
                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="Friends">
                        <i class="fa fa-facebook-sign"></i>
                        <span>Friends</span>
                    </a>
                </div>

                <div class="col-sm-6 action-nav-button">
                    <a href="#" title="Followers">
                        <i class="fa fa-twitter"></i>
                        <span>Followers</span>
                    </a>
                    <span class="triangle-button blue"><span class="inner">+8</span></span>
                </div>
            </div>

        </div>
    </div>

    <div class="col-md-9">
        <!-- find me in partials/big_chart -->

        <div class="box">
            <div class="box-header">
                <div class="title">Charts</div>
                <ul class="box-toolbar">
                    <li class="toolbar-link">
                        <a href="#" data-toggle="dropdown"><i class="fa fa-cog"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-plus-sign"></i> Add</a></li>
                            <li><a href="#"><i class="fa fa-remove-sign"></i> Remove</a></li>
                            <li><a href="#"><i class="fa fa-pencil"></i> Edit</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="box-content padded">
                <div class="row">
                    <div class="col-md-4 separate-sections" style="margin-top: 5px;">

                        <div class="row">
                            <div class="col-md-12">
                                <div class="dashboard-stats">
                                    <ul class="list-inline">
                                        <li class="glyph"><i class="fa fa-bolt fa-2x"></i></li>
                                        <li class="count">973,119</li>
                                    </ul>

                                    <div class="progress">
                                        <div class="progress-bar progress-blue tip" title="80%" data-percent="80"></div>
                                    </div>

                                    <div class="stats-label">Total Visits</div>
                                </div>
                            </div>
                        </div>

                        <div class="row" style="margin-top:30px;">
                            <div class="col-md-6">
                                <div class="dashboard-stats small">
                                    <ul class="list-inline">
                                        <li class="glyph"><i class="fa fa-user"></i></li>
                                        <li class="count">8800</li>
                                    </ul>
                                    <div class="progress">
                                        <div class="progress-bar progress-blue tip" title="65%" data-percent="65"></div>
                                    </div>

                                    <div class="stats-label">New Visitors</div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="dashboard-stats small">
                                    <ul class="list-inline">
                                        <li class="glyph"><i class="fa fa-eye-open"></i></li>
                                        <li class="count">25668</li>
                                    </ul>
                                    <div class="progress">
                                        <div class="progress-bar progress-blue tip" title="80%" data-percent="80"></div>
                                    </div>
                                    <div class="stats-label">Page Views</div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-8">
                        <div class="sine-chart" id="xchart-sine"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <div class="title">Full calendar</div>
            </div>

            <div class="box-content">
                <div id="calendar"></div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <span class="title">News with avatars (scrollable box)</span>
                <ul class="box-toolbar">
                    <li><span class="label label-blue">178</span></li>
                </ul>
            </div>
            <div class="box-content scrollable" style="height: 552px; overflow-y: auto">
                <!-- find me in partials/news_with_icons -->

                <div class="box-section news with-icons">
                    <div class="avatar blue"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>06</span> jan
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar green"><i class="fa fa-lightbulb fa-2x"></i></div>
                    <div class="news-time">
                        <span>11</span> feb
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Ruby on Rails 4.0</a></div>
                        <div class="news-text">
                            Rails 4.0 is still unfinished, but it is shaping up to become a great release ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar purple"><i class="fa fa-mobile-phone fa-2x"></i></div>
                    <div class="news-time">
                        <span>04</span> mar
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">All about SCSS</a></div>
                        <div class="news-text">
                            Sass makes CSS fun again. Sass is an extension of CSS3, adding nested rules ...
                        </div>
                    </div>
                </div>


                <div class="box-section news with-icons">
                    <div class="avatar cyan"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>22</span> dec
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>


                <!-- find me in partials/news_with_icons -->

                <div class="box-section news with-icons">
                    <div class="avatar blue"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>06</span> jan
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar green"><i class="fa fa-lightbulb fa-2x"></i></div>
                    <div class="news-time">
                        <span>11</span> feb
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Ruby on Rails 4.0</a></div>
                        <div class="news-text">
                            Rails 4.0 is still unfinished, but it is shaping up to become a great release ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar purple"><i class="fa fa-mobile-phone fa-2x"></i></div>
                    <div class="news-time">
                        <span>04</span> mar
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">All about SCSS</a></div>
                        <div class="news-text">
                            Sass makes CSS fun again. Sass is an extension of CSS3, adding nested rules ...
                        </div>
                    </div>
                </div>


                <div class="box-section news with-icons">
                    <div class="avatar cyan"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>22</span> dec
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>


                <!-- find me in partials/news_with_icons -->

                <div class="box-section news with-icons">
                    <div class="avatar blue"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>06</span> jan
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar green"><i class="fa fa-lightbulb fa-2x"></i></div>
                    <div class="news-time">
                        <span>11</span> feb
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Ruby on Rails 4.0</a></div>
                        <div class="news-text">
                            Rails 4.0 is still unfinished, but it is shaping up to become a great release ...
                        </div>
                    </div>
                </div>

                <div class="box-section news with-icons">
                    <div class="avatar purple"><i class="fa fa-mobile-phone fa-2x"></i></div>
                    <div class="news-time">
                        <span>04</span> mar
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">All about SCSS</a></div>
                        <div class="news-text">
                            Sass makes CSS fun again. Sass is an extension of CSS3, adding nested rules ...
                        </div>
                    </div>
                </div>


                <div class="box-section news with-icons">
                    <div class="avatar cyan"><i class="fa fa-ok fa-2x"></i></div>
                    <div class="news-time">
                        <span>22</span> dec
                    </div>
                    <div class="news-content">
                        <div class="news-title"><a href="#">Twitter Bootstrap v3.0 is coming!</a></div>
                        <div class="news-text">
                            With 2.2.2 out the door, our attention has shifted almost entirely to the next major update to the project ...
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <ul class="chat-box timeline">

            <li class="arrow-box-left gray">
                <div class="avatar"><img class="avatar-small" src="../../images/avatars/avatar1.jpg" /></div>
                <div class="info">
      <span class="name">
        <span class="label label-green">COMMENT</span> <strong class="indent">Alex</strong> posted a comment on this task: <strong>Core Admin</strong>
      </span>
                    <span class="time"><i class="fa fa-time"></i> 3 minutes ago</span>
                </div>
                <div class="content">
                    <blockquote>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </blockquote>
                    <div>
                        <a href="#"><i class="fa fa-paper-clip"></i> <b>project_news.docx</b></a>
                    </div>
                </div>
            </li>

            <li class="arrow-box-left gray">
                <div class="avatar"><img class="avatar-small" src="../../images/avatars/avatar2.jpg" /></div>
                <div class="info">
      <span class="name">
        <span class="label label-blue">TASK</span> <strong class="indent">Michael</strong> completed this task: <strong class="strikethrough">Core Admin</strong>
      </span>
                    <span class="time"><i class="fa fa-time"></i> 6 minutes ago</span>
                </div>
            </li>

            <li class="arrow-box-left gray">
                <div class="avatar"><img class="avatar-small" src="../../images/avatars/avatar3.jpg" /></div>
                <div class="info">
      <span class="name">
        <span class="label label-purple">FILE</span> <strong class="indent">Alex</strong> added 3 new files in project: <strong>Core Admin</strong>
      </span>
                    <span class="time"><i class="fa fa-time"></i> 12 minutes ago</span>
                </div>
                <div class="content">
                    <ul class="thumbnails padded">

                        <li class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/240x100" alt="">
                            </a>
                        </li>

                        <li class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/240x100" alt="">
                            </a>
                        </li>

                        <li class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/240x100" alt="">
                            </a>
                        </li>

                    </ul>
                </div>
            </li>
        </ul>

        <div class="box closable-chat-box">
            <div class="box-content padded">

                <div class="fields">
                    <div class="avatar"><img class="avatar-small" src="../../images/avatars/avatar2.jpg" /></div>
                    <ul>
                        <li><b>Add a comment for project <a href="#">Core Admin</a></b></li>
                        <li class="note">Click on the textarea below to expand it!</li>
                    </ul>
                </div>

                <form class="fill-up" action="/">

                    <div class="chat-message-box">
                        <textarea name="ttt" id="ttt" rows="5" placeholder="add a comment (click to expand!)"></textarea>
                    </div>

                    <div class="clearfix actions">
                        <span class="note">An optional note can go here</span>
                        <div class="pull-right faded-toolbar">
                            <a href="#" class="tip" title="Attach files"><i class="fa fa-paper-clip"></i></a>
                            <a href="#" class="btn btn-blue btn-xs">Send</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

</div>
</div>

<?php echo $this->layout()->content ?>
</body>
</html>