<?php
/*
 * Add scripts and css files
 */

// Modernizr
$this->headScript()->prependFile('/library/modernizr/modernizr.min.js'); // modernizr

// Twitter Bootstrap 3
$this->MinifyHeadScript()->appendFile('/library/bootstrap/js/bootstrap.min.js');
$this->minifyHeadLink()->appendStylesheet('/library/bootstrap/css/bootstrap.min.css');
$this->minifyHeadLink()->appendStylesheet('/library/bootstrap/css/bootstrap-theme.min.css');

// Additional Twitter Bootstrap 3
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/bootstrap-3-additional.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/bootstrap-3-additional-theme.css');

// Font-AweSome
$this->minifyHeadLink()->appendStylesheet('/library/font-awesome/css/font-awesome.min.css');

// js library files
$this->MinifyHeadScript()->appendFile('/library/bootstrap-magnify/js/bootstrap-magnify.min.js'); // twitter bootsrap magnify
//$this->headScript()->appendFile('/library/jquery.snowfall/snowfall.min.jquery.js'); // snowfall library
$this->MinifyHeadScript()->appendFile('/library/jquery.page-scroller/jquery.page-scroller.js'); // page-scroller block js

// js app files
$this->MinifyHeadScript()->appendFile('/data-content/data-themes/layout-common/js/app.js');
$this->MinifyHeadScript()->appendFile('/data-content/data-themes/layout-common/js/common.js');
$this->MinifyHeadScript()->appendFile('/data-content/data-themes/layout-default/js/script.js');

if ((Zend_Auth::getInstance()->hasIdentity())) {
    //chat script
    $this->MinifyHeadScript()->appendFile('/js/chat.js'); // chat block logic
}

// IE js files
$this->headScript()->appendFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'));
$this->headScript()->appendFile('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
//$this->headScript()->appendFile('/library/ie7/IE7.js', 'text/javascript', array('conditional' => 'lt IE 7'));

// css library files
$this->minifyHeadLink()->appendStylesheet('/library/bootstrap-magnify/css/bootstrap-magnify.min.css'); // twitter bootsrap magnify
$this->minifyHeadLink()->appendStylesheet('/library/jquery.page-scroller/css/page-srcoller.css'); // page-scroller block styles

// css app files
$this->minifyHeadLink()->appendStylesheet('/css/style.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/items.css');
//$this->minifyHeadLink()->appendStylesheet('/css/forms.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/style.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-default/css/style.css');
$this->minifyHeadLink()->appendStylesheet('/css/chat.css');

// IE css files
$this->headLink()->appendStylesheet('/data-content/data-themes/layout-common/css/ie9.css', 'screen', 'IE 9');
$this->headLink()->appendStylesheet('/data-content/data-themes/layout-common/css/ie8.css', 'screen', 'IE 8');
$this->headLink()->appendStylesheet('/data-content/data-themes/layout-common/css/ie7.css', 'screen', 'IE 7');

// google fonts
//$this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Faster+One', 'screen, print');

//temp
// Share block script
//$this->headScript()->appendFile('/js/share.js');

// Script for count down block
//$this->headScript()->appendFile('/library/jquery.countdown/jquery.countdown.min.js');
//$this->headScript()->appendFile('/library/jquery.countdown/jquery.countdown-ru.js');
//$this->headLink()->appendStylesheet('/library/jquery.countdown/css/jquery.countdown.css');

?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>

    <?php echo $this->jQuery(); ?>
</head>
<body>
<div id="page-wrapper">
    <div id="page">
        <div id="main-wrapper" class="container">
            <?php //echo $this->showMessages(); ?>
            <div class="row m-t-15">
                <div class="col-lg-12">
                    <div class="text-center">
                        <img class="img-responsive img-size-365 center-block" src="/img/or-logo-round.png"/>
                    </div>
                </div>
            </div>
            <div class="row m-t-15">
                <div class="col-lg-12">
                    <div class="panel">
                        <div class="panel-body center-block text-center">
                            <div class="error-template text-center">
                                <h1><?php echo $this->translate('УПС!'); ?></h1>

                                <h2><?php echo $this->translate('Ошибка 404. Страница не найдена!'); ?></h2>

                                <div class="error-details">
                                    <?php echo $this->translate(
                                        'Приносим свои извинения. На сайте произошла ошибка, запрашиваемая страница не найдена!'
                                    ); ?>
                                </div>
                                <div class="error-actions m-t-15">
                                    <a href="<?php echo $this->baseUrl(); ?>" class="btn btn-primary btn-lg">
                                        <i class="fa fa-home"></i> <?php echo $this->translate(
                                            'Перейти на главную страницу?'
                                        ); ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row m-t-15">
                <div class="col-md-12">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="background-wrapper" class="background-wrapper"></div>

<!-- scripts -->
<?php //echo $this->headScript() ?>
<?php echo $this->minifyHeadScript() ?>

<?php echo $this->render("common/site-heart-js.phtml") ?>
<?php echo $this->render("common/analytics-tracking-js-layout.phtml") ?>
<!-- ./ scripts -->
</body>
</html>