<?php

// js library files
$this->headScript()->prependFile("/library/modernizr/modernizr.min.js"); // modernizr


//$this->MinifyHeadScript()->appendFile("/library/jquery.page-scroller/jquery.page-scroller.js"); // page-scroller block js

// Twitter Bootstrap 3
$this->MinifyHeadScript()->appendFile("/library/bootstrap/js/bootstrap.min.js");
$this->minifyHeadLink()->appendStylesheet("/library/bootstrap/css/bootstrap.min.css");
$this->minifyHeadLink()->appendStylesheet("/library/bootstrap/css/bootstrap-theme.min.css");

// Bootstrap DatePicker
//$this->MinifyHeadScript()->appendFile("/library/bootstrap-datepicker/js/bootstrap-datepicker.js");
//$this->minifyHeadLink()->appendStylesheet("/library/bootstrap-datepicker/css/datepicker3.css");

// Bootstrap DateTimePicker
//$this->MinifyHeadScript()->appendFile("/library/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js");
//$this->minifyHeadLink()->appendStylesheet("/library/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css");

// Font-AweSome
$this->minifyHeadLink()->appendStylesheet("/library/font-awesome/css/font-awesome.min.css");

// Gritter for jQuery
//$this->MinifyHeadScript()->appendFile("/library/jquery.gritter/js/jquery.gritter.min.js");
//$this->minifyHeadLink()->appendStylesheet("/library/jquery.gritter/css/jquery.gritter.css");

// Moment.js
//$this->MinifyHeadScript()->appendFile("/library/moment/moment-with-locales.min.js");

// Full Calendar
//$this->MinifyHeadScript()->appendFile("/library/fullcalendar/fullcalendar.min.js");
//$this->minifyHeadLink()->appendStylesheet("/library/fullcalendar/fullcalendar.min.css");

// jQuery Sparkline
//$this->MinifyHeadScript()->appendFile("/library/jquery.sparkline/js/jquery.sparkline.min.js");

// jQuery tags-input
//$this->MinifyHeadScript()->appendFile("/library/jquery.tagsinput/js/jquery.tagsinput.min.js");
//$this->minifyHeadLink()->appendStylesheet("/library/jquery.tagsinput/css/jquery.tagsinput.css");

// jQuery Uniform
//$this->MinifyHeadScript()->appendFile("/library/jquery.uniform/js/jquery.uniform.min.js");

// iCheck
//$this->MinifyHeadScript()->appendFile("/library/icheck/js/icheck.min.js");
//$this->minifyHeadLink()->appendStylesheet("/library/icheck/css/all.css");

// WysiHtml5
//$this->MinifyHeadScript()->appendFile("/library/wysihtml5/js/wysihtml5-0.3.0.min.js");

// jquery.ibutton
//$this->MinifyHeadScript()->appendFile("/library/jquery.ibutton/js/jquery.metadata.js");
//$this->MinifyHeadScript()->appendFile("/library/jquery.ibutton/js/jquery.easing.1.3.js");
//$this->MinifyHeadScript()->appendFile("/library/jquery.ibutton/js/jquery.ibutton.min.js");

// combodate
//$this->MinifyHeadScript()->appendFile("/library/combodate/js/combodate.js");

// js app files
//$this->MinifyHeadScript()->appendFile("/js/app.js");
//$this->MinifyHeadScript()->appendFile("/js/common.js");
$this->MinifyHeadScript()->appendFile("/js/layout-admin.js");

// css app files
//$this->minifyHeadLink()->appendStylesheet('/css/style.css');
//$this->minifyHeadLink()->appendStylesheet('/css/items.css');
//$this->minifyHeadLink()->appendStylesheet('/css/forms.css');
$this->minifyHeadLink()->appendStylesheet('/css/layout-common.css');
$this->minifyHeadLink()->appendStylesheet('/css/layout-admin.css');


$this->minifyHeadLink()->appendStylesheet("/css/bootstrap-3-additional.css"); // twitter bootstrap additional css
$this->minifyHeadLink()->appendStylesheet("/css/bootstrap-3-additional-theme.css"); // twitter bootstrap additional theme css

$this->minifyHeadLink()->appendStylesheet('/css/action-nav.css');
$this->minifyHeadLink()->appendStylesheet('/css/triangle-button.css');

$this->minifyHeadLink()->appendStylesheet('/css/buttons.css');
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>

    <?php echo $this->jQuery(); ?>
</head>
<body>
<div id="page-wrapper">
    <div id="page">
        <div class="container-fluid">
            <?php echo $this->render("layout-admin/header.phtml") ?>
            <div class="row">
                <?php echo $this->render("layout-admin/sidebar.phtml") ?>
                <?php echo $this->render("layout-admin/content.phtml") ?>
            </div>
        </div>
    </div>
</div>
<!-- scripts -->
<?php //echo $this->headScript() ?>
<?php echo $this->minifyHeadScript() ?>

<?php //echo $this->render("common/site-heart-js.phtml") ?>
<?php echo $this->render("common/analytics-tracking-js-layout.phtml") ?>
</body>
</html>