<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>

        <?php echo $this->headScript() ?>
        <!-- Google analytics -->
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-32674101-2']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <?php echo $this->render("admin_toolbar.phtml") ?>
        <div id="page_wrapper">
            <div id="page">
                <header id="header">
                    <?php echo $this->render("header.phtml") ?>
                </header>
                <div id="main_wrapper">
                    <div id="main" class="clearfix">

                        <!-- Content -->
                        <div id="content">
                            <?php echo $this->layout()->content ?>
                        </div>
                        <!-- Left sidebar -->
                        <div id="left_sidebar">
                            <?php echo $this->render("left_sidebar.phtml") ?>
                        </div>
                    </div>
                </div>
                <footer id="footer">
                    <?php echo $this->render("footer.phtml") ?>
                </footer>
            </div>
            <?php echo $this->render("back_to_top.phtml") ?>
            <?php echo $this->render("share_block.phtml") ?>
        </div>
    </body>
</html>