<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->minifyHeadLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <?php
        if ($this->showMasterPanel == 1) {
            echo $this->render("hd_master_toolbar.phtml");
        } elseif ($this->showMasterPanel == 2) {
            echo $this->render("hd_admin_toolbar.phtml");
        }
        ?>
        <div id="page_wrapper">
            <div id="page">
                <div id="header">
                    <?php echo $this->render("header.phtml") ?>
                </div>
                <div id="main_wrapper">
                    <div id="main" class="clearfix">

                        <!-- Content -->
                        <div id="content">
                            <?php echo $this->layout()->content ?>
                        </div>
                        <!-- Left sidebar -->
                        <div id="left_sidebar">
                            <?php echo $this->render("left_sidebar.phtml") ?>
                        </div>
                    </div>
                </div>
                <div id="footer">
                    <?php echo $this->render("footer.phtml") ?>
                </div>
            </div>
            <?php
            if ($this->lo_back_to_top) {
                echo $this->render("lo_back_to_top.phtml");
            }
            ?>
            <?php
            if ($this->lo_share_block) {
                echo $this->render("lo_share_block.phtml");
            }
            ?>
        </div>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-32674101-2']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
            
            $(document).ready(function(){
//                $('body').snowfall({flakeCount : 40, maxSpeed : 10, minSize : 1, maxSize : 3});
            });
        </script>
    </body>
</html>