<?php

// Modernizr
$this->headScript()->prependFile("/library/modernizr/modernizr.min.js"); // modernizr

// Twitter Bootstrap 3
$this->MinifyHeadScript()->appendFile("/library/bootstrap/js/bootstrap.min.js");
$this->minifyHeadLink()->appendStylesheet("/library/bootstrap/css/bootstrap.min.css");
$this->minifyHeadLink()->appendStylesheet("/library/bootstrap/css/bootstrap-theme.min.css");

// Additional Twitter Bootstrap 3
$this->minifyHeadLink()->appendStylesheet("/data-content/data-themes/layout-common/css/bootstrap-3-additional.css");
$this->minifyHeadLink()->appendStylesheet("/data-content/data-themes/layout-common/css/bootstrap-3-additional-theme.css");

// Font-AweSome
$this->minifyHeadLink()->appendStylesheet("/library/font-awesome/css/font-awesome.min.css");

// jQuery Clock plugin
$this->MinifyHeadScript()->appendFile("/library/jquery.clock/js/jquery.clock.js");
$this->minifyHeadLink()->appendStylesheet("/library/jquery.clock/css/digital.css");

// js app files
//$this->MinifyHeadScript()->appendFile("/data-content/data-themes/layout-common/js/app.js");
$this->MinifyHeadScript()->appendFile("/data-content/data-themes/layout-common/js/common.js");
$this->MinifyHeadScript()->appendFile("/data-content/data-themes/layout-admin/js/script.js");

// css app files
//$this->minifyHeadLink()->appendStylesheet('/css/style.css');
//$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/items.css');
//$this->minifyHeadLink()->appendStylesheet('/css/forms.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-common/css/style.css');
$this->minifyHeadLink()->appendStylesheet('/data-content/data-themes/layout-admin/css/style.css');

$this->minifyHeadLink()->appendStylesheet('/css/action-nav.css');
$this->minifyHeadLink()->appendStylesheet('/css/triangle-button.css');

$this->minifyHeadLink()->appendStylesheet('/css/buttons.css');
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>

    <?php echo $this->jQuery(); ?>
</head>
<body id="<?php echo $this->module . '-' . $this->controller . '-' . $this->action; ?>">
<div id="page-wrapper">
    <div id="page">
        <div class="container-fluid">
            <?php echo $this->render("layout-admin/header.phtml") ?>
            <div class="row">
                <?php echo $this->render("layout-admin/sidebar.phtml") ?>
                <?php echo $this->render("layout-admin/content.phtml") ?>
            </div>
        </div>
    </div>
</div>
<!-- scripts -->
<?php //echo $this->headScript() ?>
<?php echo $this->minifyHeadScript() ?>

<?php //echo $this->render("common/site-heart-js.phtml") ?>
<?php echo $this->render("common/analytics-tracking-js-layout.phtml") ?>
</body>
</html>