<?php
/*
 * Add scripts and css files
 */

// js library files
$this->headScript()->appendFile("/library/modernizr/modernizr.min.js"); // modernizr
$this->MinifyHeadScript()->appendFile(
    "/library/jquery.page-scroller/jquery.page-scroller.js"
); // page-scroller block js

// js app files
$this->MinifyHeadScript()->appendFile("/js/app.js");
$this->MinifyHeadScript()->appendFile("/js/common.js");
$this->MinifyHeadScript()->appendFile("/js/layout-forum.js");

// IE js files
$this->headScript()->appendFile(
    "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", 'text/javascript', array('conditional' => 'lt IE 9')
);
$this->headScript()->appendFile(
    "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js", 'text/javascript', array('conditional' => 'lt IE 9')
);

// css library files
$this->minifyHeadLink()->appendStylesheet("/library/normalize/normalize.css");
$this->minifyHeadLink()->appendStylesheet(
    "/library/jquery.page-scroller/css/page-srcoller.css"
); // page-scroller block styles

// css app files
$this->minifyHeadLink()->appendStylesheet('/css/layout-common.css');
$this->minifyHeadLink()->appendStylesheet('/css/layout-forum.css');

// IE css files
$this->headLink()->appendStylesheet("/css/ie9.css", 'screen', 'IE 9');
$this->headLink()->appendStylesheet("/css/ie8.css", 'screen', 'IE 8');
$this->headLink()->appendStylesheet("/css/ie7.css", 'screen', 'IE 7');

?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>

    <script src="/library/jquery/js/jquery-1.11.0.min.js" type="text/javascript"></script>
</head>
<body>
<div id="page-wrapper">
    <div id="page">
        <div id="header">
            <h2>Online-Racing.Net </h2>

            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand" href="#">Forum</a>
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->baseUrl() ?>">Home</a></li>
                        <li><a href="#">Link1</a></li>
                        <li><a href="#">Link2</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <hr style="color:gray">
        <div id="main-wrapper">
            <div id="main" class="clearfix">
                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->render("common/page-scroller-block.phtml"); ?>

<!-- scripts -->
<?php //echo $this->headScript() ?>
<?php echo $this->minifyHeadScript() ?>

<?php echo $this->render("common/site-heart-js.phtml") ?>
<?php echo $this->render("common/analytics-tracking-js-layout.phtml") ?>
<!-- ./ scripts -->
</body>