<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	
    <?php /**@var $this Zend_View */ ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <script type="text/javascript">
        // run function for clear "X" button
        $(function() {$(".x_field").addXbtn({

            });
        });
     </script>
 </head>
<body>
<?php echo $this->render("admin_toolbar.phtml") ?>
<div id="page_wrapper">
    <div id="page">
        <?php echo $this->render("header.phtml") ?>
        <div id="main_wrapper">
            <div id="main" class="clearfix">
                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>
                <div id="left_sidebar">
                    <?php echo $this->render("left_sidebar.phtml") ?>
                </div>
            </div>
        </div>
        <?php echo $this->render("footer.phtml")?>
    </div>
    <?php echo $this->render("back_to_top.phtml")?>
</div>
</body>
</html>