<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->minifyHeadLink() ?>
    <?php //echo $this->headScript() ?>
    <?php echo $this->minifyHeadScript() ?>
</head>
<body>
<!-- head-line -->
<?php echo $this->render("layout-default/head-line.phtml"); ?>
<!-- ./ head-line -->
<!-- ./ #page-wrapper -->
<div id="page-wrapper">
    <!-- #page -->
    <div id="page">
        <?php echo $this->render("layout-default/header.phtml") ?>
        <?php
        $default_layout_sidebar = Zend_Registry::get('default_layout_sidebar');

        switch (strtoupper($default_layout_sidebar)) {
            case 'RIGHT':
                echo $this->render("layout-default/content-right-sidebar.phtml");
                break;
            case 'LEFT':
                echo $this->render("layout-default/content-left-sidebar.phtml");
                break;
            case 'BOTH-SIDEBAR':
                echo $this->render("layout-default/content-both-sidebar.phtml");
                break;
            case 'NO-SIDEBAR':
                echo $this->render("layout-default/content-no-sidebar.phtml");
                break;
            default:
                echo $this->render("layout-default/content-right-sidebar.phtml");
                break;
        }
        ?>
        <?php echo $this->render("layout-default/footer.phtml") ?>
    </div>
    <!-- ./ #page -->
</div>
<!-- ./ #page-wrapper -->
<?php
if ($this->page_scroller_block) {
    echo $this->render("common/page-scroller-block.phtml");
}
?>
<?php
if ($this->slide_out_tabs_block) {
    echo $this->render("layout-default/blocks/slide-out-tabs-block.phtml");
}
?>
<div id="background-wrapper" class="background-wrapper"></div>
<?php echo $this->render("common/site-heart-js.phtml") ?>
<?php echo $this->render("common/analytics-tracking-js-layout.phtml") ?>
</body>
</html>