<div class="sidebar_box">
    <div class="sidebar_box_title">
        <?php echo $this->translate('Ближайшее событие') ?>
    </div>
    <div class="sidebar_box_content">
        <script type="text/javascript">
            // countdown clock script
            $(function() {
                $('#countdown_dashboard').countDown({
                    targetDate: {
                        'day':1,
                        'month':2,
                        'year':2013,
                        'hour':19,
                        'min':0,
                        'sec':0,
                        // time set as UTC
                        'utc':true
                    }
                });
            });
        </script>
        Открытие сайта
        <div id="countdown_dashboard">
            <div class="dash weeks_dash">
                <span class="dash_title">Нед.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash days_dash">
                <span class="dash_title">Дн.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash hours_dash">
                <span class="dash_title">Час.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash minutes_dash">
                <span class="dash_title">Мин.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash seconds_dash">
                <span class="dash_title">Сек.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>
        </div>
    </div>
</div>
<!--
<div class="sidebar_box">
    <div class="sidebar_box_title">
        Поиск (Не работает)
    </div>
    <div class="sidebar_box_content">
        <form class="form-search" style="margin:5px 0;">
            <div class="input-append">
                <input type="text" class="span2 search-query" style="width:115px;">
                <button type="submit" class="btn" style="width:70px;">Поиск</button>
            </div>
        </form>
    </div>
</div>-->
<!-- start chat -->
<div id="chat" class="sidebar_box">
    <div class="sidebar_box_title">
        Чат (Не работает)
    </div>
    <div class="sidebar_box_content">
        <div id="chat_messages_box">

            <div class="chat_message_box">
                <div class="chat_mesage_date">
                    27.07.2012 15:46
                </div>
                <div class="chat_mesage_nickname">
                    <a href="<?php echo $this->baseUrl('user/info/') . 1 ?>" target="_BLINK"><i class="icon-user icon-black"></i></a><a href="javascript:void('Apply to')" class="nick">dark_diesel</a>
                </div>
                <div class="chat_mesage_message">
                    Приветствую всех на нашем портале. Регистрируйтесь и коментируйте работу нашего сайта.
                </div>
            </div>
        </div>
        <?php
        if (Zend_Auth::getInstance()->hasIdentity()) { ?>
        <div id="chat_textarea_count">500</div>
        <?php
            $form = new Application_Form_UserChatForm();
            echo $form;
        }
        ?>
    </div>
</div>
<!-- end chat -->
<!--
<div class="sidebar_box">
    <div class="sidebar_box_title">
        Таблица (Не работает)
    </div>
    <div class="sidebar_box_content">
        <table style="width:100%">
            <tr>
                <td>№</td>
                <td>Пилот</td>
                <td>Очки</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Имя Фамилия</td>
                <td>25</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Имя Фамилия</td>
                <td>18</td>
            </tr>
        </table>
    </div>
</div>-->