<div class="sidebar_box">
    <div class="sidebar_box_title">
        Ближайшее событие
    </div>
    <div class="sidebar_box_content">
        <script type="text/javascript">
            // countdown clock script
            $(function() {
                $('#countdown_dashboard').countDown({
                    targetDate: {
                        'day':1,
                        'month':2,
                        'year':2013,
                        'hour':19,
                        'min':0,
                        'sec':0,
                        // time set as UTC
                        'utc':true
                    }
                });
            });
        </script>
        Открытие сайта
        <div id="countdown_dashboard">
            <div class="dash weeks_dash">
                <span class="dash_title">Нед.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash days_dash">
                <span class="dash_title">Дн.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash hours_dash">
                <span class="dash_title">Час.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash minutes_dash">
                <span class="dash_title">Мин.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>

            <div class="dash seconds_dash">
                <span class="dash_title">Сек.</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
            </div>
        </div>
    </div>
</div>
<div class="sidebar_box">
    <div class="sidebar_box_title">
        Поиск (Не работает)
    </div>
    <div class="sidebar_box_content">
        <form class="form-search" style="margin:5px 0;">
            <div class="input-append">
                <input type="text" class="span2 search-query" style="width:115px;">
                <button type="submit" class="btn" style="width:70px;">Поиск</button>
            </div>
        </form>
    </div>
</div>
<div class="sidebar_box">
    <div class="sidebar_box_title">
        Чат (Не работает)
    </div>
    <div class="sidebar_box_content">
        <input class="x_field"/>
    </div>
</div>
<div class="sidebar_box">
    <div class="sidebar_box_title">
        Таблица (Не работает)
    </div>
    <div class="sidebar_box_content">
        <table style="width:100%">
            <tr>
                <td>№</td>
                <td>Пилот</td>
                <td>Очки</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Имя Фамилия</td>
                <td>25</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Имя Фамилия</td>
                <td>18</td>
            </tr>
        </table>
    </div>
</div>