<div class="sidebar_box">
    <div class="sidebar_box_title">
        <i class="icon-plane icon-white"></i> <?php echo $this->translate('Ближайшее событие') ?>
    </div>
    <div class="sidebar_box_content">
        <script type="text/javascript">
            $(document).ready(function(){
                var newYear = new Date(); 
                newYear = new Date(2012, 12 - 1 ,14, 19, 30, 45); 
                $('#countdown_dashboard').countdown({until: newYear, format: 'ODHMS', description: 'Осталось до отркытия сайта!'});
            });
        </script>

        <div id="countdown_dashboard"></div>
    </div>
</div>