<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	
    <?php /**@var $this Zend_View */ ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
	
 </head>
<body>
<div id="admin_toolbar">
    <ul id="admin_menu">
        <li class="home"><a href="">Home</a></li>
        <li><a href="/">Link1</a></li>
        <li><a href="/">Link2</a></li>
    </ul>
</div>
<div id="page_wrapper">
    <div id="page">
        <?php echo $this->render("header.phtml") ?>
        <div id="main_wrapper">
            <div id="main" class="clearfix">
                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>
                <div id="left_sidebar">
                    <div class="sidebar_container">
                        <div class="container_title">До открытия сайта осталось:</div>
                        <div class="container_content">
                            <div id="countdown_dashboard">
                                <div class="dash weeks_dash">
                                    <span class="dash_title">weeks</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash days_dash">
                                    <span class="dash_title">days</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash hours_dash">
                                    <span class="dash_title">hours</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash minutes_dash">
                                    <span class="dash_title">minutes</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash seconds_dash">
                                    <span class="dash_title">seconds</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                        Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .Sidebar .
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->render("footer.phtml")?>
    </div>

    <p id="back-top">
        <a href="#top"><span></span>На подиум!</a>
    </p>
</div>
</body>
</html>