<div id="box_main_menu">
	<ul id="main_menu">
		<li><a href="<?php echo $this->baseUrl("")?>" class="current">Главная</a></li>
		<li><a href="<?php echo $this->baseUrl("")?>">Чемпионат</a></li>
		<li><a href="<?php echo $this->baseUrl("")?>">Гонщики</a></li>
		<li><a href="<?php echo $this->baseUrl("")?>">Статьи</a></li>
                <li class="expanded"><a href="<?php echo $this->baseUrl("")?>">Файлы</a>
                    <ul class="menu">
                        <li class="first leaf"><a href="#" title="">Игры</a></li>
                        <li class="leaf"><a href="#" title="">Плагины</a></li>
                        <li class="last leaf"><a href="#" title="">Мануалы</a></li>
                    </ul>
                </li>
		<li><a href="<?php echo $this->baseUrl("")?>">Форум</a></li>
	</ul>
</div>