<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	
    <?php /**@var $this Zend_View */ ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
	<script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32674101-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
 </head>
<body>
<!--<div id="admin_toolbar">
    <ul id="admin_menu">
        <li class="home"><a href="">Home</a></li>
        <li><a href="/">Link1</a></li>
        <li><a href="/">Link2</a></li>
    </ul>
</div>-->
<div id="page_wrapper">
    <div id="page">
        <?php echo $this->render("header.phtml") ?>
        <div id="main_wrapper">
            <div id="main" class="clearfix">
                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>
                <div id="left_sidebar">
                    <div class="sidebar_box">
                        <div class="sidebar_box_title">
                            До открытия сайта осталось:
                        </div>
                        <div class="sidebar_box_content">
                            <div id="countdown_dashboard">
                                <div class="dash weeks_dash">
                                    <span class="dash_title">weeks</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash days_dash">
                                    <span class="dash_title">days</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash hours_dash">
                                    <span class="dash_title">hours</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash minutes_dash">
                                    <span class="dash_title">minutes</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>

                                <div class="dash seconds_dash">
                                    <span class="dash_title">seconds</span>
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->render("footer.phtml")?>
    </div>

    <p id="back-top">
        <a href="#top"><span></span>На подиум!</a>
    </p>
</div>
</body>
</html>