<div id="box_main_menu">
    <ul id="main_menu" class="main_menu">
        <li><a href="<?php echo $this->baseUrl("") ?>" class="current"><?php echo $this->translate('Главная') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Чемпионат') ?></a></li>
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Гонщики') ?></a></li>
        <li class="expanded">
            <a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Статьи') ?></a>
            <ul class="menu">
                <li class="leaf"><a href="#" title=""><?php echo $this->translate('Настройка болида') ?></a></li>
            </ul>
        </li>
        <li class="expanded">
            <a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Файлы') ?></a>
            <ul class="menu">
                <li class="leaf"><a href="#" title=""><?php echo $this->translate('Игры') ?></a></li>
                <li class="leaf"><a href="#" title=""><?php echo $this->translate('Плагины') ?></a></li>
                <li class="leaf"><a href="#" title=""><?php echo $this->translate('Мануалы') ?></a></li>
            </ul>
        </li>
        <li><a href="<?php echo $this->baseUrl("") ?>"><?php echo $this->translate('Форум') ?></a></li>
    </ul>
</div>