<?php if ($this->showMasterPanel == 1) {?>
<div id="admin_toolbar">
	<ul id="admin_menu">
		<li class="home"><a href="<?php echo $this->baseUrl('index/index'); ?>">Home</a></li>
		<li class="expanded">
                    <a href="<?php echo $this->baseUrl('article/index'); ?>">Контент</a>
                    <ul class="menu">
                        <li><a href="<?php echo $this->baseUrl('article/add'); ?>">Добавить</a></li>
                        <li><a href="<?php echo $this->baseUrl('article/delete'); ?>">Удалить</a></li>
                        <li><a href="<?php echo $this->baseUrl('article/edit'); ?>">Добавить</a></li>
                    </ul>
                </li>
		<li class="expanded">
                    <a href="<?php echo $this->baseUrl('user/index'); ?>">Пользователи</a>
                    <ul class="menu">
                        <li><a href="<?php echo $this->baseUrl('user/index'); ?>">Просмотр</a></li>
                    </ul>
                </li>
	</ul>
</div>
<?php }?>