<div class="moving_text">
    <marquee behavior="scroll" direction="left">
        <div>
            <ul class="header_news">
                <li><a href="<?php echo $this->baseUrl('user/register') ?>">Регистрируйтесь</a> на нашем портале</li>
                <li>Если вы нашли баг, пожалуйста сообщите мне (Igor.Peshkov@gmail.com)</li>
            </ul>
        </div>
    </marquee> 
</div>