<a href="http://vk.com/OnlineRacingNet" target="_blank"><img src="<?php echo $this->baseUrl('img/soc_net/vk.gif'); ?>" /></a>
<a href="http://www.facebook.com/OnlineRacingNet" target="_blank"><img src="<?php echo $this->baseUrl('img/soc_net/fb.gif'); ?>" /></a>
<a href="http://twitter.com/OnlineRacingnet" target="_blank"><img src="<?php echo $this->baseUrl('img/soc_net/tw.gif'); ?>" /></a>
<a href="http://www.youtube.com/user/OnlineRacingNet" target="_blank"><img src="<?php echo $this->baseUrl('img/soc_net/yt.gif'); ?>" /></a>