<div id="user_toolbar">
    <ul id="user_menu">
        <li>
            <span><?php echo $this->translate('Добро пожаловать') ?>,</span>
        </li>
        <li>
            <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
                <?php $storage_data = Zend_Auth::getInstance()->getStorage('online-racing')->read(); ?>
                <span><a href="<?php echo $this->baseUrl('user/info/') . $storage_data->id; ?>"><?php echo Zend_Auth::getInstance()->getStorage()->read()->login ?></a></span>
            <?php } else { ?>
                <span><a href="<?php echo $this->baseUrl('user/login'); ?>"><?php echo $this->translate('Гость') ?></a></span>
            <?php } ?>
        </li>
    </ul>
    <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
        <div class="user">
            <div class="btn-group dropdown">
                <a class="btn btn-primary" href="<?php echo $this->baseUrl('user/logout'); ?>"><i class="icon-user icon-white"></i> <?php echo $this->translate('Выйти') ?></a>
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->baseUrl('user/info/') . $storage_data->id; ?>"><i class="icon-briefcase"></i> <?php echo $this->translate('Профиль') ?></a><li>
                    <li><a href="<?php echo $this->baseUrl('user/message'); ?>"><i class="icon-envelope"></i> <?php echo $this->translate('Сообщения') ?></a><li>
                    <li><a href="<?php echo $this->baseUrl('user/settings'); ?>"><i class="icon-wrench"></i> <?php echo $this->translate('Настройки') ?></a></li>
                    <li><a href="<?php echo $this->baseUrl('user/edit'); ?>"><i class="icon-edit"></i> <?php echo $this->translate('Редактировать') ?></a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->baseUrl('user/logout'); ?>"><i class="icon-remove"></i> <?php echo $this->translate('Сообщения') ?></a></li>
                </ul>
            </div>
        </div>
    <?php } else { ?>
        <div class="login">
            <div class="btn-group dropdown">
                <a class="btn btn-primary" href="<?php echo $this->baseUrl('user/login'); ?>"><i class="icon-user icon-white"></i> <?php echo $this->translate('Войти') ?></a>
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                        <?php
                        $form = new Application_Form_UserLoginForm();
                        echo $form;
                        ?>
                        <hr style="margin:20px 0 10px 0">
                        <blockquote>
                            <p><a class="reg_link" href="<?php echo $this->baseUrl('user/register') ?>"><?php echo $this->translate('Регистрация') ?></a></p>
                            <p><a class="reg_link" href="<?php echo $this->baseUrl('user/restorepasswd') ?>"><?php echo $this->translate('Забыли пароль?') ?></a></p>
                        </blockquote>
                    </li>
                </ul>
            </div>
        </div>
    <?php } ?>
</div>