<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/country/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'country', 'add')) : ?>
                    <?php
                    $adminCountryAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'country', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminCountryAddUrl; ?>" class="btn btn-xs btn-primary pull-right">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить страну'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="country-id">
                        <span>ID</span>
                    </th>
                    <th class="country-native-name">
                        <span><?= $this->t('Родное название'); ?></span>
                    </th>
                    <th class="country-english-name">
                        <span><?= $this->t('Английское название'); ?></span>
                    </th>
                    <th class="country-abreviation">
                        <span><?= $this->t('Аббревиатура'); ?></span>
                    </th>
                    <th class="country-round-image">
                        <span><?= $this->t('Круговая картинка'); ?></span>
                    </th>
                    <th class="country-glowssy-wave-image">
                        <span><?= $this->t('Волнистая картинка'); ?></span>
                    </th>
                    <th class="country-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->countryData) : ?>
                    <?php foreach ($this->countryData as $country): ?>
                        <?php
                        // check access and generate link for admin/country/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'country', 'id')) {
                            $adminCountryIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'country', 'action' => 'id',
                                    'countryID' => $this->escape($country['ID'])), 'adminCountryID'
                            );
                        } else {
                            $adminCountryIdUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="country-id">
                                <span>
                                    <a href="<?= $adminCountryIdUrl; ?>">
                                        <?= $this->escape($country['ID']); ?>
                                    </a>
                                </span>
                            </td>
                            <td class="country-native-name">
                                <span>
                                    <a href="<?= $adminCountryIdUrl; ?>">
                                        <?= $this->escape($country['NativeName']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="country-english-name">
                                <span>
                                    <a href="<?= $adminCountryIdUrl; ?>">
                                        <?= $this->escape($country['EnglishName']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="country-abreviation">
                                <span>
                                    <a href="<?= $adminCountryIdUrl ?>">
                                        <?= $this->escape($country['Abbreviation']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="country-round-image">
                                <span>
                                    <img src="<?= $this->baseUrl($this->escape($country['ImageRoundUrl'])) ?>"/>
                                </span>
                            </td>
                            <td class="country-wave-image">
                                <span>
                                    <imgsrc="<?= $this->baseUrl($this->escape($country['ImageGlossyWaveUrl'])) ?>" />
                                </span>
                            </td>
                            <td class="country-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Страна"), false)
                                        ->countryMenu($this->escape($country['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->countryData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->countryData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        );
                        ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>