<?php if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'country', 'add')) : ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="clearfix m-b-10">
                <?php
                $adminCountryAddUrl = $this->url(
                    array('module' => 'admin', 'controller' => 'country', 'action' => 'add'), 'default'
                );
                ?>
                <a href="<?php echo $adminCountryAddUrl; ?>" class="btn btn-success pull-right ">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Добавить страну'); ?>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->countryData) { ?>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-list"></i>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="country-id">
                                <span>ID</span>
                            </th>
                            <th class="country-native-name">
                                <span><?php echo $this->translate('Родное название'); ?></span>
                            </th>
                            <th class="country-english-name">
                                <span><?php echo $this->translate('Английское название'); ?></span>
                            </th>
                            <th class="country-abreviation">
                                <span><?php echo $this->translate('Аббревиатура'); ?></span>
                            </th>
                            <th class="country-round-image">
                                <span><?php echo $this->translate('Круговая картинка'); ?></span>
                            </th>
                            <th class="country-glowssy-wave-image">
                                <span><?php echo $this->translate('Волнистая картинка'); ?></span>
                            </th>
                            <th class="country-action">
                                <span><?php echo $this->translate('Действие'); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->countryData as $country): ?>
                            <?php
                            if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'country', 'id')) {
                                $adminCountryIdUrl = $this->url(
                                    array('module' => 'admin', 'controller' => 'country', 'action' => 'id',
                                        'countryID' => $this->escape($country['ID'])), 'adminCountryID'
                                );
                            } else {
                                $adminCountryIdUrl = '#';
                            }
                            ?>
                            <tr>
                                <td class="country-id">
                                    <span>
                                        <a href="<?php echo $adminCountryIdUrl; ?>">
                                            <?php echo $this->escape($country['ID']); ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="country-native-name">
                                    <span>
                                        <a href="<?php echo $adminCountryIdUrl; ?>">
                                            <?php echo $this->escape($country['NativeName']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="country-english-name">
                                    <span>
                                        <a href="<?php echo $adminCountryIdUrl; ?>">
                                            <?php echo $this->escape($country['EnglishName']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="country-abreviation">
                                    <span>
                                        <a href="<?php echo $adminCountryIdUrl ?>">
                                            <?php echo $this->escape($country['Abbreviation']) ?>
                                        </a>
                                    </span>
                                </td>
                                <td class="country-round-image">
                                    <span>
                                        <img src="<?php echo $this->baseUrl($this->escape($country['UrlImageRound'])) ?>">
                                    </span>
                                </td>
                                <td class="country-wave-image">
                                    <span>
                                        <img src="<?php echo $this->baseUrl($this->escape($country['UrlImageGlossyWave'])) ?>">
                                    </span>
                                </td>
                                <td class="country-action">
                                    <span>
                                        <?php
                                        echo $this->BlockConfigMenu($this->translate("Страна"), false)->countryMenu(
                                            $this->escape($country['ID']), true
                                        );
                                        ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="pull-right">
                        <?php echo $this->paginationControl(
                            $this->countryData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        );
                        ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>