<?php if ($this->countryData) { ?>
    <div class="m-b-10">
        <?php echo $this->countryDeleteForm; ?>
        <hr/>
    </div>
    <div class="block block-default block-ui-bordered">
        <div>
            <table class="table table-striped table-bordered article_table m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Родное название'); ?></span>
                    </td>
                    <td>
                        <span><?php echo $this->escape($this->countryData['NativeName']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Английское название'); ?></span>
                    </td>
                    <td>
                        <span><?php echo $this->escape($this->countryData['EnglishName']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Аббревиатура'); ?></span>
                    </td>
                    <td>
                        <span><?php echo $this->escape($this->countryData['Abbreviation']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold"
                        ><span><?php echo $this->translate('Круговая картинка'); ?></span
                            ></td>
                    <td>
                        <span><img
                                src="<?php echo $this->baseUrl($this->escape($this->countryData['UrlImageRound'])); ?>"></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?php echo $this->translate('Волнистая картинка'); ?></span>
                    </td>
                    <td>
                        <span><img
                                src="<?php echo $this->baseUrl($this->escape($this->countryData['UrlImageGlossyWave'])); ?>"></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php } ?>