<?php if ($this->countryData) : ?>
    <div class="block block-default block-ui-bordered">
        <?php
        echo $this->BlockConfigMenu($this->t("Страна"))->countryMenu(
            $this->escape($this->countryData['ID'])
        );
        ?>
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Родное название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->countryData['NativeName']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Английское название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->countryData['EnglishName']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Аббревиатура'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->countryData['Abbreviation']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Круговая картинка'); ?></span>
                    </td>
                    <td>
                        <span>
                            <img
                                src="<?= $this->baseUrl($this->escape($this->countryData['ImageRoundUrl'])); ?>" />
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->t('Волнистая картинка'); ?></span>
                    </td>
                    <td>
                        <span>
                            <img
                                src="<?= $this->baseUrl($this->escape($this->countryData['ImageGlossyWaveUrl'])); ?>" />
                        </span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->t('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->t('Страна'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->t('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->countryData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->countryData['DateCreate']) != $this->escape($this->countryData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->t('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->countryData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>