<div id="article_types_page" class="page">
    <div class="page_title"><?php echo $this->translate('Типы статей'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
            ?>
            <table class="table table-bordered table-hover table-striped articles_table">
                <thead>
                    <tr>
                        <th class="article_type_id"><span>#</span></th>
                        <th class="article_type_name"><span><?php echo $this->translate('Название'); ?></span></th>
                        <th class="article_type_descr"><span><?php echo $this->translate('Описание'); ?></span></th>
                        <th class="article_type_action articles_table_action"><span><?php echo $this->translate('Действие'); ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->paginator as $article_type): ?>
                        <tr>
                            <td class="article_type_id"><span><a href="<?php echo $this->baseUrl('article-type/id/' . $this->escape($article_type['id'])) ?>"><?php echo $this->escape($article_type['id']) ?></a></span></td>
                            <td class="article_type_name"><span><a href="<?php echo $this->baseUrl('article-type/id/' . $this->escape($article_type['id'])) ?>"><?php echo $this->escape($article_type['name']) ?></a></span></td>
                            <td class="article_type_descr"><span><?php echo $this->truncate($this->escape($article_type['description']))->toLength(200); ?></span></td>
                            <td class="article_type_action articles_table_action">
                                <span>
                                    <a href="<?php echo $this->baseUrl('article-type/id/' . $this->escape($article_type['id'])) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a><br/>
                                    <a href="<?php echo $this->baseUrl('article-type/edit/' . $this->escape($article_type['id'])) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
                                    <a href="<?php echo $this->baseUrl('article-type/delete/' . $this->escape($article_type['id'])) ?>"><i class="icon-remove"></i> <?php echo $this->translate('Удал.'); ?></a><br/>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
            ?>
            <?php
        } else {
            ?>
            <div class="alert alert-warning alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->translate('Типы статей на сайте не найдены!'); ?>
            </div>
        <?php } ?>
    </div>
</div>