<div id="article_type_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Тип статьи') . ' :: ' . $this->escape($this->article_type->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="article_type_item">
                <table class="table table-striped table-bordered article_table">
                    <tbody>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Название'); ?></span></td>
                            <td><span><?php echo $this->escape($this->article_type->name); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Описание'); ?></span></td>
                            <td><span><?php echo $this->escape($this->article_type->description); ?></span></td>
                        </tr>
                    </tbody>
                </table>
                <div class="article_controls">
                    <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
                        <a href = "<?php echo $this->baseUrl('article-type/edit/' . $this->escape($this->article_type->id)) ?>" class = "btn btn-small btn-inverse article_edit"><?php echo $this->translate('Редактировать') ?></a>
                        <a href = "<?php echo $this->baseUrl('article-type/delete/' . $this->escape($this->article_type->id)) ?>" class = "btn btn-small btn-inverse article_delete"><?php echo $this->translate('Удалить') ?></a>
                    <?php } ?>
                </div>
                <div class="article_info">
                    <div class="article_type_name article_info_item"><span class="bold_text"><?php echo $this->translate('Вид контента') ?>: </span><?php echo $this->translate('Тип статьи'); ?></div>
                    <div class="article_type_date_create article_info_item"><span class="bold_text"><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->article_type->date_create); ?></div>
                    <?php if ($this->escape($this->article_type->date_create) != $this->escape($this->article_type->date_edit)) { ?>
                        <div class="article_type_date_edit article_info_item"><span class="bold_text"><?php echo $this->translate('Редактировалось') ?>: </span><?php echo $this->escape($this->article_type->date_edit); ?></div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>