<div id="team_delete_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Удалить команду') . ' :: ' . $this->escape($this->team->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-warning alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Предупреждение!'); ?></h4>
                <?php echo $this->translate('Вы действительно хотите удалить команду ') . '"' . $this->escape($this->team->name) . '"?'; ?>
            </div>
            <?php echo $this->form; ?>
            <div class="team-item">
                <table class="table table-striped table-bordered article_table">
                    <tbody>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Название'); ?></span></td>
                            <td><span><?php echo $this->escape($this->team->name); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Описание'); ?></span></td>
                            <td><span><?php echo $this->escape($this->team->description); ?></span></td>
                        </tr>
                    </tbody>
                </table>
                <div class="article_info">
                    <div class="team_name article_info_item"><span class="bold_text"><?php echo $this->translate('Вид контента') ?>: </span><?php echo $this->translate('Команда'); ?></div>
                    <div class="team_date_create article_info_item"><span class="bold_text""><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->team->date_create); ?></div>
                    <?php if ($this->escape($this->team->date_create) != $this->escape($this->team->date_edit)) { ?>
                        <div class="team_date_edit article_info_item"><span class="bold_text""><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($this->team->date_edit); ?></div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>