<div id="team_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Команда') . ' :: ' . $this->escape($this->team->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-warning alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="team-item">
                <table class="table table-striped table-bordered article_table">
                    <tbody>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Название'); ?></span></td>
                            <td><span><?php echo $this->escape($this->team->name); ?></span></td>
                        </tr>
                        <tr>
                            <td class="header_column"><span><?php echo $this->translate('Описание'); ?></span></td>
                            <td><span><?php echo $this->escape($this->team->description); ?></span></td>
                        </tr>
                    </tbody>
                </table>
                <?php
                $edit_access = $this->checkUserAccess('team/edit');
                $delete_access = $this->checkUserAccess('team/delete');

                if ($edit_access || $delete_access) {
                    ?>
                    <div class="article_controls">
                        <?php if ($edit_access) { ?>
                            <a href = "<?php echo $this->baseUrl('team/edit/' . $this->escape($this->team->id)) ?>" class = "btn btn-sm btn-primary article_edit"><?php echo $this->translate('Редактировать') ?></a>
                        <?php } ?>
                        <?php if ($delete_access) { ?>
                            <a href = "<?php echo $this->baseUrl('team/delete/' . $this->escape($this->team->id)) ?>" class = "btn btn-sm btn-primary article_delete"><?php echo $this->translate('Удалить') ?></a>
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="article_info">
                    <div class="team_name article_info_item"><span class="bold_text"><?php echo $this->translate('Вид контента') ?>: </span><?php echo $this->translate('Команда'); ?></div>
                    <div class="team_date_create article_info_item"><span class="bold_text""><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->team->date_create); ?></div>
                    <?php if ($this->escape($this->team->date_create) != $this->escape($this->team->date_edit)) { ?>
                        <div class="team_date_edit article_info_item"><span class="bold_text""><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($this->team->date_edit); ?></div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>