<div id="events_page" class="page">
    <div class="page_title"><?php echo $this->translate('События'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/full_views_pagination_control.phtml');
            ?>
            <div class="content_types_data img-polaroid">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th <a href="_content_type_id"><span>#</span></th>
                            <th <a href="_content_type_name"><span><?php echo $this->translate('Название'); ?></span></th>
                            <th <a href="_content_type_descr"><span><?php echo $this->translate('Описание'); ?></span></th>
                            <th <a href="_content_type_date_event"><span><?php echo $this->translate('Дата события'); ?></span></th>
                            <th <a href="_content_type_url_event"><span><?php echo $this->translate('Ссылка события'); ?></th>
                            <th class="content_type_action"><span><?php echo $this->translate('Действие'); ?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $content_type): ?>
                            <tr>
                                <td <a href="_content_type_id"><span><a href="<?php echo $this->baseURL('event/id/' . $this->escape($content_type['id'])) ?>"><?php echo $this->escape($content_type['id']) ?></a></span></td>
                                <td <a href="_content_type_name"><span><a href="<?php echo $this->baseURL('event/id/' . $this->escape($content_type['id'])) ?>"><?php echo $this->escape($content_type['name']) ?></a></span></td>
                                <td <a href="_content_type_descr"><span><?php echo $this->truncate($this->escape($content_type['description']))->toLength(200); ?></span></td>
                                <td <a href="_content_type_date_event"><span><?php echo $this->escape($content_type['date_event']); ?></span></td>
                                <td <a href="_content_type_url_event"><span><a href="<?php echo $this->escape($content_type['url_event']); ?>"><?php echo $this->translate('Ссылка'); ?></a></span></td>
                                <td class="content_type_action">
                                    <span>
                                        <a href="<?php echo $this->baseUrl('event/id/' . $this->escape($content_type['id'])) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('event/edit/' . $this->escape($content_type['id'])) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('event/delete/' . $this->escape($content_type['id'])) ?>"><i class="icon-remove"></i> <?php echo $this->translate('Удал.'); ?></a><br/>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/full_views_pagination_control.phtml');
            ?>
            <?php
        } else {
            ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->translate('События на сайте не найдены!'); ?>
            </div>
        <?php } ?>
    </div>
</div>