<!-- end user_map block -->
<div class="sidebar_box" id="sidebar_date_calendar">
    <div class="sidebar_box_title">
        <i class="fa fa-user"></i> <?php echo $this->translate("Календарь") ?>
    </div>
    <div class="sidebar_box_content">
        <script language="JavaScript" src="http://101widgets.com/03001012/128/128"></script>
    </div>
    <hr />
</div>
<!-- start user_map block -->