<div class="sidebar_box">
    <div class="sidebar_box_title">
        <i class="fa fa-music"></i> <?php echo $this->translate('Онлайн радио') ?>
    </div>
    <div class="sidebar_box_content">
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="280" height="130" id="mainCS3" align="middle">
            <param name="allowScriptAccess" value="sameDomain" />
            <param name="allowFullScreen" value="false" />
            <param name="movie" value="http://gtiradio.ru/mainCS3.swf" /><param name="quality" value="high" />
            <embed src="http://gtiradio.ru/mainCS3.swf" width="280" height="130" align="middle" quality="high" name="mainCS3" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" wmode="transparent" pluginspage="http://www.adobe.com/go/getflashplayer" />
        </object>
    </div>
    <hr />
</div>