<!-- start calendar block -->
<div id="chat" class="block block-ui-bordered block-sidebar m-b-10">
	<div class="block-header">
		<div class="block-title">
			<i class="fa fa-user"></i> <?php echo $this->translate("Календарь") ?>
		</div>
	</div>
	<div class="block-body">
		<div class="text-center">
			<object type="application/x-shockwave-flash" height="200" width="200" data="http://личныйгид.рф/flash/c_maska.swf">
				<param name="movie" value="http://личныйгид.рф/flash/c_maska.swf" />
				<param name="wmode" value="transparent" />
			</object>
		</div>
	</div>
</div>
<!-- end calendar block -->