<!-- start user_map block -->
<div id="chat" class="block block-ui-bordered block-sidebar m-b-10">
	<div class="block-header">
		<div class="block-title">
			<i class="fa fa-user fa-lg"></i> <?php echo $this->translate("Паддок") ?>
		</div>
	</div>
	<div class="block-body">
		<i><?php echo $this->translate('Cейчас в паддоке'); ?>:</i>
		<span>
            <strong>
				<?php
				$user = new Application_Model_DbTable_User();
				echo $user->getCountOnlineUsers();
				?>
            </strong>
			<?php echo $this->translate('гонщик(-а, -ов)'); ?>
        </span>
	</div>
</div>
<!-- end user_map block -->