<!-- start user_map block -->
<div class="col-lg-12 col-md-4 col-sm-6 col-xs-12">
	<div id="online-drivers" class="block block-ui-bordered block-sidebar m-b-10">
		<div class="block-header">
			<div class="block-title">
				<i class="fa fa-user fa-lg"></i> <?php echo $this->translate("Паддок") ?>
			</div>
		</div>
		<div class="block-body">
			<i><?php echo $this->translate('Cейчас в паддоке'); ?>:</i>
			<span>
				<?php
				$user = new Application_Model_DbTable_User();

				$date = new Zend_Date();
				$date->sub(7, Zend_Date::MINUTE);
				$date = $date->toString('yyyy-MM-dd HH:mm:ss');

				$user_data = $user->getAll(array('date_last_activity' => array('value' => $date, 'sign' => '>=')));

				if ($user_data) {
					$user_count = count($user_data);
				} else {
					$user_count = '0';
				}
				?>
				<strong><?php echo $user_count; ?></strong> <?php echo $this->translate('гонщик(-а, -ов)'); ?>

				<?php
				if ($user_data) {
					foreach ($user_data as $user):
						?>
						<?php echo $user->login; ?>
						<?php
					endforeach;
				}
				?>
			</span>
		</div>
	</div>
</div>
<!-- end user_map block -->