<!-- start online-radio block -->
<div class="row">
	<div class="col-lg-12 col-md-12 hidden-sm hidden-xs">
		<div id="online-radio" class="block block-ui-bordered block-sidebar m-b-10">
			<div class="block-header">
				<div class="block-title">
					<i class="fa fa-music fa-lg"></i> <?php echo $this->translate('Онлайн радио') ?>
				</div>
			</div>
			<div class="block-body">
				<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="280" height="130" id="mainCS3" align="middle">
					<param name="allowScriptAccess" value="sameDomain" />
					<param name="allowFullScreen" value="false" />
					<param name="movie" value="http://gtiradio.ru/mainCS3.swf?wmode=opaque" /><param name="quality" value="high" />
					<embed src="http://gtiradio.ru/mainCS3.swf?wmode=opaque" width="280" height="130" align="middle" quality="high" name="mainCS3" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" wmode="transparent" pluginspage="http://www.adobe.com/go/getflashplayer" />
				</object>
			</div>
		</div>
	</div>
</div>
<!-- end online-radio block -->