<div id="chmpionship_add_page" class="page">
    <div class="page_content">
        <?php echo $this->form; ?>
        <script>
            jQuery(document).ready(function() {
                $("#date_start").datepicker({
                    showButtonPanel: true,
                    dateFormat: "yy-mm-dd",
                    showAnim: "clip"
                });
                
                $("#date_end").datepicker({
                    showButtonPanel: true,
                    dateFormat: "yy-mm-dd",
                    showAnim: "clip"
                });
            });
        </script>
    </div>
</div>