<div id="chmpionship_team_driver_delete_page" class="page">
    <div class="page_title"><?php echo $this->translate('Удалить гонщика'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Предупреждение!'); ?></h4>
                <?php echo $this->translate('Вы действительно хотите удалить гонщика') . ' "' . '$this->escape($this->article->title)' . '"?'; ?>
            </div>
            <?php echo $this->form ?>
        <?php } ?>
    </div>
</div>