<div id="championship_page" class="page article">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->escape($this->championship->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else {
            ?>
            <div class="championship_item article_item">
                <?php
                $bbcode = Zend_Markup::factory('Bbcode');
                if ($this->championship->url_logo != '') {
                    ?>
                    <img class="img-polaroid article_center_image" src="<?php echo $this->escape($this->championship->url_logo); ?>">
                <?php } ?>
                <div class="article_text"><?php //echo $bbcode->render($this->escape($this->article->text)); ?></div>
                <div class="article_controls">
                    <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        if (Zend_Auth::getInstance()->getStorage('online-racing')->read()->id == $this->escape($this->championship->user_id)) {
                            ?>
                            <a href = "<?php echo $this->baseUrl('championship/edit/' . $this->escape($this->championship->id)) ?>" class = "btn btn-small btn-inverse article_edit"><?php echo $this->translate('Редактировать') ?></a>
                            <a href = "<?php echo $this->baseUrl('championship/delete/' . $this->escape($this->championship->id)) ?>" class = "btn btn-small btn-inverse article_delete"><?php echo $this->translate('Удалить') ?></a>
                            <?php
                        }
                    }
                    ?>
                </div>
                <div class="article_info">
                    <div class="championship_author article_info_item"><span class="bold_text"><?php echo $this->translate('Админ') ?>: </span><a href="<?php echo $this->baseUrl('user/id/' . $this->escape($this->championship->user_id)) ?>"><?php echo $this->escape($this->championship->user_login); ?></a></div>
                    <div class="championshipe_date_create article_info_item"><span class="bold_text"><?php echo $this->translate('Создан') ?>: </span><?php echo $this->escape($this->championship->date_create); ?></div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>