<div id="championship_page" class="page article">
    <div class="page_content">
        <?php if ($this->championship) { ?>

            <div class="championship_item block_item block_ui_gray">
                <?php
                echo $this->ConfigureBlockItemMenu($this->translate("Чемпионат"))->championship_menu($this->escape($this->championship->id));
                ?>
                <div class="block_item_content">
                    <?php if ($this->championship->url_logo != '') {
                        ?>
                        <div class="pull-right img-polaroid league_id_logo_wrapper_250 image_logo_wrapper_250 overflow-hide">
                            <img class="championship_id_logo image_logo_250" src="<?php echo $this->escape($this->championship->url_logo); ?>">
                        </div>
                    <?php } ?>

                    <div class="img-polaroid championship_id_info_block">
                        <table class="table table-striped font-veradana font-size-11">
                            <tbody>
                                <tr>
                                    <td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Название') ?>:</td>
                                    <td class="cell-text-align-vert"><?php echo $this->escape($this->championship->name); ?></td>
                                </tr>
                                <tr>
                                    <td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Администратор чемпионата') ?>:</td>
                                    <td class="cell-text-align-vert"><a target="_blank" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $this->escape($this->championship->user_id)), 'user', true); ?>"><?php echo $this->escape($this->championship->user_login); ?></a></td>
                                </tr>
                                <tr>
                                    <td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Дата старта') ?>:</td>
                                    <td class="cell-text-align-vert"><?php echo $this->escape($this->championship->date_start); ?></td>
                                </tr>
                                <tr>
                                    <td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Дата окончания') ?>:</td>
                                    <td class="cell-text-align-vert"><?php echo $this->escape($this->championship->date_end); ?></td>
                                </tr>
                                <tr>
                                    <td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Описание') ?>:</td>
                                    <td class="cell-text-align-vert">
                                        <?php
                                        if ($this->championship->description != "") {
                                            echo $this->RenderContentTypeText($this->championship->description, 'bbcode');
                                        } else {
                                            echo $this->translate("Нет описания.");
                                        }
                                        ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <a href = "<?php echo $this->url(array('controller' => 'article', 'action' => 'id', 'id' => $this->escape($this->championship->game_id)), 'article', true); ?>" target="_blank" class = "btn btn-small btn-primary article_more" title="<?php echo $this->translate('Игра для проведения') ?>"><?php echo $this->translate('Игра') ?></a>

                    <div class="article_controls">
                        <a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'ds', 'championship_id' => $this->escape($this->championship->id)), 'championshipTeamDefault', true); ?>" class = "btn btn-small btn-success article_more" title="<?php echo $this->translate('Личный зачет') ?>"><?php echo $this->translate('ЛЗ') ?></a>
                        <a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'ts', 'championship_id' => $this->escape($this->championship->id)), 'championshipTeamDefault', true); ?>" class = "btn btn-small btn-warning article_more" title="<?php echo $this->translate('Командный зачет') ?>"><?php echo $this->translate('КЗ') ?></a>
                        <a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'drivers', 'championship_id' => $this->escape($this->championship->id)), 'championshipTeamDefault', true); ?>" class = "btn btn-small btn-info article_more" title="<?php echo $this->translate('Командный зачет') ?>"><?php echo $this->translate('Гонщики') ?></a>
                        <a href = "<?php echo $this->url(array('controller' => 'article', 'action' => 'id', 'id' => $this->escape($this->championship->article_id)), 'article', true); ?>" target="_blank" class = "btn btn-small btn-danger article_more" title="<?php echo $this->translate('Регламент чемпионата') ?>"><?php echo $this->translate('Регламент') ?></a>
                    </div>
                    <div class="block_item_info_bottom">
                        <div class="content_category block_item_info_bottom_item">
                            <span class="font-bold font-color-black"><?php echo $this->translate('Категория контента') ?>: </span>
                            <?php echo $this->translate('Чемпионат'); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>