<div id="chmpionship_team_id_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Команда') . ' :: ' . $this->escape($this->team_data->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="team_item block_item">
                <?php
                echo $this->ConfigureBlockItemMenu($this->translate("Команда"))->championship_team_menu($this->team_data->championship_id, $this->team_data->team_id);
                ?>
                <div class="block_item_content">
                    <div>
                        <?php if ($this->escape($this->team_data->url_logo_car) != '') { ?>
                            <img class="img-polaroid article_team_car_image_x" src="<?php echo $this->escape($this->team_data->url_logo_car); ?>">
                        <?php } ?>
                        <?php if ($this->escape($this->team_data->url_logo) != '') { ?>
                            <img class="img-polaroid article_team_logo_image" src="<?php echo $this->escape($this->team_data->url_logo); ?>">
                        <?php } ?>
                    </div>
                </div>
                <div class="page_title"><?php echo $this->translate('Состав команды') ?>:</div>
                <div class="div_hr"></div>
                <?php
                if ($this->team_driver_data) {
                    foreach ($this->team_driver_data as $driver):
                        ?>
                        <div class="team_user_full_info_item block_ui_gray block_item">
                            <?php
                            echo $this->ConfigureBlockItemMenu($this->translate("Гонщик"))->championship_team_driver_menu($this->team_data->championship_id, $this->team_data->team_id, $driver->user_id);
                            ?>
                            <div class="block_item_content">
                                <div class="article_title team_user_full_info_name">
                                    <span class="badge team_driver_number"><?php echo $this->escape($driver->driver_number) ?></span>
                                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $driver->user_id), 'user', true) ?>" target="_blank">
                                        <?php echo $this->escape($driver->user_name) ?>
                                        <?php echo $this->escape($driver->user_surname) ?>
                                        (<?php echo $driver->country_abbreviation ?>)
                                        <img class="user_flag_x" src="<?php echo $driver->country_url_image_glossy_wave ?>" title="<?php echo $driver->country_native_name ?> (<?php echo $driver->country_english_name ?>)">
                                    </a>
                                </div>
                                <div class="user_image pull-left">
                                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $driver->user_id), 'user', true) ?>" target="_blank">
                                        <?php echo $this->setupUserAvatar($driver->user_id, $driver->user_avatar_type); ?>
                                    </a>
                                </div>
                                <div class="teams_driver_info no_width">
                                    <table class="table table-condensed">
                                        <tr>
                                            <td><span class="bold_text"><?php echo $this->translate("Имя"); ?>: </span></td>
                                            <td><?php echo $this->escape($driver->user_name) ?></td>
                                        </tr>
                                        <tr>
                                            <td><span class="bold_text"><?php echo $this->translate("Фамилия"); ?>: </span></td>
                                            <td><?php echo $this->escape($driver->user_surname) ?></td>
                                        </tr>
                                        <tr>
                                            <td><span class="bold_text"><?php echo $this->translate("Ник-нэйм"); ?>: </span></td>
                                            <td><?php echo $this->escape($driver->user_login) ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <?php
                    endforeach;
                } else {
                    echo "Пусто";
                }
                ?>
            </div>
        <?php } ?>
    </div>
</div>