<div id="chmpionship_team_id_page" class="page">
    <div class="page_title"><?php echo $this->translate('Команда'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
			<?php 
			$edit_team_access = $this->checkUserAccess('championship/editteam');
				
			if ($edit_team_access) { ?>
				<div class="article_controls">
					<?php if ($edit_team_access) { ?>
                    	<a href="<?php echo $this->url(array('controller' => 'championship', 'action' => 'editteam', ), 'championshipTeam', true )?>"class = "btn btn-small btn-inverse article_edit"><?php echo $this->translate('Редактировать') ?></a>
                    <?php } ?>
				</div>
           	<?php } ?>
        <?php } ?>
    </div>
</div>