<div id="chmpionship_team_id_page" class="page">
    <div class="page_title">
        <?php
        if (!$this->errMessage != "") {
            echo $this->translate('Команда') . ' :: ' . $this->escape($this->team_data->name);
        } else {
            echo $this->translate('Ошибка!');
        }
        ?>
    </div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } else { ?>
            <div class="team_item block_item">
                <?php
                echo $this->ConfigureBlockItemMenu()->championship_team_menu($this->team_data->championship_id, $this->team_data->team_id);
                ?>
                <div class="block_item_content">
                    <div>
                        <?php if ($this->escape($this->team_data->url_logo_car) != '') { ?>
                            <img class="img-polaroid article_team_car_image_x" src="<?php echo $this->escape($this->team_data->url_logo_car); ?>">
                        <?php } ?>
                        <?php if ($this->escape($this->team_data->url_logo) != '') { ?>
                            <img class="img-polaroid article_team_logo_image" src="<?php echo $this->escape($this->team_data->url_logo); ?>">
                        <?php } ?>
                    </div>

                </div>
                <div class="page_title"><?php echo $this->translate('Состав команды') ?>:</div>
                <div class="div_hr"></div>
                <?php
                foreach ($this->team_driver_data as $driver):
                    ?>
                    <div class="user_full_item block_item">
                        <?php
                        echo $this->ConfigureBlockItemMenu()->championship_team_menu($this->team_data->championship_id, $this->team_data->team_id);
                        ?>
                        <div class="block_item_content">
                            <div class="article_title">
                                <span class="badge team_driver_number"><?php echo $this->escape($driver->driver_number) ?></span>
                                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $driver->user_id), 'user', true) ?>" target="_blank">
                                    <?php echo $this->escape($driver->user_name) ?>
                                    <?php echo $this->escape($driver->user_surname) ?>
                                </a>
                            </div>
                            <div class="user_image pull-left">
                                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'id' => $driver->user_id), 'user', true) ?>" target="_blank">
                                    <?php echo $this->setupUserAvatar($driver->user_id, $driver->user_avatar_type); ?>
                                </a>
                            </div>
                            <div class="teams_driver_info no_width">
                                <div><span class="bold_text"><?php echo $this->translate("Имя"); ?>: </span><?php echo $this->escape($driver->user_name) ?></div>
                                <div><span class="bold_text"><?php echo $this->translate("Фамилия"); ?>: </span><?php echo $this->escape($driver->user_surname) ?></div>
                                <div><span class="bold_text"><?php echo $this->translate("Ник-нэйм"); ?>: </span><?php echo $this->escape($driver->user_login) ?></div>
                                <div><span class="bold_text"><?php echo $this->translate("Страна"); ?>: </span><img src="<?php echo $driver->country_url_image_glossy_wave ?>"></div>
                            </div>
                        </div>
                    </div>
                    <?php
                endforeach;
                ?>
            </div>
        <?php } ?>
    </div>
</div>