<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <li class="disabled"><a href="#"><?= $this->firstItemNumber; ?> - <?= $this->lastItemNumber; ?> <?= $this->translate('из'); ?> <?= $this->totalItemCount; ?></a></li>

        <!-- Ссылка на первую страницу -->
	<?php if (isset($this->previous)): ?>
	    <li><a href="<?= $this->url(array('page' => $this->first)); ?>"><?= $this->translate('Первая'); ?></a></li>
	<?php else: ?>
	    <li class="active"><a href="#"><?= $this->translate('Первая'); ?></a></li>
	<?php endif; ?>

        <!-- Ссылка на предыдущую страницу -->
	<?php if (isset($this->previous)): ?>
	    <li><a href="<?= $this->url(array('page' => $this->previous)); ?>">«</a></li>
	<?php else: ?>
	    <li class="disabled"><a href="#">«</a></li>
	<?php endif; ?>

        <!-- Нумерованные ссылки на страницы -->
	<?php foreach ($this->pagesInRange as $page): ?>
	    <?php if ($page != $this->current): ?>
	        <li><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li>
	    <?php else: ?>
	        <li class="active"><a href="#"><?= $page; ?></a></li>
	    <?php endif; ?>
	<?php endforeach; ?>

        <!-- Ссылка на следующую страницу -->
	<?php if (isset($this->next)): ?>
	    <li><a href="<?= $this->url(array('page' => $this->next)); ?>">»</a></li>
	<?php else: ?>
	    <li class="disabled"><a href="#">»</a></li>
	<?php endif; ?>

        <!-- Ссылка на последнюю страницу -->
	<?php if (isset($this->next)): ?>
	    <li><a href="<?= $this->url(array('page' => $this->last)); ?>"><?= $this->translate('Последняя'); ?></a></li>
	<?php else: ?>
	    <li class="active"><a href="#"><?= $this->translate('Последняя'); ?></a></li>
	    <?php endif; ?>
    </ul>
<?php endif; ?>