<div class="form-group">
	<?php
	$options = "";
	foreach ($this->element->getAttribs() as $name => $value):
		switch ($name):
			case 'checked':
				if ($value) {
					$options .=' ' . $name . "='" . $value . "'";
				}
				break;
			case 'options':
				break;
			default:
				$options .=' ' . $name . "='" . $value . "'";
				break;
		endswitch;
	endforeach;
	?>
	<div class="checkbox">
		<label>
			<input type="checkbox" value="<?= $this->element->getCheckedValue(); ?>" id="<?= $this->element->getId() ?>" name="<?= $this->element->getName() ?>" <?= $options; ?> /> <?= $this->element->getLabel() ?>
		</label>
	</div>
</div>