<div class="sidebar_box">
    <div class="sidebar_box_title">
        <i class="icon-plane icon-white"></i> <?php echo $this->translate('Ближайшее событие') ?>
    </div>
    <div class="sidebar_box_content">
        <script type="text/javascript">
            $(document).ready(function(){
                var newYear = new Date(); 
                newYear = new Date(2013, 01 - 1 ,05, 16, 30, 00); 
                $('#countdown_dashboard').countdown({until: newYear, format: 'ODHMS', description: 'Гран-При Малайзии!'});
            });
        </script>
        <div id="countdown_dashboard"></div>
    </div>
</div>