<div class="sidebar_box">
    <div class="sidebar_box_title">
        Поиск (Не работает)
    </div>
    <div class="sidebar_box_content">
        <form class="form-search" style="margin:5px 0;">
            <div class="input-append">
                <input type="text" class="span2 search-query" style="width:115px;">
                <button type="submit" class="btn" style="width:70px;">Поиск</button>
            </div>
        </form>
    </div>
</div>