<div id="users_page" class="page">
    <div class="page_title"><?php echo $this->translate('Гонщики'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml');

            foreach ($this->paginator as $item):
                ?>
                <div class="user_item">
                    <div class="user_image">
                        <?php
                        echo $this->gravatar()
                                ->setEmail($item['gravatar'])
                                ->setImgSize(160)
                                ->setDefaultImg(Zend_View_Helper_Gravatar::DEFAULT_MM)
                                ->setSecure(true)
                                ->setAttribs(array('class' => 'img-polaroid', 'title' => $item['login'] . " - profile avatar"));
                        ?>
                    </div>
                    <div class="user_flag"><img src="<?php echo $this->baseUrl('img/flags/eur_round_32.png'); ?>"></div>
                    <div class="user_login"><a href="<?php echo $this->baseUrl('user/info/') . $item['id'] ?>"><?php echo $item['login']; ?></a></div>
                </div>
                <?php
            endforeach;

            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml');
        } else {
            ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->translate('Пользователи на сайте не найдены!'); ?>
            </div>
        <?php } ?>
    </div>
</div>