<div id="users_page" class="page">
    <div class="page_title"><?php echo $this->translate('Гонщики'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml');

            $date1 = new Zend_Date();
            foreach ($this->paginator as $user):
                ?>
                <div class="user_item">
                    <?php
                    $date2 = new Zend_Date($user['date_last_activity']);
                    if (($date1->toValue() - $date2->toValue()) <= 420) {
                        ?>
                        <img src="/img/user_online.png" class="user_light_status img-polaroid">
                    <?php } else { ?>
                        <img src="/img/user_ofline.png" class="user_light_status img-polaroid">
                    <?php } ?>
                    <div class="user_image">
                        <?php echo $this->setupUserAvatar($user['id'], $user['avatar_type']); ?>
                    </div>

                    <div class="user_flag"><img src="<?php echo $user['country_url_image_round']; ?>" title="<?php echo $user['country_name']; ?>"></div>
                    <div class="user_login"><a href="<?php echo $this->baseUrl('user/id/') . $user['id'] ?>"><?php echo $user['login']; ?></a></div>
                </div>
                <?php
            endforeach;

            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml');
        } else {
            ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->translate('Пользователи на сайте не найдены!'); ?>
            </div>
        <?php } ?>
    </div>
</div>