<div id="user_edit_page" class="page">
    <div class="page_title"><?php echo $this->translate('Редактирование профиля'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class="alert alert-info alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4><?php echo $this->translate('Информация'); ?></h4>
            <?php echo $this->translate('Введите новые данные и нажмите "Сохранить".'); ?>
        </div>
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <div id="tabs">
            <ul>
                <li><a href="#tabs-1"><?php echo $this->translate('Личное'); ?></a></li>
                <li><a href="#tabs-2"><?php echo $this->translate('Аватар'); ?></a></li>
                <li><a href="#tabs-3"><?php echo $this->translate('Контакты'); ?></a></li>
                <li><a href="#tabs-4"><?php echo $this->translate('Аккаунты'); ?></a></li>
                <li><a href="#tabs-5"><?php echo $this->translate('Дополнительно'); ?></a></li>
            </ul>
            <div id="tabs-1">
                <form id="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>#tabs-1" method="<?php echo $this->form->getMethod(); ?>">
                    <?php echo $this->form->getDisplayGroup('personal_Inf'); ?>
                    <?php echo $this->form->tab_name->setvalue('personal_Inf'); ?>
                    <?php echo $this->form->getDisplayGroup('form_actions'); ?>
                </form>
                <script>
                    $(function() {
                        $("#birthday").datepicker({
                            showButtonPanel: true,
                            dateFormat: "yy-mm-dd",
                            showAnim: "clip"
                        });
                    });
                </script>
            </div>
            <div id="tabs-2">
                <form id="<?php echo $this->form->getName(); ?>" action="<?php echo $this->form->getAction(); ?>#tabs-2" method="<?php echo $this->form->getMethod(); ?>">
                    <table id="table_avatar_type" class="table table-bordered">
                        <tbody>
                            <tr>
                                <td><?php echo $this->setupUserAvatar($this->user_id, 1); ?></td>
                                <td><?php echo $this->setupUserAvatar($this->user_id, 2); ?></td>
                                <td><?php echo $this->setupUserAvatar($this->user_id, 3); ?></td>
                            </tr>
                            <tr>
                                <td><span><?php echo $this->translate('Загруженный'); ?></span><br /><span>(<?php echo $this->translate('Не реализованно!'); ?>)</span></td>
                                <td><span><?php echo $this->translate('Ссылка с другого ресурса'); ?></span></td>
                                <td><span><?php echo $this->translate('Gravatar'); ?></span></td>
                            </tr>
                        </tbody>
                    </table>
                    <?php echo $this->form->getDisplayGroup('avatar'); ?>
                    <?php echo $this->form->tab_name->setvalue('avatar'); ?>
                    <?php echo $this->form->getDisplayGroup('form_actions'); ?>
                </form>
            </div>
            <div id = "tabs-3">
                <form id = "<?php echo $this->form->getName(); ?>" action = "<?php echo $this->form->getAction(); ?>#tabs-3" method = "<?php echo $this->form->getMethod(); ?>">
                    <?php echo $this->form->getDisplayGroup('contacts_Inf'); ?>
                    <?php echo $this->form->tab_name->setvalue('contacts_Inf'); ?>
                    <?php echo $this->form->getDisplayGroup('form_actions'); ?>
                </form>
            </div>
            <div id = "tabs-4">
                <form id = "<?php echo $this->form->getName(); ?>" action = "<?php echo $this->form->getAction(); ?>#tabs-4" method = "<?php echo $this->form->getMethod(); ?>">
                    <?php echo $this->form->getDisplayGroup('social_netwoks'); ?>
                    <?php echo $this->form->tab_name->setvalue('social_netwoks'); ?>
                    <?php echo $this->form->getDisplayGroup('form_actions'); ?>
                </form>
            </div>
            <div id = "tabs-5">
                <form id = "<?php echo $this->form->getName(); ?>" action = "<?php echo $this->form->getAction(); ?>#tabs-5" method = "<?php echo $this->form->getMethod(); ?>">
                    <?php echo $this->form->getDisplayGroup('additional_Inf'); ?>
                    <?php echo $this->form->tab_name->setvalue('additional_Inf'); ?>
                    <?php echo $this->form->getDisplayGroup('form_actions'); ?>
                </form>
            </div>
        </div>
        <script type = "text/javascript" >
            jQuery(document) . ready(function() {
                $('#tabs') . tabs();
            });
        </script>
    </div>
</div>