<div class="page_title">Профиль</div>
<hr>

<div id="tabs">
    <ul>
        <li><a href="#tabs-1"><?php echo $this->translate('Информация')?></a></li>
        <li><a href="#tabs-2"><?php echo $this->translate('Текущие данные')?></a></li>
        <li><a href="#tabs-3"><?php echo $this->translate('Статистика')?></a></li>
    </ul>
    <div id="tabs-1"><?php echo $this->translate('Номер пользователя') . ': ' . $this->id ?></div>
    <div id="tabs-2"></div>
    <div id="tabs-3"></div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        $('#tabs').tabs();
    });
</script>

<?php print_r($this->user)?>