<div id="user_register_page" class="page">
    <div class="page_title"><?php echo $this->translate('Авторизация'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class='alert alert-info'><?php echo $this->translate('Введите данные в форму ниже, чтобы авторизоваться на сайте.');?></div>
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="alert alert-error">' . $this->errMessage . '</div>';
        }
        ?>
        <?php echo $this->form; ?>
    </div>
</div>