<div id="user_register_page" class="page">
    <div class="page_title"><?php echo $this->translate('Авторизация'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <p>Введите данные в форму ниже, чтобы авторизоваться на сайте.</p>
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="messages errors">' . $this->errMessage . '</div>';
        }
        ?>
        <?php echo $this->form; ?>
    </div>
</div>