<div id="user_register_page" class="page">
    <div class="page_title"><?php echo $this->translate('Восcтановление пароля'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class="alert alert-info"><?php echo $this->translate('Для востановления своего пароля введите e-mail адрес,
            указаный при регистрации, 
            на который вам будут высланы данные для востановления пароля.'); ?></div>
        <?php
        if ($this->errMessage != "") {
            echo $this->errMessage = '<div class="alert alert-error">' . $this->errMessage . '</div>';
        }
        ?>
        <?php echo $this->form; ?>
    </div>
</div>

