<div id="user_register_page" class="page">
    <div class="page_title"><?php echo $this->translate('Восcтановление пароля'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <div class="alert alert-info alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4><?php echo $this->translate('Информация!'); ?></h4>
            <?php echo $this->translate('Введите данные, полученные на ваш регистрационный e-mail в форму ниже для создания нового пароля.'); ?><br/>
            <?php echo $this->translate('Если вы не получили письмо - проверьте письма из папки спам и пометьте его как "не смам", либо попробуйте')?>
            <strong><a href="<?php echo $this->baseUrl('user/restore-passwd')?>"><?php echo $this->translate('выслать данные еще раз.'); ?></a></strong>
        </div>
        <?php if ($this->errMessage != "") { ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->errMessage; ?>
            </div>
        <?php } ?>
        <?php echo $this->form; ?>
    </div>
</div>

