<div id="tracks_page" class="page">
    <div class="page_content">
        <?php
        if ($this->paginator) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
            ?>
            <table class="table table-bordered table-hover table-striped articles_table">
                <thead>
                    <tr>
                        <th class="track_id"><span>#</span></th>
                        <th class="track_name"><span><?php echo $this->translate('Название'); ?></span></th>
                        <th class="track_name"><span><?php echo $this->translate('Английское название'); ?></span></th>
                        <th class="track_descr"><span><?php echo $this->translate('Аббревиатура'); ?></span></th>
                        <th class="track_descr"><span><?php echo $this->translate('Круговая картинка'); ?></span></th>
                        <th class="track_descr"><span><?php echo $this->translate('Волнистая картинка'); ?></span></th>
                        <th class="track_action articles_table_action"><span><?php echo $this->translate('Действие'); ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->paginator as $track): ?>
                        <tr>
                            <td class="track_id">
                                <span><a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'id', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <?php echo $this->escape($track['id']) ?>
                                    </a></span>
                            </td>
                            <td class="track_name">
                                <span><a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'id', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <?php echo $this->escape($track['name']) ?>
                                    </a></span>
                            </td>
                            <td class="track_name">
                                <span><a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'id', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <?php echo $this->escape($track['english_name']) ?>
                                    </a></span>
                            </td>
                            <td class="track_name">
                                <span><a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'id', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <?php echo $this->escape($track['abbreviation']) ?>
                                    </a></span>
                            </td>
                            <td class="track_img_round">
                                <span><img src="<?php echo $this->baseUrl($this->escape($track['url_image_round'])); ?>"></span>
                            </td>
                            <td class="track_img_glossy_wave">
                                <span><img src="<?php echo $this->baseUrl($this->escape($track['url_image_glossy_wave'])); ?>"></span>
                            </td>
                            <td class="track_action articles_table_action">
                                <span>
                                    <a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'id', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <i class="fa fa-eye"></i> <?php echo $this->translate('Просм.'); ?>
                                    </a><br/>
                                    <a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'edit', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <i class="fa fa-edit"></i> <?php echo $this->translate('Ред.'); ?>
                                    </a><br/>
                                    <a href="<?php echo $this->url(array('controller' => 'track', 'action' => 'delete', 'id' => $this->escape($track['id'])), 'track', true); ?>">
                                        <i class="fa fa-trash-o"></i> <?php echo $this->translate('Удал.'); ?>
                                    </a><br/>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
            ?>
        <?php }
        ?>
    </div>
</div>