<?php if ($this->event) { ?>
    <?= $this->form; ?>
    <div class="event_item block-item">
        <table class="table table-striped table-bordered article_table">
    	<tbody>
    	    <tr>
    		<td class="header_column"><span><?= $this->translate('Название'); ?></span></td>
    		<td><span><?= $this->escape($this->event['name']); ?></span></td>
    	    </tr>
    	    <tr>
    		<td class="header_column"><span><?= $this->translate('Описание'); ?></span></td>
    		<td><span><?= $this->escape($this->event['description']); ?></span></td>
    	    </tr>
    	    <tr>
    		<td class="header_column"><span><?= $this->translate('Дата события'); ?></span></td>
    		<td><span><?= $this->escape($this->event['date_event']); ?></span></td>
    	    </tr>
    	    <tr>
    		<td class="header_column"><span><?= $this->translate('Ссылка на событие'); ?></span></td>
    		<td><span><a href="<?= $this->escape($this->event['url_event']); ?>"><?= $this->translate('Ссылка'); ?></a></span></td>
    	    </tr>
    	</tbody>
        </table>
	<?php
	$acl = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('Acl');

	$edit_access = $acl->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'event','edit');
	$delete_access = $acl->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'event','delete');

	if ($edit_access || $delete_access) {
	    ?>
	    <div class = "article_controls" >
		<?php if ($edit_access) { ?>
	    	<a href = "<?= $this->url(array('module' => 'admin', 'controller' => 'event', 'action' => 'edit', 'event_id' => $this->event['id']), 'event_action', true) ?>" class = "btn btn-sm btn-primary content_edit"><?= $this->translate('Редактировать') ?></a>
		<?php } ?>
		<?php if ($delete_access) { ?>
	    	<a href = "<?= $this->url(array('module' => 'admin', 'controller' => 'event', 'action' => 'delete', 'event_id' => $this->event['id']), 'event_action', true) ?>" class = "btn btn-sm btn-primary content_delete"><?= $this->translate('Удалить') ?></a>
		<?php } ?>
	    </div>
	<?php } ?>
        <div class="article_info">
    	<div class="event_name article_info_item"><span class="bold_text"><?= $this->translate('Вид контента') ?>: </span><?= $this->translate('Событие'); ?></div>
    	<div class="event_date_create article_info_item"><span class="bold_text"><?= $this->translate('Опубликовано') ?>: </span><?= $this->escape($this->event['date_create']); ?></div>
	    <?php if ($this->escape($this->event['date_create']) != $this->escape($this->event['date_edit'])) { ?>
		<div class="event_date_edit article_info_item"><span class="bold_text"><?= $this->translate('Последнее редактирование') ?>: </span><?= $this->escape($this->event['date_edit']); ?></div>
	    <?php } ?>
        </div>
    </div>
<?php } ?>