<div class="alert alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4><?php echo $this->translate('Предупреждение!'); ?></h4>
    <?php echo $this->translate('Вы действительно хотите удалить событие ') . '"' . $this->escape($this->event->name) . '"?'; ?>
</div>
<?php echo $this->form; ?>
<div class="content_type_item">
    <table class="table table-striped table-bordered article_table">
	<tbody>
	    <tr>
		<td class="header_column"><span><?php echo $this->translate('Название'); ?></span></td>
		<td><span><?php echo $this->escape($this->event->name); ?></span></td>
	    </tr>
	    <tr>
		<td class="header_column"><span><?php echo $this->translate('Описание'); ?></span></td>
		<td><span><?php echo $this->escape($this->event->description); ?></span></td>
	    </tr>
	    <tr>
		<td class="header_column"><span><?php echo $this->translate('Дата события'); ?></span></td>
		<td><span><?php echo $this->escape($this->event->date_event); ?></span></td>
	    </tr>
	    <tr>
		<td class="header_column"><span><?php echo $this->translate('Ссылка на событие'); ?></span></td>
		<td><span><a href="<?php echo $this->escape($this->event->url_event); ?>"><?php echo $this->translate('Ссылка'); ?></a></span></td>
	    </tr>
	</tbody>
    </table>
    <div class="content_type_url_event"><?php echo $this->escape($this->event->url_event); ?></div>
    <div class="article_info">
	<div class="event_name article_info_item"><span class="bold_text"><?php echo $this->translate('Вид контента') ?>: </span><?php echo $this->translate('Событие'); ?></div>
	<div class="event_date_create article_info_item"><span class="bold_text"><?php echo $this->translate('Опубликовано') ?>: </span><?php echo $this->escape($this->event->date_create); ?></div>
	<?php if ($this->escape($this->event->date_create) != $this->escape($this->event->date_edit)) { ?>
    	<div class="event_date_edit article_info_item"><span class="bold_text"><?php echo $this->translate('Последнее редактирование') ?>: </span><?php echo $this->escape($this->event->date_edit); ?></div>
	<?php } ?>
    </div>
</div>