<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <i class="fa fa-list fa-2x"></i>
                <?php
                // check access and generate link for admin/team/add
                if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'team', 'add')) : ?>
                    <?php
                    $adminTeamAddUrl = $this->url(
                        array('module' => 'admin', 'controller' => 'team', 'action' => 'add'), 'default'
                    );
                    ?>
                    <a href="<?= $adminTeamAddUrl; ?>" class="btn btn-xs btn-primary pull-right ">
                        <i class="fa fa-plus"></i> <?= $this->t('Добавить команду'); ?>
                    </a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th class="team-id">
                        <span>ID</span>
                    </th>
                    <th class="team-name">
                        <span><?= $this->t('Название'); ?></span>
                    </th>
                    <th class="team-racing-series">
                        <span><?= $this->t('Гоночная серия'); ?></span>
                    </th>
                    <th class="team-action">
                        <span><?= $this->t('Действие'); ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->teamData) : ?>
                    <?php foreach ($this->teamData as $team): ?>
                        <?php
                        // check access and generate link for admin/team/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'team', 'id')) {
                            $adminTeamIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'team', 'action' => 'id',
                                    'teamID' => $this->escape($team['ID'])), 'adminTeamID'
                            );
                        } else {
                            $adminTeamIdUrl = '#';
                        }
                        ?>
                        <?php
                        // check access and generate link for admin/racing-series/id
                        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'id')) {
                            $adminRacingSeriesIdUrl = $this->url(
                                array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'id',
                                    'racingSeriesID' => $this->escape($team['RacingSeries']['ID'])), 'adminRacingSeriesID'
                            );
                        } else {
                            $adminRacingSeriesIdUrl = '#';
                        }
                        ?>
                        <tr>
                            <td class="team-id">
                                <span>
                                    <a href="<?= $adminTeamIdUrl; ?>">
                                        <?= $this->escape($team['ID']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="team-name">
                                <span>
                                    <a href="<?= $adminTeamIdUrl; ?>">
                                        <?= $this->escape($team['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="team-racing-series">
                                <span>
                                    <a href="<?= $adminRacingSeriesIdUrl; ?>">
                                        <?= $this->escape($team['RacingSeries']['Name']) ?>
                                    </a>
                                </span>
                            </td>
                            <td class="team-action">
                                <span>
                                    <?= $this->BlockConfigMenu($this->t("Команда"), false)
                                        ->teamMenu($this->escape($team['ID']), true);
                                    ?>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
            <div class="panel-footer clearfix">
                <?php if ($this->teamData) : ?>
                    <div class="pull-right">
                        <?= $this->paginationControl(
                            $this->teamData, 'Sliding', 'pagers/default_pagination_tpl.phtml'
                        ); ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
