<?php if ($this->teamData) : ?>
    <div class="block block-default block-ui-bordered">
        <?php
        echo $this->BlockConfigMenu($this->translate("Команда"))->teamMenu(
            $this->escape($this->teamData['ID'])
        );
        // check access and generate link for admin/racing-series/id
        if ($this->checkUserAccess('admin' . Acl::RESOURCE_SEPARATOR . 'racing-series', 'id')) {
            $adminRacingSeriesIdUrl = $this->url(
                array('module' => 'admin', 'controller' => 'racing-series', 'action' => 'id',
                    'racingSeriesID' => $this->escape($this->teamData['RacingSeries']['ID'])), 'adminRacingSeriesID'
            );
        } else {
            $adminRacingSeriesIdUrl = '#';
        }
        ?>
        <div>
            <table class="table table-striped table-bordered m-b-0">
                <tbody>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Название'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escape($this->teamData['Name']); ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Гоночная серия'); ?></span>
                    </td>
                    <td>
                        <span>
                            <a target="_blank"
                                 href="<?= $adminRacingSeriesIdUrl; ?>"><?= $this->escape($this->teamData['RacingSeries']['Name']); ?>
                            </a>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="text-bold">
                        <span><?= $this->translate('Описание'); ?></span>
                    </td>
                    <td>
                        <span><?= $this->RenderContentTypeText($this->teamData['Description'], 'full_html'); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="block-footer clearfix">
            <div class="pull-left m-r-15 tooltip-field" data-title="<?= $this->translate('Тип контента'); ?>"
                 data-placement="bottom">
                <i class="fa fa-filter fa-lg"></i>
                <?= $this->translate('Команда'); ?>
            </div>
            <div class="pull-right m-r-15 tooltip-field" data-title="<?= $this->translate('Дата создания'); ?>"
                 data-placement="bottom">
                <i class="fa fa-calendar fa-lg"></i>
                <?= $this->escape($this->teamData['DateCreate']); ?>
            </div>
            <?php if ($this->escape($this->teamData['DateCreate']) != $this->escape($this->teamData['DateEdit'])) : ?>
                <div class="pull-right m-r-15 tooltip-field"
                     data-title="<?= $this->translate('Дата редактирования'); ?>" data-placement="bottom">
                    <i class="fa fa-pencil fa-lg"></i>
                    <?= $this->escape($this->teamData['DateEdit']); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>