<?php if ($this->championship_races_data) : ?>

    <?php echo $this->render('championship/common/championship_menu.phtml') ?>

    <?php echo $this->render('championship/common/hotlap_menu.phtml') ?>

    <!-- start races -->
    <div class="row">
        <section class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
            <?php foreach ($this->championship_races_data as $race): ?>
                <?php
                $championship_race_id_url = $this->url(
                    array('module'          => 'default', 'controller' => 'race', 'action' => 'id',
                          'league_id'       => $this->league_data->id,
                          'championship_id' => $this->championship_data->id, 'race_id' => $race->id),
                    'defaultChampionshipRaceId', true
                );
                ?>
                <div class="block block-ui-bordered block-ui-shadow m-b-15">
                    <?php
                    echo $this->BlockConfigMenu($this->translate("Гонка"))->championshipRaceMenu(
                        $this->escape($this->league_data->id), $this->escape($this->championship_data->id),
                        $this->escape($race->id)
                    );
                    ?>
                    <div class="block-body">
                        <div class="row">
                            <article class="block-race">
                                <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                                    <?php if ($this->escape($race->track_url_scheme) != '') : ?>
                                        <div
                                            class="img-wrapper-200-200 pull-left overflow-hide m-r-5">
                                            <a href="#" data-toggle="modal" data-target=".champ-race-<?php echo $race->id; ?>"
                                               title="<?php echo $this->escape($race->name); ?>" class="thumbnail">
                                                <img class="media-object img-size-200 img-responsive"
                                                     src="<?php echo $this->baseUrl(
                                                         $this->escape($race->track_url_scheme)
                                                     ); ?>">
                                            </a>
                                            <?php echo $this->modal(array(
                                                'title' => $race->track_name,
                                                'class' => 'champ-race-'.$race->id,
                                                'content' => '<img src="'.$this->baseUrl($this->escape($race->track_url_scheme)).'" class="img-responsive img-rounded center-block" alt="">'
                                            )); ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
                                    <ul class="meta-search">
                                        <li><i class="glyphicon glyphicon-calendar"></i>
                                            <span><?php echo $this->escape($race->race_date); ?></span></li>
                                        <li><i class="glyphicon glyphicon-time"></i> <span></span></li>
                                        <li><i class="glyphicon glyphicon-tags"></i> <span><?php echo $this->translate(
                                                    'Гонка'
                                                ); ?></span></li>
                                        <li>
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        <span class="tooltip-field" data-placement="bottom"
                                              data-title="<?php echo $this->escape($race->country_english_name); ?>">
                                            <img class="img-size-30-30" src="<?php echo $this->baseUrl(
                                                $this->escape($race->country_url_image_round)
                                            ); ?>" alt="<?php echo $this->escape($race->country_english_name); ?>">
                                        </span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7  excerpet">
                                    <h3>
                                        <a href="<?php echo $championship_race_id_url; ?>"
                                           title="">
                                            <?php echo $this->escape($race->name); ?>
                                        </a>
                                    </h3>
                                    <!-- detail information for race  -->
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            <thead>
                                            <tr>
                                                <th>
                                                    <?php echo $this->translate('Номер'); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate('Круги'); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate('Конфиг. трассы (год)'); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate('Длина круга (км)'); ?>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td>
                                                    <span
                                                        class="label label-danger"><?php echo $race->race_number ?></span>
                                                </td>
                                                <td>
                                                    <?php echo $this->escape($race->race_laps); ?>
                                                </td>
                                                <td>
                                                    <?php echo $this->escape($race->track_year); ?>
                                                </td>
                                                <td>
                                                    <?php echo $this->escape($race->track_length); ?>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end detail information for race  -->
                                    <!-- More btn -->
                                <span class="plus">
                                    <a href="<?php echo $championship_race_id_url; ?>"
                                       title="<?php echo $this->translate('Подробнее...'); ?>" class="pull-right">
                                        <i class="glyphicon glyphicon-share-alt"></i>
                                    </a>
                                </span><!-- More btn -->
                                </div>
                                <span class="clearfix borda"></span>
                            </article>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </section>
    </div><!-- end races -->
<?php endif; ?>
