<?php if ($this->championship_races_data) : ?>

    <?= $this->render('championship/common/championship-menu.phtml') ?>

    <?= $this->render('championship/common/hotlaps-menu.phtml') ?>

    <!-- start races -->
    <div class="row">
        <section class="col-xs-12 col-sm-12 col-md-12 col-ls-12">
            <?php foreach ($this->championship_races_data as $race): ?>
                <?php
                $championship_race_id_url = $this->url(
                    array('module'          => 'default',
                          'controller' => 'race',
                          'action' => 'id',
                          'league_id'       => $this->leagueData['ID'],
                          'championship_id' => $this->championship_data->id,
                          'race_id' => $race->id),
                    'defaultChampionshipRaceId', true
                );
                ?>
                <div class="block block-default block-ui-bordered block-ui-shadow m-b-15">
                    <?php
                    echo $this->BlockConfigMenu($this->t("Гонка"))->championshipRaceMenu(
                        $this->escape($this->leagueData['ID']),
                        $this->escape($this->championship_data->id),
                        $this->escape($race->id),
                        $this->escape($race->track_id)
                    );
                    ?>
                    <div class="block-body">
                        <div class="row">
                            <article class="block-race">
                                <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                                    <?php if ($this->escape($race->track_url_scheme) != '') : ?>
                                        <div
                                            class="img-wrapper-200-200 pull-left overflow-hide m-r-5">
                                            <a href="#" data-toggle="modal" data-target=".champ-race-<?= $race->id; ?>"
                                               title="<?= $this->escape($race->name); ?>" class="thumbnail">
                                                <img class="media-object img-size-200 img-responsive"
                                                     src="<?= $this->baseUrl(
                                                         $this->escape($race->track_url_scheme)
                                                     ); ?>">
                                            </a>
                                            <?= $this->modal(array(
                                                'title' => $race->track_name,
                                                'class' => 'champ-race-'.$race->id,
                                                'content' => '<img src="'.$this->baseUrl($this->escape($race->track_url_scheme)).'" class="img-responsive img-rounded center-block" alt="">'
                                            )); ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
                                    <ul class="meta-search">
                                        <li><i class="glyphicon glyphicon-calendar"></i>
                                            <span><?= $this->escape($race->race_date); ?></span></li>
                                        <li><i class="glyphicon glyphicon-time"></i> <span></span></li>
                                        <li><i class="glyphicon glyphicon-tags"></i> <span><?= $this->t(
                                                    'Гонка'
                                                ); ?></span></li>
                                        <li>
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        <span class="tooltip-field" data-placement="bottom"
                                              data-title="<?= $this->escape($race->country_EnglishName); ?>">
                                            <img class="img-size-30-30" src="<?= $this->baseUrl(
                                                $this->escape($race->country_ImageRoundUrl)
                                            ); ?>" alt="<?= $this->escape($race->country_EnglishName); ?>">
                                        </span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7  excerpet">
                                    <h3>
                                        <a href="<?= $championship_race_id_url; ?>"
                                           title="">
                                            <?= $this->escape($race->name); ?>
                                        </a>
                                    </h3>
                                    <!-- detail information for race  -->
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            <thead>
                                            <tr>
                                                <th>
                                                    <?= $this->t('Номер'); ?>
                                                </th>
                                                <th>
                                                    <?= $this->t('Круги'); ?>
                                                </th>
                                                <th>
                                                    <?= $this->t('Конфиг. трассы (год)'); ?>
                                                </th>
                                                <th>
                                                    <?= $this->t('Длина круга (км)'); ?>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td>
                                                    <span
                                                        class="label label-danger"><?= $race->race_number ?></span>
                                                </td>
                                                <td>
                                                    <?= $this->escape($race->race_laps); ?>
                                                </td>
                                                <td>
                                                    <?= $this->escape($race->track_year); ?>
                                                </td>
                                                <td>
                                                    <?= $this->escape($race->track_length); ?>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end detail information for race  -->
                                    <!-- More btn -->
                                <span class="plus">
                                    <a href="<?= $championship_race_id_url; ?>"
                                       title="<?= $this->t('Подробнее...'); ?>" class="pull-right">
                                        <i class="glyphicon glyphicon-share-alt"></i>
                                    </a>
                                </span><!-- More btn -->
                                </div>
                                <span class="clearfix borda"></span>
                            </article>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </section>
    </div><!-- end races -->
<?php endif; ?>
