<?php if ($this->championshipTeams) { ?>

    <?= $this->render('championship/common/championship-menu.phtml') ?>

    <?= $this->render('championship/common/hotlaps-menu.phtml') ?>

    <?php foreach ($this->championshipTeams as $team): ?>
        <div class="row team-item">
            <div class="col-lg-12">
                <div class="clearfix">
                    <?php
                    $team_url = $this->url(array('controller' => 'championship', 'action' => 'team', 'league_id' => $this->leagueData['ID'], 'championship_id' => $this->escape($team->championship_id), 'team_id' => $this->escape($team->team_id)), 'defaultChampionshipTeam', true);

                    $championship_team_driver = new Application_Model_DbTable_ChampionshipTeamDriver();
                    $championship_team_drivers_data = $championship_team_driver->getChampionshipTeamDrivers($this->escape($team->championship_id), $this->escape($team->team_id));

                    if ($championship_team_drivers_data) {
                        $racers_count = count($championship_team_drivers_data);
                    } else {
                        $racers_count = "0";
                    }
                    ?>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="well well-sm block block-default">
                                <?= $this->BlockConfigMenu($this->t("Команда"))->championshipTeamMenu($this->escape($this->leagueData['ID']), $this->escape($team->championship_id), $this->escape($team->team_id)); ?>
                                <div class="block-body media">
                                    <?php if ($this->escape($team['url_logo']) != '') { ?>
                                        <div
                                            class=" team_drivers_logo_wrapper_365 img-wrapper-150-150 overflow-hide pull-left">
                                            <a href="<?= $team_url; ?>">
                                                <img class="team_drivers_logo img-thumbnail img-responsive"
                                                     src="<?= $this->escape($team['url_logo']); ?>">
                                            </a>
                                        </div>
                                    <?php } ?>
                                    <div class="media-body">
                                        <h4 class="media-heading"><span class="team-name"><a
                                                    href="<?= $team_url; ?>"><?= $this->escape($team['name']); ?></a></span>
                                        </h4>

                                        <p>
                                            <span
                                                class="label label-warning"><?= $this->t('Номер') . ': ' . $team->team_number; ?></span>
                                            <span
                                                class="label label-info"><?= $this->t('Гонщиков') . ': ' . $racers_count; ?></span>
                                        </p>

                                        <p>
                                            <a href="#" class="btn btn-xs btn-default"><span
                                                    class="glyphicon glyphicon-comment"></span> <?= $this->t('Подать заявку'); ?>
                                            </a>
                                        </p>
                                    </div>
                                    <?php if ($this->escape($team['url_logo_car']) != '') { ?>
                                        <div class=" team_drivers_logo_wrapper_365 img-wrapper-365 overflow-hide">
                                            <a href="<?= $team_url; ?>">
                                                <img class="team_drivers_logo img-thumbnail img-responsive"
                                                     src="<?= $this->escape($team['url_logo_car']); ?>">
                                            </a>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="block-item clearfix">
                                <div class="section-title"><?= $this->t('Состав команды') . ":"; ?></div>
                                <?php
                                if ($championship_team_drivers_data) {
                                    /*
                                     * @TODO: Выводить сообщение, о том, что в команде нет гонщиков.
                                     */
                                    foreach ($championship_team_drivers_data as $driver):
                                        ?>
                                        <div class="team-driver-item block">
                                            <?php
                                            $driver_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'id', 'user_id' => $driver->user_id), 'defaultUserID', true);
                                            echo $this->BlockConfigMenu($this->t("Гонщик"))->championshipTeamDriverMenu($this->escape($this->leagueData['ID']), $team->championship_id, $team->team_id, $driver->user_id);
                                            ?>
                                            <div class="block-body media well">
                                                <div
                                                    class="team_drivers_logo_wrapper img-wrapper-100-100 overflow-hide pull-left img-circle dp">
                                                    <a href="<?= $driver_url; ?>" target="_blank">
                                                        <?= $this->getUserAvatar($driver->user_id, $driver->user_avatar_type, 'media-object img-responsive', 100); ?>
                                                    </a>
                                                </div>
                                                <div class="media-body">
                                                    <?php
                                                    $user_name = "";
                                                    if (isset($driver->user_surname) && !empty($driver->user_surname)) {
                                                        $user_name .= $this->escape($driver->user_surname) . " ";
                                                    }
                                                    if (isset($driver->user_name) && !empty($driver->user_name)) {
                                                        $user_name .= $this->escape($driver->user_name) . " ";
                                                    }
                                                    ?>
                                                    <h4 class="media-heading">
                                                        <a class="font-color-black" href="<?= $driver_url; ?>"
                                                           target="_blank"><?= $user_name; ?></a>
                                                        <small> <?= $driver->country_NativeName ?>
                                                            (<?= $driver->country_EnglishName ?>)
                                                        </small>
                                                    </h4>
                                                    <hr style="margin:8px auto">
                                                    <span class="label"><img class="img-size-32 team_driver_flag"
                                                                             src="<?= $driver->country_ImageRoundUrl ?>"
                                                                             title="<?= $driver->country_NativeName ?> (<?= $driver->country_EnglishName ?>)"></span>
                                                    <span
                                                        class="label label-default"><?= $this->t('Номер') . ': ' . $driver->driver_number; ?></span>
                                                </div>
                                            </div>
                                        </div>
                                    <?php
                                    endforeach;
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php } ?>