<?php if ($this->championshipTeams) { ?>
    <?php foreach ($this->championshipTeams as $team): ?>
        <div class="team_item block_item">
            <?php
            echo $this->ConfigureBlockItemMenu($this->translate("Команда"))->championship_team_menu($this->escape($this->league_data->id), $this->escape($team->championship_id), $this->escape($team->team_id));
            ?>
            <div class="block_item_content">
                <span class="badge badge-warning team_number"><?php echo $team->team_number; ?></span>
                <div class="pull-left break-word-wrap block-width-390">
                    <?php if ($this->escape($team['url_logo_car']) != '') { ?>
                        <div class="img-thumbnail team_drivers_logo_wrapper_365 image_wrapper_365 overflow-hide">
                            <img class="team_drivers_logo image_size_365" src="<?php echo $this->escape($team['url_logo_car']); ?>">
                        </div>
                    <?php } ?>
                    <div class="img-thumbnail">
                        <div class="team_name">
                            <a href="<?php echo $this->url(array('controller' => 'championship', 'action' => 'team-show', 'league_id' => $this->league_data->id, 'championship_id' => $this->escape($team->championship_id), 'team_id' => $this->escape($team->team_id)), 'championshipTeam', true) ?>"><?php echo $this->escape($team['name']); ?></a>
                        </div>
                    </div>
                </div>
                <?php
                $championship_team_driver = new Application_Model_DbTable_ChampionshipTeamDriver();
                $championship_team_drivers_data = $championship_team_driver->getChampionshipTeamDrivers($this->escape($team->championship_id), $this->escape($team->team_id));
                if ($championship_team_drivers_data) {
                    foreach ($championship_team_drivers_data as $driver):
                        ?>
                        <div class="team_driver_item block_item block-width-135 pull-left">
                            <?php
                            echo $this->ConfigureBlockItemMenu($this->translate("Гонщик"))->championship_team_driver_menu($this->escape($this->league_data->id), $team->championship_id, $team->team_id, $driver->user_id);
                            ?>
                            <div class="block_item_content">
                                <div class="img-thumbnail team_drivers_logo_wrapper_70 image_wrapper_70 overflow-hide pull-left">
                                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $driver->user_id), 'userId', true) ?>" target="_blank">
                                        <?php echo $this->getUserAvatar($driver->user_id, $driver->user_avatar_type, 'image_size_70', 100); ?>
                                    </a>
                                </div>
                                <span class="badge team_driver_number"><?php echo $this->escape($driver->driver_number) ?></span>
                                <img class="image_size_32 team_driver_flag" src="<?php echo $driver->country_url_image_round ?>" title="<?php echo $driver->country_native_name ?> (<?php echo $driver->country_english_name ?>)">
                                <div class="team_driver_info break-word-wrap">
                                    <div><span class="font-bold font-color-black"><?php echo $this->translate("Имя"); ?>: </span><?php echo $this->escape($driver->user_name) ?></div>
                                    <div><span class="font-bold font-color-black"><?php echo $this->translate("Фамилия"); ?>: </span><?php echo $this->escape($driver->user_surname) ?></div>
                                </div>
                            </div>
                        </div>
                        <?php
                    endforeach;
                    if (count($championship_team_drivers_data) == 1) {
                        ?>
                        <div class="team_driver_item block_item block-width-135 pull-left">
                            <div class="block_item_content">
                                <div class="label label-info font-align-center align-center-block"><?php echo $this->translate("Место свободно"); ?></div>
                            </div>
                        </div>
                        <?php
                    }
                } else {
                    ?>
                    <div class="team_driver_item block_item block-width-135 pull-left">
                        <div class="block_item_content">
                            <div class="label label-info font-align-center align-center-block"><?php echo $this->translate("Место свободно"); ?></div>
                        </div>
                    </div>
                    <div class="team_driver_item block_item block-width-135 pull-left">
                        <div class="block_item_content">
                            <div class="label label-info font-align-center align-center-block"><?php echo $this->translate("Место свободно"); ?></div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php } ?>