<?php if ($this->errMessage != "") { ?>
    <div class="alert alert-error alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4><?php echo $this->translate('Ошибка!'); ?></h4>
        <?php echo $this->errMessage; ?>
    </div>
<?php } ?>
<?php echo $this->form; ?>
<script>
    jQuery(document).ready(function() {
        $("#date_start").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });

        $("#date_end").datepicker({
            showButtonPanel: true,
            dateFormat: "yy-mm-dd",
            showAnim: "clip"
        });
    });
</script>