<?php if ($this->championship) { ?>
    <?php if ($this->championship->hotlap_ip) { ?>
	<div class="block-item hotlap-block">
	    <div class="navbar navbar-default" role="navigation">
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-hotlap-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		    </button>
		</div>
		<div class="navbar-hotlap-collapse">
		    <p class="navbar-text hotlap-marquee">
			<iframe src="http://<?php echo $this->championship->hotlap_ip; ?>/rFactorHotlaps/Marquee.htm" name="standings" width="625" height="25" scrolling="no" id="standings" frameborder="0" style="background:none;"></iframe>
		    </p>
		    <ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate("Ссылки"); ?> <b class="caret"></b></a>
			    <ul class="dropdown-menu">
				<li><a href="http://<?php echo $this->championship->hotlap_ip; ?>/rFactorLive" target="_BLINK"><?php echo $this->translate('Прямой эфир') ?></a></li>
				<li><a href="http://<?php echo $this->championship->hotlap_ip; ?>/rFactorHotlaps?max=25" target="_BLINK"><?php echo $this->translate('Рекорды') ?></a></li>
				<li class="divider"></li>
				<li><a href="http://<?php echo $this->championship->hotlap_ip; ?>/rFactorLeagues" target="_BLINK"><?php echo $this->translate('Лиги') ?></a></li>
				<li><a href="http://<?php echo $this->championship->hotlap_ip; ?>/rFactorResults" target="_BLINK"><?php echo $this->translate('Результаты') ?></a></li>
			    </ul>
			</li>
		    </ul>
		</div>
	    </div>
	</div>
    <?php } ?>

    <div class="championship_item block-item">
	<?php
	echo $this->ConfigureBlockItemMenu($this->translate("Чемпионат"))->championship_menu($this->escape($this->championship->league_id), $this->escape($this->championship->id));
	?>
	<div class="row">
        <div class="block-item-content">
    	    <div class="col-lg-4 col-lg-push-8">
    		<div class="thumbnail text-align-center">
			<?php if ($this->championship->url_logo != '') {
			    ?>
			    <div class="img-thumbnail overflow-hide ">
				<img class="championship_id_logo img-responsive" src="<?php echo $this->escape($this->championship->url_logo); ?>">
			    </div>
			<?php } ?>
    		    <div class="caption">
    			<a href = "<?php echo $this->url(array('controller' => 'post', 'action' => 'id', 'post_id' => $this->escape($this->championship->game_id)), 'postId', true); ?>" target="_blank" class = "btn btn-sm btn-primary post_more" title="<?php echo $this->translate('Игра для проведения') ?>"><?php echo $this->translate('Игра') ?></a>
    			<br/><br/>
    			<a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'ds', 'league_id' => $this->escape($this->championship->league_id), 'championship_id' => $this->escape($this->championship->id)), 'championship', true); ?>" class = "btn btn-sm btn-success post_more" title="<?php echo $this->translate('Личный зачет') ?>"><?php echo $this->translate('ЛЗ') ?></a>
    			<a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'ts', 'league_id' => $this->escape($this->championship->league_id), 'championship_id' => $this->escape($this->championship->id)), 'championship', true); ?>" class = "btn btn-sm btn-warning post_more" title="<?php echo $this->translate('Командный зачет') ?>"><?php echo $this->translate('КЗ') ?></a>
    			<a href = "<?php echo $this->url(array('controller' => 'championship', 'action' => 'drivers', 'league_id' => $this->escape($this->championship->league_id), 'championship_id' => $this->escape($this->championship->id)), 'championship', true); ?>" class = "btn btn-sm btn-info post_more" title="<?php echo $this->translate('Гонщики') ?>"><?php echo $this->translate('Гонщики') ?></a>
    			<a href = "<?php echo $this->url(array('controller' => 'post', 'action' => 'id', 'post_id' => $this->escape($this->championship->post_id)), 'postId', true); ?>" target="_blank" class = "btn btn-sm btn-danger post_more" title="<?php echo $this->translate('Регламент чемпионата') ?>"><?php echo $this->translate('Регламент') ?></a>
    		    </div>
    		</div>
    	    </div>
    	    <div class="col-lg-8 col-lg-pull-4">
    		<div class="thumbnail championship_id_info_block">
    		    <table class="table table-striped font-veradana font-size-11">
    			<tbody>
    			    <tr>
    				<td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Название') ?>:</td>
    				<td class="cell-text-align-vert"><?php echo $this->escape($this->championship->name); ?></td>
    			    </tr>
    			    <tr>
    				<td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Администратор чемпионата') ?>:</td>
    				<td class="cell-text-align-vert"><a target="_blank" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'id', 'user_id' => $this->escape($this->championship->user_id)), 'userId', true); ?>"><?php echo $this->escape($this->championship->user_login); ?></a></td>
    			    </tr>
    			    <tr>
    				<td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Дата старта') ?>:</td>
    				<td class="cell-text-align-vert"><?php echo $this->escape($this->championship->date_start); ?></td>
    			    </tr>
    			    <tr>
    				<td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Дата окончания') ?>:</td>
    				<td class="cell-text-align-vert"><?php echo $this->escape($this->championship->date_end); ?></td>
    			    </tr>
    			    <tr>
    				<td class="font-bold cell-text-align-vert cell-width-150"><?php echo $this->translate('Описание') ?>:</td>
    				<td class="cell-text-align-vert">
					<?php
					if ($this->championship->description != "") {
					    echo $this->RenderContentTypeText($this->championship->description, 'bbcode');
					} else {
					    echo $this->translate("Нет описания.");
					}
					?>
    				</td>
    			    </tr>
    			</tbody>
    		    </table>
    		</div>
    	    </div>
        </div>
	    </div>
	<div class="block-item-info-bottom">
    	    <div class="content_category block-item-info-bottom-item">
    		<span class="font-bold font-color-black"><?php echo $this->translate('Категория контента') ?>: </span>
		    <?php echo $this->translate('Чемпионат'); ?>
    	    </div>
    	</div>
    </div>
    <!-- Races start -->
	<?php if (count($this->paginator)) { ?>
    <div class="section-title"><?php echo $this->translate('Гонки чемпионата') ?></div>
	<?php foreach ($this->paginator as $race): ?>
	    <div class="race_item block-item">
		<?php
		echo $this->ConfigureBlockItemMenu($this->translate("Гонка"))->championship_race_menu($this->escape($race['id']));
		?>
	        <div class="block-item_header">
	    	<div class="block-item_title">
	    	    <img class="img-size-40-40" src="<?php echo $this->baseUrl($this->escape($race['country_url_image_round'])); ?>">
	    	    <i class="icon-flag-checkered"></i>
	    	    <a href="<?php echo $this->url(array('controller' => 'race', 'action' => 'id', 'championship_id' => $this->championship->id, 'race_id' => $this->escape($race['id'])), 'championshipRaceId', true); ?>"><?php echo $this->escape($race['name']); ?></a>
	    	</div>
	    	<div class="block-item_info_header">
	    	    <div class="content_category block-item_info_header_item">
	    		<span class="font-bold font-color-black"><i class="fa fa-filter font-color-gray"></i> <?php echo $this->translate('Категория контента') ?>: </span>
			    <?php echo $this->translate('Гонка'); ?>
	    	    </div>
	    	</div>
	        </div>
	        <div class="block-item-content">
	    	<div class="championship_all_logo_wrapper_150_150 img-wrapper-150-150 pull-left overflow-hide">
	    	    <img class="img-size-150 img-responsive img-thumbnail" src="<?php echo $this->baseUrl($this->escape($race['track_url_scheme'])); ?>">
	    	</div>
	    	<div class="block-content-text">
			<?php
			if ($race['description'] != NULL) {
			    echo $this->RenderContentTypeText($race['description'], 'bbcode');
			} else {
			    echo $this->translate('Нет описания');
			}
			?>
	    	</div>
	    	<div class="pull-right">
	    	    <a href = "<?php echo $this->url(array('controller' => 'race', 'action' => 'id', 'championship_id' => $this->championship->id, 'race_id' => $this->escape($race['id'])), 'championshipRaceId', true); ?>" class = "btn btn-sm btn-primary block-content-button-more" title="<?php echo $this->translate('Детальная информация о гонке') ?>"><?php echo $this->translate('Подробнее...') ?></a>
	    	</div>
	    	<div class="championship-block-item-info block-item-info-bottom">
	    	    <div class="championship_date_create block-item-info-bottom-item">
	    		<span class="font-bold font-color-black"><?php echo $this->translate('Создан') ?>: </span>
			    <?php echo $this->escape($race['date_create']); ?>
	    	    </div>
	    	</div>
	        </div>
	    </div>
	<?php endforeach; ?>
	<?php
	echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/default_pagination_tpl.phtml');
    } ?>
    <!-- Races end -->
<?php } ?>