<div id="admin_articles_page" class="page">
    <div class="page_title"><?php echo $this->translate('Контент сайта'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            ?>
            <div class="articles_data img-polaroid">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <td class="article_id"><span>#</span></td>
                            <td class="article_title"><span><?php echo $this->translate('Заголовок'); ?></span></td>
                            <td class="article_author"><span><?php echo $this->translate('Автор'); ?></span></td>
                            <td class="article_type"><span><?php echo $this->translate('Тип контента'); ?></span></td>
                            <td class="article_date"><span><?php echo $this->translate('Дата'); ?></span></td>
                            <td class="article_action"><span><?php echo $this->translate('Действие'); ?></span></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $item): ?>
                            <tr>
                                <td class="article_id"><span><a href="<?php echo $this->baseUrl('article/view/' . $this->escape($item['id'])) ?>"><?php echo $this->escape($item['id']); ?></a></span></td>
                                <td class="article_title"><span><a href="<?php echo $this->baseUrl('article/view/' . $this->escape($item['id'])) ?>"><?php echo $this->escape($item['title']); ?></a></span></td>
                                <td class="article_author"><span><a href="<?php echo $this->baseUrl('user/info/' . $this->escape($item['user_id'])) ?>"><?php echo $item['login']; ?></a></span></td>
                                <td class="article_type"><span><a href="<?php echo $this->baseUrl('articletype/id/' . $this->escape($item['article_type_id'])) ?>"><?php echo $this->escape($this->escape($item['name'])); ?></a></span></td>
                                <td class="article_date"><span><?php echo $this->escape($this->escape($item['date_edit'])); ?></span></td>
                                <td class="article_action">
                                    <span>
                                        <a href="<?php echo $this->baseUrl('article/id/' . $this->escape($item['id'])) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('article/edit/' . $this->escape($item['id'])) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('article/delete/' . $this->escape($item['id'])) ?>"><i class="icon-remove"></i> <?php echo $this->translate('Удал.'); ?></a><br/>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml'); ?>
            <?php
        } else {
            echo $this->translate('Контент не найден на сайте!');
        }
        ?>
    </div>
</div>