<div id="admin_leagues_page" class="page">
    <div class="page_title"><?php echo $this->translate('Лиги'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/full_views_pagination_control.phtml');
            ?>
            <div class="leagues_data img-polaroid">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <td class="league_id"><span>#</span></td>
                            <td class="league_name"><span><?php echo $this->translate('Название'); ?></span></td>
                            <td class="league_descr"><span><?php echo $this->translate('Описание'); ?></span></td>
                            <td class="league_action"><span><?php echo $this->translate('Действие'); ?></span></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $league): ?>
                            <tr>
                                <td class="league_id"><span><a href="<?php echo $this->baseURL('league/id/' . $this->escape($league['id'])) ?>"><?php echo $this->escape($league['id']) ?></a></span></td>
                                <td class="league_name"><span><a href="<?php echo $this->baseURL('league/id/' . $this->escape($league['id'])) ?>"><?php echo $this->escape($league['name']) ?></a></span></td>
                                <td class="league_descr"><span><?php echo $this->truncate($this->escape($league['description']))->toLength(200); ?></span></td>
                                <td class="league_action">
                                    <span>
                                        <a href="<?php echo $this->baseUrl('league/id/' . $this->escape($league['id'])) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('league/edit/' . $this->escape($league['id'])) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('league/delete/' . $this->escape($league['id'])) ?>"><i class="icon-remove"></i> <?php echo $this->translate('Удал.'); ?></a><br/>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/article_all_pagination_control.phtml');
            ?>
            <?php
        } else {
            ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4><?php echo $this->translate('Ошибка!'); ?></h4>
                <?php echo $this->translate('Лиги на сайте не найдены!'); ?>
            </div>
        <?php } ?>
    </div>
</div>