<div id="articles_page" class="page">
    <div class="page_title"><?php echo $this->translate('Пользователи'); ?></div>
    <div class="div_hr"></div>
    <div class="page_content">
        <?php
        if (count($this->paginator)) {
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml');
            ?>
            <div class="users_data img-polaroid">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <td><span>#</span></td>
                            <td><span><?php echo $this->translate('Логин'); ?></span></td>
                            <td><span><?php echo $this->translate('Активация'); ?></span></td>
                            <td><span><?php echo $this->translate('Статус'); ?></span></td>
                            <td><span><?php echo $this->translate('Последний визит'); ?></span></td>
                            <td class="article_action"><span><?php echo $this->translate('Действие'); ?></span></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $user): ?>
                            <tr>
                                <td><span><a href="<?php echo $this->baseURL('user/info/'.$this->escape($user['id']))?>"><?php echo $this->escape($user['id']) ?></a></span></td>
                                <td><span><a href="<?php echo $this->baseURL('user/info/'.$this->escape($user['id']))?>"><?php echo $this->escape($user['login']) ?></a></span></td>
                                <td><span><?php echo $this->escape($user['activate']) ?></span></td>
                                <td><span><?php echo ($this->escape($user['enabled']) == 1) ? $this->translate('Активный') : $this->translate('Забанен') ?></span></td>
                                <td><span><?php echo $this->escape($user['last_login']) ?></span></td>
                                <td class="article_action"><span>
                                        <a href="<?php echo $this->baseUrl('user/edit/' . $this->escape($user['id'])) ?>"><i class="icon-edit"></i> <?php echo $this->translate('Ред.'); ?></a><br/>
                                        <a href="<?php echo $this->baseUrl('user/info/' . $this->escape($user['id'])) ?>"><i class="icon-eye-open"></i> <?php echo $this->translate('Просм.'); ?></a>
                                    </span></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagers/user_all_pagination_control.phtml'); ?>
            <?php
        } else {
            echo $this->translate('Контент не найден на сайте!');
        }
        ?>
    </div>
</div>