<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="1" align="center" bgcolor="#DDDDDD" style="font-family:verdana, arial, helvetica; font-size:13px; padding:50px 0; height:100%;">
    <tr valign="middle">
        <td>
            <table cellspacing="5px" width="800px" bgcolor="#FFFFFF" align="center" style="border:1px solid #cccccc;">
                <tr>
                    <td>
                        <table width="100%" cellspacing="0" cellpadding="0" style="padding:0; border:1px solid #cccccc;">
                            <tr>
                                <td>
                                    <table bgcolor="#F2F2F2" cellspacing="0" border="0" width="100%" style="padding:3px;">
                                        <tr>
                                            <td>
                                                <a href="http://Online-Racing.net"><img src="http://Online-Racing.net/img/logo_190.png" alt="Перейти на сайт"></a>

                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table cellspacing="0" cellpadding="10" style="font-size:13px; ">
                                        <tr>
                                            <td>
                                                <p>
                                                    Доброго времени суток, <strong><?= $this->login; ?></strong>.
                                                </p>
                                                <p>
                                                    Пароль от вашей <a href="http://online-racing.net/user/id/<?= $this->user_id; ?>">учетной записи</a>, на сайте <a href="http://Online-Racing.net">Online-Racing.Net</a> был изминен.
                                                </p>
                                                <p>
                                                    <strong>Новый пароль:</strong> <?= $this->password; ?>
                                                </p>
                                                <p><span style="color:gray;">_______________</span><br/>
                                                    С уважением, администрация сайта <a href="http://Online-Racing.net">online-racing.net</a>
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:0;">
                                    <table width="100%" bgcolor="#F2F2F2" align="center" style="padding:3px; font-size:10px;">
                                        <tr style="height:50px;">
                                            <td align="center" style="color:#958989;">
                                                2012 © <a href="http://Online-Racing.net" style="color:#958989;">Online-Racing.net</a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>