<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="1" align="center" bgcolor="#DDDDDD"
       style="font-family:verdana, arial, helvetica; font-size:13px; padding:50px 0; height:100%;">
    <tr valign="middle">
        <td>
            <table cellspacing="5px" width="800px" bgcolor="#FFFFFF" align="center" style="border:1px solid #cccccc;">
                <tr>
                    <td>
                        <table width="100%" cellspacing="0" cellpadding="0"
                               style="padding:0; border:1px solid #cccccc;">
                            <tr>
                                <td>
                                    <table bgcolor="#F2F2F2" cellspacing="0" border="0" width="100%"
                                           style="padding:3px;">
                                        <tr>
                                            <td>
                                                <a href="http://Online-Racing.net">
                                                    <img src="http://Online-Racing.net/img/logo_190.png"
                                                         alt="Перейти на сайт">
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table cellspacing="0" cellpadding="10" style="font-size:13px; ">
                                        <tr>
                                            <td>
                                                <p>
                                                    Здравствуйте, <?= $this->Name; ?> <?= $this->Surname; ?>
                                                    (<?= $this->NickName; ?>).
                                                </p>
                                                <p>
                                                    Пароль для вашего аккаунта <?= $this->Email; ?> на портале
                                                    <a href="http://online-racing.net">Online-Racing.Net</a> был успешно изменен.
                                                </p>
                                                <br/>
                                                <p>
                                                <h2>Данные вашего аккаунта:</h2>
                                                <table border="1" style="font-size:14px;">
                                                    <tbody>
                                                    <tr>
                                                        <td><strong>Имя</strong></td>
                                                        <td><?= $this->Name; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>Фамилия</strong></td>
                                                        <td><?= $this->Surname; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>Никнейм</strong></td>
                                                        <td><?= $this->NickName; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>E-Mail</strong></td>
                                                        <td><?= $this->Email; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>Пароль</strong></td>
                                                        <td style="color:red"><?= $this->Password; ?></td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                                </p>
                                                <br/>
                                                <p>
                                                    Для авторизации на сайте перейдите на страницу
                                                    <a href="<?= $this->SignInUrl; ?>">
                                                        <?= $this->SignInUrl; ?>
                                                    </a>
                                                    и введите перечисленные выше данные.<br/>
                                                </p>
                                                <p>
                                                    <span style="color:gray;">_______________</span><br/>
                                                    С уважением, администрация сайта <a href="http://online-racing.net">Online-Racing.Net</a>.
                                                    Да пребудет с вами скорость (c) 2012-2014.
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:0;">
                                    <table width="100%" bgcolor="#F2F2F2" align="center"
                                           style="padding:3px; font-size:10px;">
                                        <tr style="height:30px;">
                                            <td align="left" style="color:#958989; font-size:12px">
                                                2012-2014 © <a href="http://Online-Racing.net" style="color:#958989;">Online-Racing.net</a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>