<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="clearfix m-b-10">
			<?php
			$privilege_id_url = $this->url(array('module' => 'admin', 'controller' => 'privilege', 'action' => 'add'), 'default', true);
			?>
			<a href="<?= $privilege_id_url ?>" class="btn btn-success pull-right "><i class="fa fa-plus"></i> <?= $this->translate('Добавить привилегию ресурса'); ?></a>
		</div>
	</div>
</div>
<?php if ($this->privileges_data) { ?>
	<div class="row">
		<div class="col-md-12 col-lg-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<i class="fa fa-list"></i>
				</div>
				<div class="panel-body">
					<table class="table table-striped custab">
						<thead>
							<tr>
								<th class="privilege_id"><span>ID</span></th>
								<th class="privilege_name"><span><?= $this->translate('Название'); ?></span></th>
								<th class="privilege_resource"><span><?= $this->translate('Ресурс'); ?></span></th>
								<th class="privilege_descr"><span><?= $this->translate('Описание'); ?></span></th>
								<th class="privilege_date_create"><span><?= $this->translate('Дата создания'); ?></span></th>
								<th class="privilege_date_edit"><span><?= $this->translate('Дата редактирования'); ?></span></th>
								<th class="privilege_action"><span><?= $this->translate('Действие'); ?></span></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->privileges_data as $privilege): ?>
								<?php
								$privilege_id_url = $this->url(array('module' => 'admin', 'controller' => 'privilege', 'action' => 'id', 'privilege_id' => $this->escape($privilege->id)), 'adminPrivilegeId', true);
								$privilege_edit_url = $this->url(array('module' => 'admin', 'controller' => 'privilege', 'action' => 'edit', 'privilege_id' => $this->escape($privilege->id)), 'adminPrivilegeAction', true);
								$privilege_delete_url = $this->url(array('module' => 'admin', 'controller' => 'privilege', 'action' => 'delete', 'privilege_id' => $this->escape($privilege->id)), 'adminPrivilegeAction', true);

								$resource_id_url = $this->url(array('module' => 'admin', 'controller' => 'resource', 'action' => 'id', 'resource_id' => $this->escape($privilege->resource_id)), 'adminResourceId', true);
								?>
								<tr>
									<td class="privilege_id"><span><a href="<?= $privilege_id_url; ?>"><?= $this->escape($privilege->id) ?></a></span></td>
									<td class="privilege_name"><span><a href="<?= $privilege_id_url ?>"><?= $this->escape($privilege->name) ?></a></span></td>
									<td class="privilege_resource"><span><a href="<?= $resource_id_url ?>"><?= $this->escape($privilege->resource_id) ?></a></span></td>
									<td class="privilege_descr"><span><?= $this->truncate($this->escape($privilege->description))->toLength(100); ?></span></td>
									<td class="privilege_date_create"><span><?= $this->escape($privilege->date_create); ?></span></td>
									<td class="privilege_dae_edit"><span><?= $this->escape($privilege->date_edit); ?></span></td>
									<td class="privilege_action">
										<span>
											<div class="pull-right action-buttons">
												<div class="btn-group pull-right">
													<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
														<span class="fa fa-cog fa-lg" style="margin-right: 0px;"></span>
													</button>
													<ul class="dropdown-menu slidedown">
														<li><a href="<?= $privilege_id_url ?>"><i class="fa fa-eye"></i> <?= $this->translate('Просмотреть'); ?></a></li>
														<li><a href="<?= $privilege_edit_url ?>"><i class="fa fa-pencil"></i> <?= $this->translate('Редактировать'); ?></a></li>
														<li><a href="<?= $privilege_delete_url ?>"><i class="fa fa-trash-o"></i> <?= $this->translate('Удалить'); ?></a></li>
													</ul>
												</div>
											</div>
										</span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="pull-right">
						<?= $this->paginationControl($this->privileges_data, 'Sliding', 'pagers/default_pagination_tpl.phtml'); ?>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>